//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package uuid ;import (_c "crypto/rand";_ff "encoding/hex";_d "io";);var _e =_c .Reader ;type UUID [16]byte ;var Nil =_fbf ;func _a (_ef []byte ,_fbe UUID ){_ff .Encode (_ef ,_fbe [:4]);_ef [8]='-';_ff .Encode (_ef [9:13],_fbe [4:6]);_ef [13]='-';_ff .Encode (_ef [14:18],_fbe [6:8]);
_ef [18]='-';_ff .Encode (_ef [19:23],_fbe [8:10]);_ef [23]='-';_ff .Encode (_ef [24:],_fbe [10:]);};func (_da UUID )String ()string {var _cg [36]byte ;_a (_cg [:],_da );return string (_cg [:])};func MustUUID ()UUID {uuid ,_fb :=NewUUID ();if _fb !=nil {panic (_fb );
};return uuid ;};func NewUUID ()(UUID ,error ){var uuid UUID ;_ ,_g :=_d .ReadFull (_e ,uuid [:]);if _g !=nil {return _fbf ,_g ;};uuid [6]=(uuid [6]&0x0f)|0x40;uuid [8]=(uuid [8]&0x3f)|0x80;return uuid ,nil ;};var _fbf UUID ;