//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package errors ;import (_f "fmt";_ff "golang.org/x/xerrors";);func Error (processName ,message string )error {return _g (message ,processName )};type processError struct{_be string ;_a string ;_af string ;_ae error ;};func _g (_ag ,_eb string )*processError {return &processError {_be :"\u005b\u0055\u006e\u0069\u0050\u0044\u0046\u005d",_af :_ag ,_a :_eb };
};func (_d *processError )Unwrap ()error {return _d ._ae };func Errorf (processName ,message string ,arguments ...interface{})error {return _g (_f .Sprintf (message ,arguments ...),processName );};var _ _ff .Wrapper =(*processError )(nil );func Wrap (err error ,processName ,message string )error {if _ec ,_aeff :=err .(*processError );
_aeff {_ec ._be ="";};_fe :=_g (message ,processName );_fe ._ae =err ;return _fe ;};func Wrapf (err error ,processName ,message string ,arguments ...interface{})error {if _cd ,_ga :=err .(*processError );_ga {_cd ._be ="";};_bd :=_g (_f .Sprintf (message ,arguments ...),processName );
_bd ._ae =err ;return _bd ;};func (_e *processError )Error ()string {var _aef string ;if _e ._be !=""{_aef =_e ._be ;};_aef +="\u0050r\u006f\u0063\u0065\u0073\u0073\u003a "+_e ._a ;if _e ._af !=""{_aef +="\u0020\u004d\u0065\u0073\u0073\u0061\u0067\u0065\u003a\u0020"+_e ._af ;
};if _e ._ae !=nil {_aef +="\u002e\u0020"+_e ._ae .Error ();};return _aef ;};