//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package errors ;import (_e "fmt";_c "golang.org/x/xerrors";);func Wrap (err error ,processName ,message string )error {if _f ,_cdb :=err .(*processError );_cdb {_f ._eg ="";};_bf :=_cd (message ,processName );_bf ._ca =err ;return _bf ;};func Error (processName ,message string )error {return _cd (message ,processName )};
func _cd (_gf ,_eb string )*processError {return &processError {_eg :"\u005b\u0055\u006e\u0069\u0050\u0044\u0046\u005d",_ge :_gf ,_ba :_eb };};func Wrapf (err error ,processName ,message string ,arguments ...interface{})error {if _fc ,_ea :=err .(*processError );
_ea {_fc ._eg ="";};_cb :=_cd (_e .Sprintf (message ,arguments ...),processName );_cb ._ca =err ;return _cb ;};var _ _c .Wrapper =(*processError )(nil );func (_d *processError )Error ()string {var _a string ;if _d ._eg !=""{_a =_d ._eg ;};_a +="\u0050r\u006f\u0063\u0065\u0073\u0073\u003a "+_d ._ba ;
if _d ._ge !=""{_a +="\u0020\u004d\u0065\u0073\u0073\u0061\u0067\u0065\u003a\u0020"+_d ._ge ;};if _d ._ca !=nil {_a +="\u002e\u0020"+_d ._ca .Error ();};return _a ;};func (_ee *processError )Unwrap ()error {return _ee ._ca };func Errorf (processName ,message string ,arguments ...interface{})error {return _cd (_e .Sprintf (message ,arguments ...),processName );
};type processError struct{_eg string ;_ba string ;_ge string ;_ca error ;};