//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package xmputil provides abstraction used by the pdf document XMP Metadata.
package xmputil ;import (_ea "errors";_bd "fmt";_e "github.com/trimmer-io/go-xmp/models/pdf";_fa "github.com/trimmer-io/go-xmp/models/xmp_base";_ef "github.com/trimmer-io/go-xmp/models/xmp_mm";_d "github.com/trimmer-io/go-xmp/xmp";_faf "github.com/unidoc/unipdf/v4/core";
_ca "github.com/unidoc/unipdf/v4/internal/timeutils";_b "github.com/unidoc/unipdf/v4/internal/uuid";_g "github.com/unidoc/unipdf/v4/model/xmputil/pdfaextension";_dd "github.com/unidoc/unipdf/v4/model/xmputil/pdfaid";_c "strconv";_dc "time";);

// SetPdfAID sets up pdfaid xmp metadata.
// In example: Part: '1' Conformance: 'B' states for PDF/A 1B.
func (_dfg *Document )SetPdfAID (part int ,conformance string )error {_cdg ,_bbf :=_dd .MakeModel (_dfg ._a );if _bbf !=nil {return _bbf ;};_cdg .Part =part ;_cdg .Conformance =conformance ;if _eafb :=_cdg .SyncToXMP (_dfg ._a );_eafb !=nil {return _eafb ;
};return nil ;};

// MediaManagementOptions are the options for the Media management xmp metadata.
type MediaManagementOptions struct{

// OriginalDocumentID  as media is imported and projects is started, an original-document ID
// must be created to identify a new document. This identifies a document as a conceptual entity.
// By default, this value is generated.
OriginalDocumentID string ;

// NewDocumentID is a flag which generates a new Document identifier while setting media management.
// This value should be set to true only if the document is stored and saved as new document.
// Otherwise, if the document is modified and overwrites previous file, it should be set to false.
NewDocumentID bool ;

// DocumentID when a document is copied to a new file path or converted to a new format with
// Save As, another new document ID should usually be assigned. This identifies a general version or
// branch of a document. You can use it to track different versions or extracted portions of a document
// with the same original-document ID.
// By default, this value is generated if NewDocumentID is true or previous doesn't exist.
DocumentID string ;

// InstanceID to track a document’s editing history, you must assign a new instance ID
// whenever a document is saved after any changes. This uniquely identifies an exact version of a
// document. It is used in resource references (to identify both the document or part itself and the
// referenced or referencing documents), and in document-history resource events (to identify the
// document instance that resulted from the change).
// By default, this value is generated.
InstanceID string ;

// DerivedFrom references the source document from which this one is derived,
// typically through a Save As operation that changes the file name or format. It is a minimal reference;
// missing components can be assumed to be unchanged. For example, a new version might only need
// to specify the instance ID and version number of the previous version, or a rendition might only need
// to specify the instance ID and rendition class of the original.
// By default, the derived from structure is filled from previous XMP metadata (if exists).
DerivedFrom string ;

// VersionID are meant to associate the document with a product version that is part of a release process. They can be useful in tracking the
// document history, but should not be used to identify a document uniquely in any context.
// Usually it simply works by incrementing integers 1,2,3...
// By default, this values is incremented or set to the next version number.
VersionID string ;

// ModifyComment is a comment to given modification
ModifyComment string ;

// ModifyDate is a custom modification date for the versions.
// By default, this would be set to time.Now().
ModifyDate _dc .Time ;

// Modifier is a person who did the modification.
Modifier string ;};

// GetPdfInfo gets the document pdf info.
func (_eee *Document )GetPdfInfo ()(*PdfInfo ,bool ){_gc :=PdfInfo {};var _cac *_faf .PdfObjectDictionary ;_ega :=func (_bga string ,_ag _faf .PdfObject ){if _cac ==nil {_cac =_faf .MakeDict ();};_cac .Set (_faf .PdfObjectName (_bga ),_ag );};_aff ,_fad :=_eee ._a .FindModel (_e .NsPDF ).(*_e .PDFInfo );
if !_fad {_bb ,_bfb :=_eee ._a .FindModel (_fa .NsXmp ).(*_fa .XmpBase );if !_bfb {return nil ,false ;};if _bb .CreatorTool !=""{_ega ("\u0043r\u0065\u0061\u0074\u006f\u0072",_faf .MakeString (string (_bb .CreatorTool )));};if !_bb .CreateDate .IsZero (){_ega ("\u0043\u0072\u0065a\u0074\u0069\u006f\u006e\u0044\u0061\u0074\u0065",_faf .MakeString (_ca .FormatPdfTime (_bb .CreateDate .Value ())));
};if !_bb .ModifyDate .IsZero (){_ega ("\u004do\u0064\u0044\u0061\u0074\u0065",_faf .MakeString (_ca .FormatPdfTime (_bb .ModifyDate .Value ())));};_gc .InfoDict =_cac ;return &_gc ,true ;};_gc .Copyright =_aff .Copyright ;_gc .PdfVersion =_aff .PDFVersion ;
_gc .Marked =bool (_aff .Marked );if len (_aff .Title )> 0{_ega ("\u0054\u0069\u0074l\u0065",_faf .MakeString (_aff .Title .Default ()));};if len (_aff .Author )> 0{_ega ("\u0041\u0075\u0074\u0068\u006f\u0072",_faf .MakeString (_aff .Author [0]));};if _aff .Keywords !=""{_ega ("\u004b\u0065\u0079\u0077\u006f\u0072\u0064\u0073",_faf .MakeString (_aff .Keywords ));
};if len (_aff .Subject )> 0{_ega ("\u0053u\u0062\u006a\u0065\u0063\u0074",_faf .MakeString (_aff .Subject .Default ()));};if _aff .Creator !=""{_ega ("\u0043r\u0065\u0061\u0074\u006f\u0072",_faf .MakeString (string (_aff .Creator )));};if _aff .Producer !=""{_ega ("\u0050\u0072\u006f\u0064\u0075\u0063\u0065\u0072",_faf .MakeString (string (_aff .Producer )));
};if _aff .Trapped {_ega ("\u0054r\u0061\u0070\u0070\u0065\u0064",_faf .MakeName ("\u0054\u0072\u0075\u0065"));};if !_aff .CreationDate .IsZero (){_ega ("\u0043\u0072\u0065a\u0074\u0069\u006f\u006e\u0044\u0061\u0074\u0065",_faf .MakeString (_ca .FormatPdfTime (_aff .CreationDate .Value ())));
};if !_aff .ModifyDate .IsZero (){_ega ("\u004do\u0064\u0044\u0061\u0074\u0065",_faf .MakeString (_ca .FormatPdfTime (_aff .ModifyDate .Value ())));};_gc .InfoDict =_cac ;return &_gc ,true ;};

// NewDocument creates a new document without any previous xmp information.
func NewDocument ()*Document {_ec :=_d .NewDocument ();return &Document {_a :_ec }};

// Document is an implementation of the xmp document.
// It is a wrapper over go-xmp/xmp.Document that provides some Pdf predefined functionality.
type Document struct{_a *_d .Document };

// SetPdfAExtension sets the pdfaExtension XMP metadata.
func (_ab *Document )SetPdfAExtension ()error {_bc ,_fd :=_g .MakeModel (_ab ._a );if _fd !=nil {return _fd ;};if _fd =_g .FillModel (_ab ._a ,_bc );_fd !=nil {return _fd ;};if _fd =_bc .SyncToXMP (_ab ._a );_fd !=nil {return _fd ;};return nil ;};

// PdfAID is the result of the XMP pdfaid metadata.
type PdfAID struct{Part int ;Conformance string ;Rev int ;};

// MediaManagement are the values from the document media management metadata.
type MediaManagement struct{

// OriginalDocumentID  as media is imported and projects is started, an original-document ID
// must be created to identify a new document. This identifies a document as a conceptual entity.
OriginalDocumentID GUID ;

// DocumentID when a document is copied to a new file path or converted to a new format with
// Save As, another new document ID should usually be assigned. This identifies a general version or
// branch of a document. You can use it to track different versions or extracted portions of a document
// with the same original-document ID.
DocumentID GUID ;

// InstanceID to track a document’s editing history, you must assign a new instance ID
// whenever a document is saved after any changes. This uniquely identifies an exact version of a
// document. It is used in resource references (to identify both the document or part itself and the
// referenced or referencing documents), and in document-history resource events (to identify the
// document instance that resulted from the change).
InstanceID GUID ;

// DerivedFrom references the source document from which this one is derived,
// typically through a Save As operation that changes the file name or format. It is a minimal reference;
// missing components can be assumed to be unchanged. For example, a new version might only need
// to specify the instance ID and version number of the previous version, or a rendition might only need
// to specify the instance ID and rendition class of the original.
DerivedFrom *MediaManagementDerivedFrom ;

// VersionID are meant to associate the document with a product version that is part of a release process. They can be useful in tracking the
// document history, but should not be used to identify a document uniquely in any context.
// Usually it simply works by incrementing integers 1,2,3...
VersionID string ;

// Versions is the history of the document versions along with the comments, timestamps and issuers.
Versions []MediaManagementVersion ;};

// SetPdfAIDWithRev sets up pdfaid xmp metadata.
// In example: Part: '4' Conformance: 'F' Rev '2025' states for PDF/A 4F revised in 2025.
func (_ae *Document )SetPdfAIDWithRev (part int ,conformance string ,rev int )error {_agc ,_cg :=_dd .MakeModel (_ae ._a );if _cg !=nil {return _cg ;};_agc .Part =part ;_agc .Conformance =conformance ;_agc .Rev =rev ;if _egg :=_agc .SyncToXMP (_ae ._a );
_egg !=nil {return _egg ;};return nil ;};

// GetPdfAID gets the pdfaid xmp metadata model.
func (_gbg *Document )GetPdfAID ()(*PdfAID ,bool ){_gbf ,_ccg :=_gbg ._a .FindModel (_dd .Namespace ).(*_dd .Model );if !_ccg {return nil ,false ;};return &PdfAID {Part :_gbf .Part ,Conformance :_gbf .Conformance ,Rev :_gbf .Rev },true ;};

// PdfInfo is the xmp document pdf info.
type PdfInfo struct{InfoDict _faf .PdfObject ;PdfVersion string ;Copyright string ;Marked bool ;};

// GUID is a string representing a globally unique identifier.
type GUID string ;

// GetPdfaExtensionSchemas gets a pdfa extension schemas.
func (_abc *Document )GetPdfaExtensionSchemas ()([]_g .Schema ,error ){_db :=_abc ._a .FindModel (_g .Namespace );if _db ==nil {return nil ,nil ;};_da ,_eg :=_db .(*_g .Model );if !_eg {return nil ,_bd .Errorf ("\u0069\u006eva\u006c\u0069\u0064 \u006d\u006f\u0064\u0065l f\u006fr \u0070\u0064\u0066\u0061\u0045\u0078\u0074en\u0073\u0069\u006f\u006e\u0073\u003a\u0020%\u0054",_db );
};return _da .Schemas ,nil ;};

// LoadDocument loads up the xmp document from provided input stream.
func LoadDocument (stream []byte )(*Document ,error ){_eac :=_d .NewDocument ();if _bf :=_d .Unmarshal (stream ,_eac );_bf !=nil {return nil ,_bf ;};return &Document {_a :_eac },nil ;};

// MediaManagementDerivedFrom is a structure that contains references of identifiers and versions
// from which given document was derived.
type MediaManagementDerivedFrom struct{OriginalDocumentID GUID ;DocumentID GUID ;InstanceID GUID ;VersionID string ;};

// MediaManagementVersion is the version of the media management xmp metadata.
type MediaManagementVersion struct{VersionID string ;ModifyDate _dc .Time ;Comments string ;Modifier string ;};

// MarshalIndent the document into xml byte stream with predefined prefix and indent.
func (_bg *Document )MarshalIndent (prefix ,indent string )([]byte ,error ){if _bg ._a .IsDirty (){if _gf :=_bg ._a .SyncModels ();_gf !=nil {return nil ,_gf ;};};return _d .MarshalIndent (_bg ._a ,prefix ,indent );};

// GetMediaManagement gets the media management metadata from provided xmp document.
func (_ead *Document )GetMediaManagement ()(*MediaManagement ,bool ){_caf :=_ef .FindModel (_ead ._a );if _caf ==nil {return nil ,false ;};_ddd :=make ([]MediaManagementVersion ,len (_caf .Versions ));for _eaf ,_afb :=range _caf .Versions {_ddd [_eaf ]=MediaManagementVersion {VersionID :_afb .Version ,ModifyDate :_afb .ModifyDate .Value (),Comments :_afb .Comments ,Modifier :_afb .Modifier };
};_cafc :=&MediaManagement {OriginalDocumentID :GUID (_caf .OriginalDocumentID .Value ()),DocumentID :GUID (_caf .DocumentID .Value ()),InstanceID :GUID (_caf .InstanceID .Value ()),VersionID :_caf .VersionID ,Versions :_ddd };if _caf .DerivedFrom !=nil {_cafc .DerivedFrom =&MediaManagementDerivedFrom {OriginalDocumentID :GUID (_caf .DerivedFrom .OriginalDocumentID ),DocumentID :GUID (_caf .DerivedFrom .DocumentID ),InstanceID :GUID (_caf .DerivedFrom .InstanceID ),VersionID :_caf .DerivedFrom .VersionID };
};return _cafc ,true ;};

// Marshal the document into xml byte stream.
func (_ff *Document )Marshal ()([]byte ,error ){if _ff ._a .IsDirty (){if _cb :=_ff ._a .SyncModels ();_cb !=nil {return nil ,_cb ;};};return _d .Marshal (_ff ._a );};

// GetGoXmpDocument gets direct access to the go-xmp.Document.
// All changes done to specified document would result in change of this document 'd'.
func (_gb *Document )GetGoXmpDocument ()*_d .Document {return _gb ._a };

// PdfInfoOptions are the options used for setting pdf info.
type PdfInfoOptions struct{InfoDict _faf .PdfObject ;PdfVersion string ;Copyright string ;Marked bool ;

// Overwrite if set to true, overwrites all values found in the current pdf info xmp model to the ones provided.
Overwrite bool ;};

// SetMediaManagement sets up XMP media management metadata: namespace xmpMM.
func (_gfb *Document )SetMediaManagement (options *MediaManagementOptions )error {_ba ,_dca :=_ef .MakeModel (_gfb ._a );if _dca !=nil {return _dca ;};if options ==nil {options =new (MediaManagementOptions );};_cc :=_ef .ResourceRef {};switch {case options .DocumentID !="":_ba .DocumentID =_d .GUID (options .DocumentID );
case options .NewDocumentID ||_ba .DocumentID .IsZero ():if !_ba .DocumentID .IsZero (){_cc .DocumentID =_ba .DocumentID ;};_eec ,_fc :=_b .NewUUID ();if _fc !=nil {return _fc ;};_ba .DocumentID =_d .GUID (_eec .String ());};if !_ba .InstanceID .IsZero (){_cc .InstanceID =_ba .InstanceID ;
};_ba .InstanceID =_d .GUID (options .InstanceID );if _ba .InstanceID ==""{_cag ,_cce :=_b .NewUUID ();if _cce !=nil {return _cce ;};_ba .InstanceID =_d .GUID (_cag .String ());};if !_cc .IsZero (){_ba .DerivedFrom =&_cc ;};_cd :=options .VersionID ;if _ba .VersionID !=""{_dad ,_df :=_c .Atoi (_ba .VersionID );
if _df !=nil {_cd =_c .Itoa (len (_ba .Versions )+1);}else {_cd =_c .Itoa (_dad +1);};};if _cd ==""{_cd ="\u0031";};_ba .VersionID =_cd ;if _dca =_ba .SyncToXMP (_gfb ._a );_dca !=nil {return _dca ;};return nil ;};

// SetPdfInfo sets the pdf info into selected document.
func (_fb *Document )SetPdfInfo (options *PdfInfoOptions )error {if options ==nil {return _ea .New ("\u006ei\u006c\u0020\u0070\u0064\u0066\u0020\u006f\u0070\u0074\u0069\u006fn\u0073\u0020\u0070\u0072\u006f\u0076\u0069\u0064\u0065\u0064");};_af ,_dbc :=_e .MakeModel (_fb ._a );
if _dbc !=nil {return _dbc ;};if options .Overwrite {*_af =_e .PDFInfo {};};if options .InfoDict !=nil {_ee ,_bcb :=_faf .GetDict (options .InfoDict );if !_bcb {return _bd .Errorf ("i\u006e\u0076\u0061\u006c\u0069\u0064 \u0070\u0064\u0066\u0020\u006f\u0062\u006a\u0065\u0063t\u0020\u0074\u0079p\u0065:\u0020\u0025\u0054",options .InfoDict );
};var _bfg *_faf .PdfObjectString ;for _ ,_bda :=range _ee .Keys (){switch _bda {case "\u0054\u0069\u0074l\u0065":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u0054\u0069\u0074l\u0065"));if _bcb {_af .Title =_d .NewAltString (_bfg );};case "\u0041\u0075\u0074\u0068\u006f\u0072":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u0041\u0075\u0074\u0068\u006f\u0072"));
if _bcb {_af .Author =_d .NewStringList (_bfg .String ());};case "\u004b\u0065\u0079\u0077\u006f\u0072\u0064\u0073":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u004b\u0065\u0079\u0077\u006f\u0072\u0064\u0073"));if _bcb {_af .Keywords =_bfg .String ();};case "\u0043r\u0065\u0061\u0074\u006f\u0072":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u0043r\u0065\u0061\u0074\u006f\u0072"));
if _bcb {_af .Creator =_d .AgentName (_bfg .String ());};case "\u0053u\u0062\u006a\u0065\u0063\u0074":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u0053u\u0062\u006a\u0065\u0063\u0074"));if _bcb {_af .Subject =_d .NewAltString (_bfg .String ());};case "\u0050\u0072\u006f\u0064\u0075\u0063\u0065\u0072":_bfg ,_bcb =_faf .GetString (_ee .Get ("\u0050\u0072\u006f\u0064\u0075\u0063\u0065\u0072"));
if _bcb {_af .Producer =_d .AgentName (_bfg .String ());};case "\u0054r\u0061\u0070\u0070\u0065\u0064":_bde ,_egf :=_faf .GetName (_ee .Get ("\u0054r\u0061\u0070\u0070\u0065\u0064"));if _egf {switch _bde .String (){case "\u0054\u0072\u0075\u0065":_af .Trapped =true ;
case "\u0046\u0061\u006cs\u0065":_af .Trapped =false ;default:_af .Trapped =true ;};};case "\u0043\u0072\u0065a\u0074\u0069\u006f\u006e\u0044\u0061\u0074\u0065":if _fde ,_gd :=_faf .GetString (_ee .Get ("\u0043\u0072\u0065a\u0074\u0069\u006f\u006e\u0044\u0061\u0074\u0065"));
_gd &&_fde .String ()!=""{_bcba ,_bfgf :=_ca .ParsePdfTime (_fde .String ());if _bfgf !=nil {return _bd .Errorf ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0043\u0072e\u0061\u0074\u0069\u006f\u006e\u0044\u0061t\u0065\u0020\u0066\u0069\u0065\u006c\u0064\u003a\u0020\u0025\u0077",_bfgf );
};_af .CreationDate =_d .NewDate (_bcba );};case "\u004do\u0064\u0044\u0061\u0074\u0065":if _fdb ,_ga :=_faf .GetString (_ee .Get ("\u004do\u0064\u0044\u0061\u0074\u0065"));_ga &&_fdb .String ()!=""{_bcbd ,_ffa :=_ca .ParsePdfTime (_fdb .String ());if _ffa !=nil {return _bd .Errorf ("\u0069n\u0076\u0061\u006c\u0069d\u0020\u004d\u006f\u0064\u0044a\u0074e\u0020f\u0069\u0065\u006c\u0064\u003a\u0020\u0025w",_ffa );
};_af .ModifyDate =_d .NewDate (_bcbd );};};};};if options .PdfVersion !=""{_af .PDFVersion =options .PdfVersion ;};if options .Marked {_af .Marked =_d .Bool (options .Marked );};if options .Copyright !=""{_af .Copyright =options .Copyright ;};if _dbc =_af .SyncToXMP (_fb ._a );
_dbc !=nil {return _dbc ;};return nil ;};