//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package pdfutil ;import (_ag "bytes";_g "errors";_f "fmt";_e "github.com/unidoc/unipdf/v4/common";_gf "github.com/unidoc/unipdf/v4/contentstream";_bd "github.com/unidoc/unipdf/v4/contentstream/draw";_ga "github.com/unidoc/unipdf/v4/core";_ge "github.com/unidoc/unipdf/v4/model";
_da "github.com/unidoc/unipdf/v4/ps";_a "io";_b "os";);

// MergePdfStreams merges several PDF streams passed as io.ReadSeeker and writes the result to output.
// isMergingForms controls if it is necessary to merge AcroForms from input streams.
// If you are not sure, you can always set isMergingForms to true.
func MergePdfStreams (inputs []_a .ReadSeeker ,output _a .Writer ,isMergingForms bool )error {return MergePdfStreamsWithOptions (inputs ,output ,MergePdfOptions {IsMergingForms :isMergingForms });};

// MergePdf merges several PDF files passed as inputPaths to one PDF file, outputPath.
// isMergingForms controls if it is necessary to merge AcroForms from input files.
// If you are not sure, you can always set isMergingForms to true.
func MergePdf (inputPaths []string ,outputPath string ,isMergingForms bool )error {return MergePdfWithFilePermissionAndOptions (inputPaths ,outputPath ,MergePdfOptions {IsMergingForms :isMergingForms },_b .FileMode (0644));};func _fef (_ce string ,_edc *_ge .PdfPageResources )([]byte ,error ){_ef :=_gf .NewContentStreamParser (_ce );
_de ,_ac :=_ef .Parse ();if _ac !=nil {return nil ,_ac ;};_bf :=&_gf .ContentStreamOperations {};_gfe :=map[_ga .PdfObjectName ]bool {};_bb :=map[_ga .PdfObjectName ]bool {};_fbc :=_gf .NewContentStreamProcessor (*_de );_fbc .AddHandler (_gf .HandlerConditionEnumAllOperands ,"",func (_ca *_gf .ContentStreamOperation ,_dg _gf .GraphicsState ,_dgg *_ge .PdfPageResources )error {_gb :=_ca .Operand ;
switch _gb {case "\u0043\u0053":if _fc (_dg .ColorspaceStroking ){_gfd :=_ca .Params [0].(*_ga .PdfObjectName );if *_gfd !="\u0050a\u0074\u0074\u0065\u0072\u006e"{_fac ,_ee :=_dgg .GetColorspaceByName (*_gfd );if !_ee {return _g .New ("\u0063\u006f\u006c\u006frs\u0070\u0061\u0063\u0065\u0020\u006e\u006f\u0074\u0020\u0064\u0065\u0066\u0069\u006ee\u0064");
};_afe ,_ee :=_fac .(*_ge .PdfColorspaceSpecialPattern );if !_ee {return _g .New ("\u0074\u0079\u0070\u0065\u0020\u0065\u0072\u0072\u006f\u0072");};if _afe .UnderlyingCS !=nil {_afe .UnderlyingCS =_ge .NewPdfColorspaceDeviceGray ();};_ac =_dgg .SetColorspaceByName (*_gfd ,_afe );
if _ac !=nil {return _ac ;};};*_bf =append (*_bf ,_ca );return nil ;};_ead :=_gf .ContentStreamOperation {};_ead .Operand =_gb ;_ead .Params =[]_ga .PdfObject {_ga .MakeName ("\u0044\u0065\u0076\u0069\u0063\u0065\u0047\u0072\u0061\u0079")};*_bf =append (*_bf ,&_ead );
return nil ;case "\u0063\u0073":if _fc (_dg .ColorspaceNonStroking ){_be :=_ca .Params [0].(*_ga .PdfObjectName );if *_be !="\u0050a\u0074\u0074\u0065\u0072\u006e"{_daa ,_ded :=_dgg .GetColorspaceByName (*_be );if !_ded {return _g .New ("\u0063\u006f\u006c\u006frs\u0070\u0061\u0063\u0065\u0020\u006e\u006f\u0074\u0020\u0064\u0065\u0066\u0069\u006ee\u0064");
};_gaa ,_ded :=_daa .(*_ge .PdfColorspaceSpecialPattern );if !_ded {return _g .New ("\u0074\u0079\u0070\u0065\u0020\u0065\u0072\u0072\u006f\u0072");};if _gaa .UnderlyingCS !=nil {_gaa .UnderlyingCS =_ge .NewPdfColorspaceDeviceGray ();};if _caa :=_dgg .SetColorspaceByName (*_be ,_gaa );
_caa !=nil {return _caa ;};};*_bf =append (*_bf ,_ca );return nil ;};_df :=_gf .ContentStreamOperation {};_df .Operand =_gb ;_df .Params =[]_ga .PdfObject {_ga .MakeName ("\u0044\u0065\u0076\u0069\u0063\u0065\u0047\u0072\u0061\u0079")};*_bf =append (*_bf ,&_df );
return nil ;case "\u0053\u0043","\u0053\u0043\u004e":if _fc (_dg .ColorspaceStroking ){_edca :=_gf .ContentStreamOperation {};_edca .Operand =_gb ;_edca .Params =[]_ga .PdfObject {};_fd ,_gdf :=_dg .ColorStroking .(*_ge .PdfColorPattern );if !_gdf {return _g .New ("i\u006e\u0076\u0061\u006c\u0069\u0064 \u0073\u0074\u0072\u006f\u006b\u0069\u006e\u0067\u0020c\u006f\u006c\u006fr\u0020t\u0079\u0070\u0065");
};if _fd .Color !=nil {_eb ,_dbb :=_dg .ColorspaceStroking .ColorToRGB (_fd .Color );if _dbb !=nil {return _dbb ;};_ebe :=_eb .(*_ge .PdfColorDeviceRGB );_dd :=_ebe .ToGray ();_edca .Params =append (_edca .Params ,_ga .MakeFloat (_dd .Val ()));};if _ ,_afc :=_gfe [_fd .PatternName ];
_afc {_edca .Params =append (_edca .Params ,_ga .MakeName (string (_fd .PatternName )));*_bf =append (*_bf ,&_edca );return nil ;};_gfe [_fd .PatternName ]=true ;_cdd ,_acf :=_dgg .GetPatternByName (_fd .PatternName );if !_acf {return _g .New ("\u0075\u006e\u0064\u0065fi\u006e\u0065\u0064\u0020\u0070\u0061\u0074\u0074\u0065\u0072\u006e\u0020\u006e\u0061m\u0065");
};_caf ,_dac :=_bcg (_cdd );if _dac !=nil {return _dac ;};_dac =_dgg .SetPatternByName (_fd .PatternName ,_caf .ToPdfObject ());if _dac !=nil {return _dac ;};_edca .Params =append (_edca .Params ,_ga .MakeName (string (_fd .PatternName )));*_bf =append (*_bf ,&_edca );
}else {_ab ,_cae :=_dg .ColorspaceStroking .ColorToRGB (_dg .ColorStroking );if _cae !=nil {return _cae ;};_deb :=_ab .(*_ge .PdfColorDeviceRGB );_ceb :=_deb .ToGray ();_def :=_gf .ContentStreamOperation {};_def .Operand =_gb ;_def .Params =[]_ga .PdfObject {_ga .MakeFloat (_ceb .Val ())};
*_bf =append (*_bf ,&_def );};return nil ;case "\u0073\u0063","\u0073\u0063\u006e":if _fc (_dg .ColorspaceNonStroking ){_bfg :=_gf .ContentStreamOperation {};_bfg .Operand =_gb ;_bfg .Params =[]_ga .PdfObject {};_ece ,_faa :=_dg .ColorNonStroking .(*_ge .PdfColorPattern );
if !_faa {return _g .New ("i\u006e\u0076\u0061\u006c\u0069\u0064 \u0073\u0074\u0072\u006f\u006b\u0069\u006e\u0067\u0020c\u006f\u006c\u006fr\u0020t\u0079\u0070\u0065");};if _ece .Color !=nil {_cde ,_gea :=_dg .ColorspaceNonStroking .ColorToRGB (_ece .Color );
if _gea !=nil {return _gea ;};_dgd :=_cde .(*_ge .PdfColorDeviceRGB );_fga :=_dgd .ToGray ();_bfg .Params =append (_bfg .Params ,_ga .MakeFloat (_fga .Val ()));};if _ ,_afa :=_gfe [_ece .PatternName ];_afa {_bfg .Params =append (_bfg .Params ,_ga .MakeName (string (_ece .PatternName )));
*_bf =append (*_bf ,&_bfg );return nil ;};_gfe [_ece .PatternName ]=true ;_cbg ,_ba :=_dgg .GetPatternByName (_ece .PatternName );if !_ba {return _g .New ("\u0075\u006e\u0064\u0065fi\u006e\u0065\u0064\u0020\u0070\u0061\u0074\u0074\u0065\u0072\u006e\u0020\u006e\u0061m\u0065");
};_eade ,_efg :=_bcg (_cbg );if _efg !=nil {return _efg ;};_efg =_dgg .SetPatternByName (_ece .PatternName ,_eade .ToPdfObject ());if _efg !=nil {return _efg ;};_bfg .Params =append (_bfg .Params ,_ga .MakeName (string (_ece .PatternName )));*_bf =append (*_bf ,&_bfg );
}else {_egb ,_ad :=_dg .ColorspaceNonStroking .ColorToRGB (_dg .ColorNonStroking );if _ad !=nil {return _ad ;};_bac :=_egb .(*_ge .PdfColorDeviceRGB );_fec :=_bac .ToGray ();_cg :=_gf .ContentStreamOperation {};_cg .Operand =_gb ;_cg .Params =[]_ga .PdfObject {_ga .MakeFloat (_fec .Val ())};
*_bf =append (*_bf ,&_cg );};return nil ;case "\u0052\u0047","\u004b":_gc ,_eef :=_dg .ColorspaceStroking .ColorToRGB (_dg .ColorStroking );if _eef !=nil {return _eef ;};_dc :=_gc .(*_ge .PdfColorDeviceRGB );_dgda :=_dc .ToGray ();_gce :=_gf .ContentStreamOperation {};
_gce .Operand ="\u0047";_gce .Params =[]_ga .PdfObject {_ga .MakeFloat (_dgda .Val ())};*_bf =append (*_bf ,&_gce );return nil ;case "\u0072\u0067","\u006b":_dacb ,_ace :=_dg .ColorspaceNonStroking .ColorToRGB (_dg .ColorNonStroking );if _ace !=nil {return _ace ;
};_aa :=_dacb .(*_ge .PdfColorDeviceRGB );_cf :=_aa .ToGray ();_gab :=_gf .ContentStreamOperation {};_gab .Operand ="\u0067";_gab .Params =[]_ga .PdfObject {_ga .MakeFloat (_cf .Val ())};*_bf =append (*_bf ,&_gab );return nil ;case "\u0073\u0068":if len (_ca .Params )!=1{return _g .New ("\u0070\u0061\u0072\u0061\u006d\u0073 \u0074\u006f\u0020\u0073\u0068\u0020\u006f\u0070\u0065\u0072\u0061\u0074\u006fr\u0020\u0073\u0068\u006f\u0075\u006c\u0064 \u0062\u0065\u0020\u0031");
};_ecb ,_bed :=_ca .Params [0].(*_ga .PdfObjectName );if !_bed {return _g .New ("\u0073\u0068 \u0070\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072\u0020\u0073\u0068\u006f\u0075\u006c\u0064\u0020\u0062\u0065\u0020\u0061\u0020na\u006d\u0065");};if _ ,_dbf :=_bb [*_ecb ];
_dbf {*_bf =append (*_bf ,_ca );return nil ;};_bb [*_ecb ]=true ;_aeg ,_fcf :=_dgg .GetShadingByName (*_ecb );if !_fcf {return _g .New ("\u0073\u0068\u0061\u0064\u0069\u006e\u0067\u0020\u006e\u006f\u0074\u0020\u0064\u0065\u0066i\u006ee\u0064\u0020\u0069\u006e\u0020\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065\u0073");
};_afeg ,_eefd :=_age (_aeg );if _eefd !=nil {return _eefd ;};_eefd =_dgg .SetShadingByName (*_ecb ,_afeg .GetContext ().ToPdfObject ());if _eefd !=nil {return _eefd ;};};*_bf =append (*_bf ,_ca );return nil ;});_fbc .AddHandler (_gf .HandlerConditionEnumOperand ,"\u0042\u0049",func (_dcf *_gf .ContentStreamOperation ,_edd _gf .GraphicsState ,_gac *_ge .PdfPageResources )error {if len (_dcf .Params )!=1{return _g .New ("\u0069\u006e\u0076\u0061l\u0069\u0064\u0020\u006e\u0075\u006d\u0062\u0065\u0072\u0020o\u0066 \u0070\u0061\u0072\u0061\u006d\u0065\u0074e\u0072\u0073");
};_fbf ,_dba :=_dcf .Params [0].(*_gf .ContentStreamInlineImage );if !_dba {return _g .New ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0069\u006el\u0069\u006e\u0065\u0020\u0069\u006d\u0061g\u0065\u0020\u0070\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072");
};_cc ,_bfga :=_fbf .ToImage (_gac );if _bfga !=nil {return _bfga ;};_gae ,_bfga :=_fbf .GetColorSpace (_gac );if _bfga !=nil {return _bfga ;};_bc ,_bfga :=_gae .ImageToRGB (*_cc );if _bfga !=nil {return _bfga ;};_dgf :=_ge .NewPdfColorspaceDeviceRGB ();
_ccd ,_bfga :=_dgf .ImageToGray (_bc );if _bfga !=nil {return _bfga ;};_abd ,_bfga :=_fbf .GetEncoder ();if _bfga !=nil {return _bfga ;};if _dcfg ,_edf :=_abd .(*_ga .DCTEncoder );_edf {_dcfg .ColorComponents =1;};_fbg ,_bfga :=_gf .NewInlineImageFromImage (_ccd ,_abd );
if _bfga !=nil {if _bfga ==_ga .ErrUnsupportedEncodingParameters {_abd =_ga .NewFlateEncoder ();};_fbg ,_bfga =_gf .NewInlineImageFromImage (_ccd ,_abd );if _bfga !=nil {return _bfga ;};};_bff :=_gf .ContentStreamOperation {};_bff .Operand ="\u0042\u0049";
_bff .Params =[]_ga .PdfObject {_fbg };*_bf =append (*_bf ,&_bff );return nil ;});_gabc :=map[string ]bool {};_fbc .AddHandler (_gf .HandlerConditionEnumOperand ,"\u0044\u006f",func (_egf *_gf .ContentStreamOperation ,_ede _gf .GraphicsState ,_bg *_ge .PdfPageResources )error {if len (_egf .Params )< 1{return _g .New ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0049\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u006e\u0075\u006d\u0062\u0065r\u0020\u006f\u0066\u0020\u0070\u0061\u0072\u0061\u006ds\u0020\u0066\u006f\u0072\u0020\u0044\u006f\u0020\u006f\u0062\u006a\u0065\u0063t\u003a\u0020\u0052\u0061\u006e\u0067e\u0020\u0063\u0068e\u0063\u006b");
};_eba :=_egf .Params [0].(*_ga .PdfObjectName );_ ,_abe :=_gabc [string (*_eba )];if _abe {return nil ;};_gabc [string (*_eba )]=true ;_ ,_afb :=_bg .GetXObjectByName (*_eba );if _afb ==_ge .XObjectTypeImage {_daf ,_gg :=_bg .GetXObjectImageByName (*_eba );
if _gg !=nil {return _gg ;};_ada ,_gg :=_daf .ToImage ();if _gg !=nil {return _gg ;};_cec ,_gg :=_daf .ColorSpace .ImageToRGB (*_ada );if _gg !=nil {return _gg ;};_fea :=_ge .NewPdfColorspaceDeviceRGB ();_eee ,_gg :=_fea .ImageToGray (_cec );if _gg !=nil {return _gg ;
};_fdg :=_daf .Filter ;if _cfb ,_gag :=_fdg .(*_ga .DCTEncoder );_gag {_cfb .ColorComponents =1;};_dgb ,_gg :=_ge .NewXObjectImageFromImage (&_eee ,nil ,_fdg );if _gg !=nil {if _gg ==_ga .ErrUnsupportedEncodingParameters {_fdg =_ga .NewFlateEncoder ();
};_dgb ,_gg =_ge .NewXObjectImageFromImage (&_eee ,nil ,_fdg );if _gg !=nil {return _gg ;};};_gg =_bg .SetXObjectImageByName (*_eba ,_dgb );if _gg !=nil {return _gg ;};}else if _afb ==_ge .XObjectTypeForm {_cebf ,_aba :=_bg .GetXObjectFormByName (*_eba );
if _aba !=nil {return _aba ;};_ecf ,_aba :=_cebf .GetContentStream ();if _aba !=nil {return _aba ;};_cfbc :=_cebf .Resources ;if _cfbc ==nil {_cfbc =_bg ;};_gcc ,_aba :=_fef (string (_ecf ),_cfbc );if _aba !=nil {return _aba ;};_aba =_cebf .SetContentStream (_gcc ,nil );
if _aba !=nil {return _aba ;};_aba =_bg .SetXObjectFormByName (*_eba ,_cebf );if _aba !=nil {return _aba ;};};return nil ;});_ac =_fbc .Process (_edc );if _ac !=nil {return nil ,_ac ;};return _bf .Bytes (),nil ;};func _age (_bfc *_ge .PdfShading )(*_ge .PdfShading ,error ){_agb :=_bfc .ColorSpace ;
if _agb .GetNumComponents ()==1{return _bfc ,nil ;}else if _agb .GetNumComponents ()==3{_dgc :=&_ge .PdfFunctionType4 {};_dgc .Domain =[]float64 {0,1,0,1,0,1};_dgc .Range =[]float64 {0,1};_abdg :=_da .NewPSProgram ();_abdg .Append (_da .MakeReal (0.11));
_abdg .Append (_da .MakeOperand ("\u006d\u0075\u006c"));_abdg .Append (_da .MakeOperand ("\u0065\u0078\u0063\u0068"));_abdg .Append (_da .MakeReal (0.59));_abdg .Append (_da .MakeOperand ("\u006d\u0075\u006c"));_abdg .Append (_da .MakeOperand ("\u0061\u0064\u0064"));
_abdg .Append (_da .MakeOperand ("\u0065\u0078\u0063\u0068"));_abdg .Append (_da .MakeReal (0.3));_abdg .Append (_da .MakeOperand ("\u006d\u0075\u006c"));_abdg .Append (_da .MakeOperand ("\u0061\u0064\u0064"));_dgc .Program =_abdg ;_cdg :=_ge .NewPdfColorspaceDeviceN ();
_cdg .AlternateSpace =_ge .NewPdfColorspaceDeviceGray ();_cdg .ColorantNames =_ga .MakeArray (_ga .MakeName ("\u0052"),_ga .MakeName ("\u0047"),_ga .MakeName ("\u0042"));_cdg .TintTransform =_dgc ;_bfc .ColorSpace =_cdg ;return _bfc ,nil ;}else if _agb .GetNumComponents ()==4{_acee :=&_ge .PdfFunctionType4 {};
_acee .Domain =[]float64 {0,1,0,1,0,1,0,1};_acee .Range =[]float64 {0,1};_bgd :=_da .NewPSProgram ();_bgd .Append (_da .MakeOperand ("\u0065\u0078\u0063\u0068"));_bgd .Append (_da .MakeReal (0.11));_bgd .Append (_da .MakeOperand ("\u006d\u0075\u006c"));
_bgd .Append (_da .MakeOperand ("\u0061\u0064\u0064"));_bgd .Append (_da .MakeOperand ("\u0065\u0078\u0063\u0068"));_bgd .Append (_da .MakeReal (0.59));_bgd .Append (_da .MakeOperand ("\u006d\u0075\u006c"));_bgd .Append (_da .MakeOperand ("\u0061\u0064\u0064"));
_bgd .Append (_da .MakeOperand ("\u0065\u0078\u0063\u0068"));_bgd .Append (_da .MakeReal (0.30));_bgd .Append (_da .MakeOperand ("\u006d\u0075\u006c"));_bgd .Append (_da .MakeOperand ("\u0061\u0064\u0064"));_bgd .Append (_da .MakeOperand ("\u0064\u0075\u0070"));
_bgd .Append (_da .MakeReal (1.0));_bgd .Append (_da .MakeOperand ("\u0067\u0065"));_faf :=_da .NewPSProgram ();_faf .Append (_da .MakeOperand ("\u0070\u006f\u0070"));_faf .Append (_da .MakeReal (1.0));_bgd .Append (_faf );_bgd .Append (_da .MakeOperand ("\u0069\u0066"));
_acee .Program =_bgd ;_bab :=_ge .NewPdfColorspaceDeviceN ();_bab .AlternateSpace =_ge .NewPdfColorspaceDeviceGray ();_bab .ColorantNames =_ga .MakeArray (_ga .MakeName ("\u0043"),_ga .MakeName ("\u004d"),_ga .MakeName ("\u0059"),_ga .MakeName ("\u004b"));
_bab .TintTransform =_acee ;_bfc .ColorSpace =_bab ;return _bfc ,nil ;}else {return nil ,_g .New ("\u0075\u006e\u0073\u0075\u0070\u0070\u006fr\u0074\u0065\u0064 \u0070\u0061\u0074t\u0065\u0072n\u0020\u0063\u006f\u006c\u006f\u0072s\u0070ac\u0065\u0020\u0066\u006f\u0072\u0020\u0067\u0072\u0061\u0079\u0073\u0063\u0061\u006c\u0065\u0020\u0063\u006f\u006e\u0076\u0065\u0072\u0073\u0069\u006f\u006e");
};};

// MergePdfStreamsWithOptions merges several PDF streams and writes the result to output,
// applying the supplied options. See MergePdfOptions for available knobs.
func MergePdfStreamsWithOptions (inputs []_a .ReadSeeker ,output _a .Writer ,opts MergePdfOptions )error {if len (inputs )==0{return _f .Errorf ("\u006e\u006f\u0020\u0069np\u0075\u0074\u0020\u0050\u0044\u0046\u0073\u0020\u0070\u0072\u006f\u0076\u0069\u0064e\u0064");
};_baf :=_ge .NewPdfWriter ();if opts .Optimizer !=nil {_baf .SetOptimizer (opts .Optimizer );};var _egbf *_ge .PdfAcroForm ;for _fae ,_geg :=range inputs {_aac ,_babe :=_ge .NewPdfReaderWithOpts (_geg ,nil );if _babe !=nil {return _babe ;};_feg ,_babe :=_aac .GetNumPages ();
if _babe !=nil {return _babe ;};for _gcec :=range _feg {_cee :=_gcec +1;_aecg ,_ff :=_aac .GetPage (_cee );if _ff !=nil {return _ff ;};_ff =_baf .AddPage (_aecg );if _ff !=nil {return _ff ;};};if opts .IsMergingForms &&_aac .AcroForm !=nil {if _egbf ==nil {_egbf =_aac .AcroForm ;
}else {_egbf ,_babe =_ceac (_egbf ,_aac .AcroForm ,_fae +1);if _babe !=nil {return _babe ;};};};};if _egbf !=nil {_baf .SetForms (_egbf );};return _baf .Write (output );};func _bcg (_afd *_ge .PdfPattern )(*_ge .PdfPattern ,error ){if _afd .IsTiling (){_ecff :=_afd .GetAsTilingPattern ();
if _ecff .IsColored (){_eefb ,_gagc :=_ecff .GetContentStream ();if _gagc !=nil {return nil ,_gagc ;};_aec ,_gagc :=_fef (string (_eefb ),_ecff .Resources );if _gagc !=nil {return nil ,_gagc ;};_gagc =_ecff .SetContentStream (_aec ,nil );if _gagc !=nil {return nil ,_gagc ;
};_ =_ecff .ToPdfObject ();};}else if _afd .IsShading (){_gcb :=_afd .GetAsShadingPattern ();_ecbb ,_abb :=_age (_gcb .Shading );if _abb !=nil {return nil ,_abb ;};_gcb .Shading =_ecbb ;_ =_gcb .ToPdfObject ();};return _afd ,nil ;};

// ConvertPageToGrayscale() replaces color objects on the page with grayscale ones.  Also references XObject Images and Forms
// to convert those to grayscale.
func ConvertPageToGrayscale (page *_ge .PdfPage )error {_db ,_dad :=page .GetAllContentStreams ();if _dad !=nil {return _dad ;};_cb ,_dad :=_fef (_db ,page .Resources );if _dad !=nil {return _dad ;};_dad =page .SetContentStreams ([]string {string (_cb )},_ga .NewFlateEncoder ());
if _dad !=nil {return _dad ;};return nil ;};

// MergePdfWithFilePermissionAndOptions merges several PDF files passed as inputPaths to one PDF file,
// outputPath, applying the supplied options and writing the result with the given file permission.
// See MergePdfOptions for available knobs.
func MergePdfWithFilePermissionAndOptions (inputPaths []string ,outputPath string ,opts MergePdfOptions ,perm _b .FileMode )error {_faaa :=make ([]_a .ReadSeeker ,0,len (inputPaths ));for _ ,_cgg :=range inputPaths {_eff ,_cce :=_b .Open (_cgg );if _cce !=nil {return _cce ;
};defer _eff .Close ();_faaa =append (_faaa ,_eff );};var _fdd _ag .Buffer ;if _ebd :=MergePdfStreamsWithOptions (_faaa ,&_fdd ,opts );_ebd !=nil {return _ebd ;};return _b .WriteFile (outputPath ,_fdd .Bytes (),perm );};

// MergePdfOptions configures behaviour of the merge operation.
type MergePdfOptions struct{

// IsMergingForms controls whether AcroForms from input documents are merged.
IsMergingForms bool ;

// Optimizer is applied to the merged document on write. When nil (default),
// the merged output is written without optimization. To deduplicate streams
// shared across input documents (e.g. embedded font programs, image
// XObjects, ToUnicode CMaps), pass
// optimize.New(optimize.Options{CombineDuplicateStreams: true}).
Optimizer _ge .Optimizer ;};func _bbe (_egbfa ,_cggb *_ge .PdfPageResources )(*_ge .PdfPageResources ,error ){if _egbfa .XObject ==nil {_egbfa .XObject =_cggb .XObject ;}else {_dcfe ,_ :=_ga .GetDict (_egbfa .XObject );if _cggb .XObject !=nil {_dca ,_ :=_ga .GetDict (_cggb .XObject );
for _ ,_efc :=range _dca .Keys (){_cgc :=_dca .Get (_efc );_dcfe .Set (_efc ,_cgc );};};};_fbe ,_faca :=_egbfa .GetColorspaces ();if _faca !=nil {return nil ,_faca ;};_eaf ,_faca :=_cggb .GetColorspaces ();if _faca !=nil {return nil ,_faca ;};if _fbe ==nil {_egbfa .SetColorSpace (_eaf );
}else {if _eaf !=nil {for _cbd ,_gcg :=range _eaf .Colorspaces {if _ ,_gfg :=_fbe .Colorspaces [_cbd ];!_gfg {_fbe .Names =append (_fbe .Names ,_cbd );};_egbfa .SetColorspaceByName (_ga .PdfObjectName (_cbd ),_gcg );};};};if _egbfa .ExtGState ==nil {_egbfa .ExtGState =_cggb .ExtGState ;
}else {_dcg ,_ :=_ga .GetDict (_egbfa .ExtGState );if _cggb .ExtGState !=nil {_gaga ,_ :=_ga .GetDict (_cggb .ExtGState );for _ ,_dbgb :=range _gaga .Keys (){_gcf :=_gaga .Get (_dbgb );_dcg .Set (_dbgb ,_gcf );};};};if _egbfa .Shading ==nil {_egbfa .Shading =_cggb .Shading ;
}else {_fbb ,_ :=_ga .GetDict (_egbfa .Shading );if _cggb .Shading !=nil {_dbae ,_ :=_ga .GetDict (_cggb .Shading );for _ ,_ffe :=range _dbae .Keys (){_ggc :=_dbae .Get (_ffe );_fbb .Set (_ffe ,_ggc );};};};if _egbfa .Pattern ==nil {_egbfa .Pattern =_cggb .Pattern ;
}else {_bdc ,_ :=_ga .GetDict (_egbfa .Pattern );if _cggb .Pattern !=nil {_agea ,_ :=_ga .GetDict (_cggb .Pattern );for _ ,_bbg :=range _agea .Keys (){_baa :=_agea .Get (_bbg );_bdc .Set (_bbg ,_baa );};};};if _egbfa .Font ==nil {_egbfa .Font =_cggb .Font ;
}else {_dce ,_ :=_ga .GetDict (_egbfa .Font );if _cggb .Font !=nil {_dcb ,_ :=_ga .GetDict (_cggb .Font );for _ ,_gee :=range _dcb .Keys (){_adc :=_dcb .Get (_gee );_dce .Set (_gee ,_adc );};};};if _egbfa .ProcSet ==nil {_egbfa .ProcSet =_cggb .ProcSet ;
}else {_afca ,_ :=_ga .GetDict (_egbfa .ProcSet );if _cggb .ProcSet !=nil {_fbgf ,_ :=_ga .GetDict (_cggb .ProcSet );for _ ,_fgf :=range _fbgf .Keys (){_deg :=_fbgf .Get (_fgf );_afca .Set (_fgf ,_deg );};};};if _egbfa .Properties ==nil {_egbfa .Properties =_cggb .Properties ;
}else {_efad ,_ :=_ga .GetDict (_egbfa .Properties );if _cggb .Properties !=nil {_fff ,_ :=_ga .GetDict (_cggb .Properties );for _ ,_dbff :=range _fff .Keys (){_facf :=_fff .Get (_dbff );_efad .Set (_dbff ,_facf );};};};return _egbfa ,nil ;};

// MergePdfWithOptions merges several PDF files passed as inputPaths to one PDF file, outputPath,
// applying the supplied options. See MergePdfOptions for available knobs.
func MergePdfWithOptions (inputPaths []string ,outputPath string ,opts MergePdfOptions )error {return MergePdfWithFilePermissionAndOptions (inputPaths ,outputPath ,opts ,_b .FileMode (0644));};func _ceac (_edcg ,_gff *_ge .PdfAcroForm ,_ccg int )(*_ge .PdfAcroForm ,error ){if _edcg .NeedAppearances ==nil {_edcg .NeedAppearances =_gff .NeedAppearances ;
};if _edcg .SigFlags ==nil {_edcg .SigFlags =_gff .SigFlags ;};if _edcg .CO ==nil {_edcg .CO =_gff .CO ;};if _edcg .DR ==nil {_edcg .DR =_gff .DR ;}else if _gff .DR !=nil {_dbc ,_bda :=_bbe (_edcg .DR ,_gff .DR );if _bda !=nil {return nil ,_bda ;};_edcg .DR =_dbc ;
};if _edcg .DA ==nil {_edcg .DA =_gff .DA ;};if _edcg .Q ==nil {_edcg .Q =_gff .Q ;};if _edcg .XFA ==nil {_edcg .XFA =_gff .XFA ;}else {if _gff .XFA !=nil {_e .Log .Debug ("TO\u0044\u004f\u003a\u0020\u0048\u0061\u006edl\u0065\u0020\u0058\u0046\u0041\u0020\u006d\u0065\u0072\u0067\u0069\u006e\u0067\u0020\u002d \u0043\u0075\u0072\u0072\u0065\u006e\u0074\u006c\u0079\u0020\u006a\u0075\u0073\u0074\u0020\u0075\u0073\u0069\u006e\u0067 \u0066\u0069\u0072\u0073\u0074\u0020o\u006e\u0065\u0020\u0074\u0068\u0061\u0074\u0020\u0069s\u0020e\u006e\u0063\u006f\u0075\u006e\u0074\u0065\u0072\u0065\u0064");
};};if _edcg .Fields ==nil {_edcg .Fields =_gff .Fields ;}else {_ccc :=_ge .NewPdfField ();_ccc .T =_ga .MakeString (_f .Sprintf ("\u0064\u006f\u0063%\u0064",_ccg ));_ccc .Kids =[]*_ge .PdfField {};if _gff .Fields !=nil {for _ ,_gceg :=range *_gff .Fields {_gceg .Parent =_ccc ;
_ccc .Kids =append (_ccc .Kids ,_gceg );};};*_edcg .Fields =append (*_edcg .Fields ,_ccc );};return _edcg ,nil ;};func _fc (_ec _ge .PdfColorspace )bool {_ ,_cbe :=_ec .(*_ge .PdfColorspaceSpecialPattern );return _cbe };

// ExtractPageRange extracts a range of pages from inputPath PDF file and saves it as outputPath PDF file.
// keepOptionalContent controls if we need to process OC properties (rarely needed).
func ExtractPageRange (inputPath string ,outputPath string ,pageFrom int ,pageTo int ,keepOptionalContent bool )error {_ae :=_ge .NewPdfWriter ();_fe ,_eg ,_c :=_ge .NewPdfReaderFromFile (inputPath ,nil );if _c !=nil {return _c ;};defer _eg .Close ();_ged ,_c :=_fe .GetNumPages ();
if _c !=nil {return _c ;};if _ged < pageTo {return _f .Errorf ("n\u0075\u006d\u0050\u0061\u0067\u0065s\u0020\u0028\u0025\u0064\u0029\u0020\u003c\u0020\u0070a\u0067\u0065\u0054o\u0020(\u0025\u0064\u0029",_ged ,pageTo );};if keepOptionalContent {_gd ,_cd :=_fe .GetOCProperties ();
if _cd !=nil {return _cd ;};_ae .SetOCProperties (_gd );};for _aeb :=pageFrom ;_aeb <=pageTo ;_aeb ++{_fb :=_aeb ;_ed ,_fa :=_fe .GetPage (_fb );if _fa !=nil {return _fa ;};_fa =_ae .AddPage (_ed );if _fa !=nil {return _fa ;};};_ea ,_c :=_b .Create (outputPath );
if _c !=nil {return _c ;};defer _ea .Close ();_c =_ae .Write (_ea );if _c !=nil {return _c ;};return nil ;};

// NormalizePage performs the following operations on the passed in page:
//   - Normalize the page rotation.
//     Rotates the contents of the page according to the Rotate entry, thus
//     flattening the rotation. The Rotate entry of the page is set to nil.
//   - Normalize the media box.
//     If the media box of the page is offsetted (Llx != 0 or Lly != 0),
//     the contents of the page are translated to (-Llx, -Lly). After
//     normalization, the media box is updated (Llx and Lly are set to 0 and
//     Urx and Ury are updated accordingly).
//   - Normalize the crop box.
//     The crop box of the page is updated based on the previous operations.
//
// After normalization, the page should look the same if openend using a
// PDF viewer.
// NOTE: This function does not normalize annotations, outlines other parts
// that are not part of the basic geometry and page content streams.
func NormalizePage (page *_ge .PdfPage )error {_aed ,_ebf :=page .GetMediaBox ();if _ebf !=nil {return _ebf ;};_eadb ,_ebf :=page .GetRotate ();if _ebf !=nil {_e .Log .Debug ("\u0045\u0052R\u004f\u0052\u003a\u0020\u0025\u0073\u0020\u002d\u0020\u0069\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0061\u006e\u0064\u0020\u0061\u0073\u0073\u0075\u006d\u0069\u006e\u0067\u0020\u006e\u006f\u0020\u0072\u006f\u0074\u0061\u0074\u0069\u006f\u006e\u000a",_ebf .Error ());
};_cbga :=_eadb %360!=0&&_eadb %90==0;_aed .Normalize ();_fegc ,_bgb ,_eaed ,_dfg :=_aed .Llx ,_aed .Lly ,_aed .Width (),_aed .Height ();_dgbb :=_fegc !=0||_bgb !=0;if !_cbga &&!_dgbb {return nil ;};_egfg :=func (_ebac ,_cbgd ,_fgg float64 )_bd .BoundingBox {return _bd .Path {Points :[]_bd .Point {_bd .NewPoint (0,0).Rotate (_fgg ),_bd .NewPoint (_ebac ,0).Rotate (_fgg ),_bd .NewPoint (0,_cbgd ).Rotate (_fgg ),_bd .NewPoint (_ebac ,_cbgd ).Rotate (_fgg )}}.GetBoundingBox ();
};_fab :=_gf .NewContentCreator ();var _egg float64 ;if _cbga {_egg =-float64 (_eadb );_cbgag :=_egfg (_eaed ,_dfg ,_egg );_fab .Translate ((_cbgag .Width -_eaed )/2+_eaed /2,(_cbgag .Height -_dfg )/2+_dfg /2);_fab .RotateDeg (_egg );_fab .Translate (-_eaed /2,-_dfg /2);
_eaed ,_dfg =_cbgag .Width ,_cbgag .Height ;};if _dgbb {_fab .Translate (-_fegc ,-_bgb );};_facb :=_fab .Operations ();_bgda ,_ebf :=_ga .MakeStream (_facb .Bytes (),_ga .NewFlateEncoder ());if _ebf !=nil {return _ebf ;};_bcd :=_ga .MakeArray (_bgda );
_bcd .Append (page .GetContentStreamObjs ()...);*_aed =_ge .PdfRectangle {Urx :_eaed ,Ury :_dfg };if _bde :=page .CropBox ;_bde !=nil {_bde .Normalize ();_aag ,_gcce ,_eagc ,_gcef :=_bde .Llx -_fegc ,_bde .Lly -_bgb ,_bde .Width (),_bde .Height ();if _cbga {_facc :=_egfg (_eagc ,_gcef ,_egg );
_eagc ,_gcef =_facc .Width ,_facc .Height ;};*_bde =_ge .PdfRectangle {Llx :_aag ,Lly :_gcce ,Urx :_aag +_eagc ,Ury :_gcce +_gcef };};_e .Log .Debug ("\u0052\u006f\u0074\u0061\u0074\u0065\u003d\u0025\u0066\u00b0\u0020\u004f\u0070\u0073\u003d%\u0071 \u004d\u0065\u0064\u0069\u0061\u0042\u006f\u0078\u003d\u0025\u002e\u0032\u0066",_egg ,_facb ,_aed );
page .Contents =_bcd ;page .Rotate =nil ;return nil ;};

// MergePdfWithFilePermission merges several PDF files passed as inputPaths to one PDF file, outputPath.
// isMergingForms controls if it is necessary to merge AcroForms from input files.
// If you are not sure, you can always set isMergingForms to true.
// perm sets the file permission for the output file.
func MergePdfWithFilePermission (inputPaths []string ,outputPath string ,isMergingForms bool ,perm _b .FileMode )error {return MergePdfWithFilePermissionAndOptions (inputPaths ,outputPath ,MergePdfOptions {IsMergingForms :isMergingForms },perm );};