//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package optimize ;import (_db "bytes";_e "crypto/md5";_g "crypto/sha256";_cd "errors";_fa "fmt";_f "github.com/unidoc/unipdf/v4/common";_ga "github.com/unidoc/unipdf/v4/contentstream";_bd "github.com/unidoc/unipdf/v4/core";_gg "github.com/unidoc/unipdf/v4/extractor";
_de "github.com/unidoc/unipdf/v4/internal/imageutil";_bg "github.com/unidoc/unipdf/v4/internal/textencoding";_df "github.com/unidoc/unipdf/v4/model";_bb "github.com/unidoc/unitype";_d "golang.org/x/image/draw";_b "math";_bf "strings";);

// Append appends optimizers to the chain.
func (_cc *Chain )Append (optimizers ..._df .Optimizer ){_cc ._ca =append (_cc ._ca ,optimizers ...)};func _bef (_bdc *_bd .PdfObjectStream ,_deb []rune ,_bdfa []_bb .GlyphIndex )error {_bdc ,_aad :=_bd .GetStream (_bdc );if !_aad {_f .Log .Debug ("\u0045\u006d\u0062\u0065\u0064\u0064\u0065\u0064\u0020\u0066\u006f\u006e\u0074\u0020\u006f\u0062\u006a\u0065c\u0074\u0020\u006e\u006f\u0074\u0020\u0066o\u0075\u006e\u0064\u0020\u002d\u002d\u0020\u0041\u0042\u004f\u0052T\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006e\u0067");
return _cd .New ("\u0066\u006f\u006e\u0074fi\u006c\u0065\u0032\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064");};_fac ,_fgeg :=_bd .DecodeStream (_bdc );if _fgeg !=nil {_f .Log .Debug ("\u0044\u0065c\u006f\u0064\u0065 \u0065\u0072\u0072\u006f\u0072\u003a\u0020\u0025\u0076",_fgeg );
return _fgeg ;};_fed ,_fgeg :=_bb .Parse (_db .NewReader (_fac ));if _fgeg !=nil {_f .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0070\u0061\u0072\u0073\u0069n\u0067\u0020\u0025\u0064\u0020\u0062\u0079\u0074\u0065\u0020f\u006f\u006e\u0074",len (_bdc .Stream ));
return _fgeg ;};_cfc :=_bdfa ;if len (_deb )> 0{_bdb :=_fed .LookupRunes (_deb );_cfc =append (_cfc ,_bdb ...);};_fed ,_fgeg =_fed .SubsetKeepIndices (_cfc );if _fgeg !=nil {_f .Log .Debug ("\u0045R\u0052\u004f\u0052\u0020s\u0075\u0062\u0073\u0065\u0074t\u0069n\u0067 \u0066\u006f\u006e\u0074\u003a\u0020\u0025v",_fgeg );
return _fgeg ;};var _gfea _db .Buffer ;_fgeg =_fed .Write (&_gfea );if _fgeg !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_fgeg );return _fgeg ;};if _gfea .Len ()> len (_fac ){_f .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
return nil ;};_eee ,_fgeg :=_bd .MakeStream (_gfea .Bytes (),_bd .NewFlateEncoder ());if _fgeg !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_fgeg );return _fgeg ;
};*_bdc =*_eee ;_bdc .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bd .MakeInteger (int64 (_gfea .Len ())));return nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_fbc *ImagePPI )Optimize (objects []_bd .PdfObject )(_ddgd []_bd .PdfObject ,_cfbg error ){if _fbc .ImageUpperPPI <=0{return objects ,nil ;};_bda :=_cefg (objects );if len (_bda )==0{return objects ,nil ;};_debf :=make (map[_bd .PdfObject ]struct{});
for _ ,_bee :=range _bda {_aeed :=_bee .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b");_debf [_aeed ]=struct{}{};};_bfg :=make (map[*_bd .PdfObjectStream ]*imageInfo );for _ ,_fbce :=range _bda {_bfg [_fbce .Stream ]=_fbce ;};var _eeg *_bd .PdfObjectDictionary ;
for _ ,_aac :=range objects {if _aecf ,_deefg :=_bd .GetDict (_aac );_eeg ==nil &&_deefg {if _ffdc ,_eea :=_bd .GetName (_aecf .Get ("\u0054\u0079\u0070\u0065"));_eea &&*_ffdc =="\u0043a\u0074\u0061\u006c\u006f\u0067"{_eeg =_aecf ;};};};if _eeg ==nil {return objects ,nil ;
};_gcge ,_fbdd :=_bd .GetDict (_eeg .Get ("\u0050\u0061\u0067e\u0073"));if !_fbdd {return objects ,nil ;};_adbg ,_ecdc :=_bd .GetArray (_gcge .Get ("\u004b\u0069\u0064\u0073"));if !_ecdc {return objects ,nil ;};for _ ,_bgea :=range _adbg .Elements (){_dgdfb :=make (map[string ]*imageInfo );
_bcdc ,_adg :=_bd .GetDict (_bgea );if !_adg {continue ;};_bcg ,_ :=_aeeda (_bcdc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));if len (_bcg )==0{continue ;};_ecb ,_edgg :=_bd .GetDict (_bcdc .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));
if !_edgg {continue ;};_degg ,_agc :=_df .NewPdfPageResourcesFromDict (_ecb );if _agc !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065\u0073\u0020-\u0020\u0069\u0067\u006e\u006fr\u0069\u006eg\u003a\u0020\u0025\u0076",_agc );
continue ;};_bbfb ,_cfgf :=_bd .GetDict (_ecb .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));if !_cfgf {continue ;};_dde :=_bbfb .Keys ();for _ ,_egdg :=range _dde {if _ceg ,_fbgc :=_bd .GetStream (_bbfb .Get (_egdg ));_fbgc {if _ceea ,_bbgg :=_bfg [_ceg ];
_bbgg {_dgdfb [string (_egdg )]=_ceea ;};};};_ffde :=_ga .NewContentStreamParser (_bcg );_ceba ,_agc :=_ffde .Parse ();if _agc !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_agc );continue ;};_ffg :=_ga .NewContentStreamProcessor (*_ceba );
_ffg .AddHandler (_ga .HandlerConditionEnumAllOperands ,"",func (_fgb *_ga .ContentStreamOperation ,_fedg _ga .GraphicsState ,_gda *_df .PdfPageResources )error {switch _fgb .Operand {case "\u0044\u006f":if len (_fgb .Params )!=1{_f .Log .Debug ("E\u0052\u0052\u004f\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020w\u0069\u0074\u0068\u0020\u006c\u0065\u006e\u0028\u0070\u0061ra\u006d\u0073\u0029 \u0021=\u0020\u0031");
return nil ;};_gedf ,_gdge :=_bd .GetName (_fgb .Params [0]);if !_gdge {_f .Log .Debug ("\u0045\u0052\u0052O\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020\u0077\u0069\u0074\u0068\u0020\u006e\u006f\u006e\u0020\u004e\u0061\u006d\u0065\u0020p\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072");
return nil ;};if _gdecf ,_ffdcg :=_dgdfb [string (*_gedf )];_ffdcg {_bgcg :=_fedg .CTM .ScalingFactorX ();_eacc :=_fedg .CTM .ScalingFactorY ();_dgcd ,_aeeb :=_bgcg /72.0,_eacc /72.0;_bgge ,_aada :=float64 (_gdecf .Width )/_dgcd ,float64 (_gdecf .Height )/_aeeb ;
if _dgcd ==0||_aeeb ==0{_bgge =72.0;_aada =72.0;};_gdecf .PPI =_b .Max (_gdecf .PPI ,_bgge );_gdecf .PPI =_b .Max (_gdecf .PPI ,_aada );};};return nil ;});_agc =_ffg .Process (_degg );if _agc !=nil {_f .Log .Debug ("E\u0052\u0052\u004f\u0052 p\u0072o\u0063\u0065\u0073\u0073\u0069n\u0067\u003a\u0020\u0025\u002b\u0076",_agc );
continue ;};};for _ ,_eec :=range _bda {if _ ,_ccad :=_debf [_eec .Stream ];_ccad {continue ;};if _eec .PPI <=_fbc .ImageUpperPPI {continue ;};_afge ,_egge :=_df .NewXObjectImageFromStream (_eec .Stream );if _egge !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_egge );
continue ;};var _aega imageModifications ;_aega .Scale =_fbc .ImageUpperPPI /_eec .PPI ;if _eec .BitsPerComponent ==1&&_eec .ColorComponents ==1{_dcfg :=_b .Round (_eec .PPI /_fbc .ImageUpperPPI );_gfa :=_de .NextPowerOf2 (uint (_dcfg ));if _de .InDelta (float64 (_gfa ),1/_aega .Scale ,0.3){_aega .Scale =float64 (1)/float64 (_gfa );
};if _ ,_bcf :=_afge .Filter .(*_bd .JBIG2Encoder );!_bcf {_aega .Encoding =_bd .NewJBIG2Encoder ();};};if _egge =_gbgg (_afge ,_aega );_egge !=nil {_f .Log .Debug ("\u0045\u0072\u0072\u006f\u0072 \u0073\u0063\u0061\u006c\u0065\u0020\u0069\u006d\u0061\u0067\u0065\u0020\u006be\u0065\u0070\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0073",_egge );
continue ;};_aega .Encoding =nil ;if _abgd ,_gffe :=_bd .GetStream (_eec .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b"));_gffe {_aga ,_cdeb :=_df .NewXObjectImageFromStream (_abgd );if _cdeb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_cdeb );
continue ;};if _cdeb =_gbgg (_aga ,_aega );_cdeb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_cdeb );continue ;};};};return objects ,nil ;};func _ffed (_dgdc string ,_bfff []string )bool {for _ ,_cced :=range _bfff {if _dgdc ==_cced {return true ;
};};return false ;};

// CleanFonts cleans up embedded fonts, reducing font sizes.
type CleanFonts struct{

// Subset embedded fonts if encountered (if true).
// Otherwise attempts to reduce the font program.
Subset bool ;};

// ObjectStreams groups PDF objects to object streams.
// It implements interface model.Optimizer.
type ObjectStreams struct{};

// Optimize optimizes PDF objects to decrease PDF size.
func (_dbdg *Image )Optimize (objects []_bd .PdfObject )(_fdfb []_bd .PdfObject ,_afg error ){if _dbdg .ImageQuality <=0{return objects ,nil ;};_aeg :=_cefg (objects );if len (_aeg )==0{return objects ,nil ;};_eac :=make (map[_bd .PdfObject ]_bd .PdfObject );
_dbc :=make (map[_bd .PdfObject ]struct{});for _ ,_gada :=range _aeg {_aec :=_gada .Stream .Get ("\u0053\u004d\u0061s\u006b");_dbc [_aec ]=struct{}{};};for _bgd ,_caed :=range _aeg {_gdda :=_caed .Stream ;if _ ,_bdbg :=_dbc [_gdda ];_bdbg {continue ;};
_eefe ,_fggb :=_df .NewXObjectImageFromStream (_gdda );if _fggb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fggb );continue ;};switch _eefe .Filter .(type ){case *_bd .JBIG2Encoder :continue ;case *_bd .CCITTFaxEncoder :continue ;
};_bafg ,_fggb :=_eefe .ToImage ();if _fggb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fggb );continue ;};_dccf :=_bd .NewDCTEncoder ();_dccf .ColorComponents =_bafg .ColorComponents ;_dccf .Quality =_dbdg .ImageQuality ;
_dccf .BitsPerComponent =_caed .BitsPerComponent ;_dccf .Width =_caed .Width ;_dccf .Height =_caed .Height ;_agfa ,_fggb :=_dccf .EncodeBytes (_bafg .Data );if _fggb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fggb );
continue ;};var _eabf _bd .StreamEncoder ;_eabf =_dccf ;{_faag :=_bd .NewFlateEncoder ();_ecdg :=_bd .NewMultiEncoder ();_ecdg .AddEncoder (_faag );_ecdg .AddEncoder (_dccf );_bedeg ,_dgc :=_ecdg .EncodeBytes (_bafg .Data );if _dgc !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_dgc );
continue ;};if len (_bedeg )< len (_agfa ){if _f .Log .IsLogLevel (_f .LogLevelTrace ){_f .Log .Trace ("\u004d\u0075\u006c\u0074\u0069\u0020\u0065\u006e\u0063\u0020\u0069\u006d\u0070\u0072\u006f\u0076\u0065\u0073\u003a\u0020\u0025\u0064\u0020\u0074o\u0020\u0025\u0064\u0020\u0028o\u0072\u0069g\u0020\u0025\u0064\u0029",len (_agfa ),len (_bedeg ),len (_gdda .Stream ));
};_agfa =_bedeg ;_eabf =_ecdg ;};};_gcbd :=len (_gdda .Stream );if _gcbd < len (_agfa ){continue ;};_ddg :=&_bd .PdfObjectStream {Stream :_agfa };_ddg .PdfObjectReference =_gdda .PdfObjectReference ;_ddg .PdfObjectDictionary =_bd .MakeDict ();_ddg .Merge (_gdda .PdfObjectDictionary );
_ddg .Merge (_eabf .MakeStreamDict ());_ddg .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bd .MakeInteger (int64 (len (_agfa ))));_eac [_gdda ]=_ddg ;_aeg [_bgd ].Stream =_ddg ;};_fdfb =make ([]_bd .PdfObject ,len (objects ));copy (_fdfb ,objects );_aeac (_fdfb ,_eac );
return _fdfb ,nil ;};

// Optimize implements Optimizer interface.
func (_bdfd *CleanUnusedResources )Optimize (objects []_bd .PdfObject )(_cec []_bd .PdfObject ,_bgg error ){_ged ,_bgg :=_dgdf (objects );if _bgg !=nil {return nil ,_bgg ;};_cde :=[]_bd .PdfObject {};for _ ,_ded :=range objects {_ ,_dcee :=_ged [_ded ];
if _dcee {continue ;};_cde =append (_cde ,_ded );};return _cde ,nil ;};

// CleanUnusedResources represents an optimizer used to clean unused resources.
type CleanUnusedResources struct{};func _cca (_ea _bd .PdfObject )[]content {if _ea ==nil {return nil ;};_aagf ,_dgd :=_bd .GetArray (_ea );if !_dgd {_f .Log .Debug ("\u0041\u006e\u006e\u006fts\u0020\u006e\u006f\u0074\u0020\u0061\u006e\u0020\u0061\u0072\u0072\u0061\u0079");
return nil ;};var _ggb []content ;for _ ,_fad :=range _aagf .Elements (){_eaa ,_gcd :=_bd .GetDict (_fad );if !_gcd {_f .Log .Debug ("I\u0067\u006e\u006f\u0072\u0069\u006eg\u0020\u006e\u006f\u006e\u002d\u0064i\u0063\u0074\u0020\u0065\u006c\u0065\u006de\u006e\u0074\u0020\u0069\u006e\u0020\u0041\u006e\u006e\u006ft\u0073");
continue ;};_dec ,_gcd :=_bd .GetDict (_eaa .Get ("\u0041\u0050"));if !_gcd {_f .Log .Debug ("\u004e\u006f\u0020\u0041P \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_ced :=_bd .TraceToDirectObject (_dec .Get ("\u004e"));
if _ced ==nil {_f .Log .Debug ("N\u006f\u0020\u004e\u0020en\u0074r\u0079\u0020\u002d\u0020\u0073k\u0069\u0070\u0070\u0069\u006e\u0067");continue ;};var _dce *_bd .PdfObjectStream ;switch _decf :=_ced .(type ){case *_bd .PdfObjectDictionary :_ffd ,_gba :=_bd .GetName (_eaa .Get ("\u0041\u0053"));
if !_gba {_f .Log .Debug ("\u004e\u006f\u0020\u0041S \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_dce ,_gba =_bd .GetStream (_decf .Get (*_ffd ));if !_gba {_f .Log .Debug ("\u0046o\u0072\u006d\u0020\u006eo\u0074\u0020\u0066\u006f\u0075n\u0064 \u002d \u0073\u006b\u0069\u0070\u0070\u0069\u006eg");
continue ;};case *_bd .PdfObjectStream :_dce =_decf ;};if _dce ==nil {_f .Log .Debug ("\u0046\u006f\u0072m\u0020\u006e\u006f\u0074 \u0066\u006f\u0075\u006e\u0064\u0020\u0028n\u0069\u006c\u0029\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067");
continue ;};_gccc ,_bgf :=_df .NewXObjectFormFromStream (_dce );if _bgf !=nil {_f .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020l\u006f\u0061\u0064\u0069\u006e\u0067\u0020\u0066\u006f\u0072\u006d\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_bgf );
continue ;};_dbf ,_bgf :=_gccc .GetContentStream ();if _bgf !=nil {_f .Log .Debug ("E\u0072\u0072\u006f\u0072\u0020\u0064e\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0063\u006fn\u0074\u0065\u006et\u0073:\u0020\u0025\u0076",_bgf );continue ;};_ggb =append (_ggb ,content {_edce :string (_dbf ),_gdb :_gccc .Resources });
};return _ggb ;};

// CombineDuplicateStreams combines duplicated streams by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateStreams struct{};

// CombineDuplicateDirectObjects combines duplicated direct objects by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateDirectObjects struct{};func _bge (_bdd []*_bd .PdfIndirectObject )map[string ][]string {_cfg :=map[string ][]string {};for _ ,_caca :=range _bdd {_efg ,_fde :=_bd .GetDict (_caca .PdfObject );if !_fde {continue ;};_acbc :=_efg .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073");
_gede :=_bd .TraceToDirectObject (_acbc );_dac :="";if _bae ,_eef :=_gede .(*_bd .PdfObjectArray );_eef {var _cgcd []string ;for _ ,_eaab :=range _bae .Elements (){_dcce ,_cfgd :=_cdb (_eaab );if _cfgd !=nil {continue ;};_cgcd =append (_cgcd ,_dcce );};
_dac =_bf .Join (_cgcd ,"\u0020");};if _eeff ,_cdgg :=_gede .(*_bd .PdfObjectStream );_cdgg {_ece ,_fcg :=_bd .DecodeStream (_eeff );if _fcg !=nil {continue ;};_dac =string (_ece );};_afe :=_ga .NewContentStreamParser (_dac );_eae ,_ffb :=_afe .Parse ();
if _ffb !=nil {continue ;};for _ ,_eca :=range *_eae {_egbc :=_eca .Operand ;_dbdc :=_eca .Params ;switch _egbc {case "\u0044\u006f":_aadf :=_dbdc [0].String ();if _ ,_aaa :=_cfg ["\u0058O\u0062\u006a\u0065\u0063\u0074"];!_aaa {_cfg ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=[]string {_aadf };
}else {_cfg ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=append (_cfg ["\u0058O\u0062\u006a\u0065\u0063\u0074"],_aadf );};case "\u0054\u0066":_gca :=_dbdc [0].String ();if _ ,_bddb :=_cfg ["\u0046\u006f\u006e\u0074"];!_bddb {_cfg ["\u0046\u006f\u006e\u0074"]=[]string {_gca };
}else {_cfg ["\u0046\u006f\u006e\u0074"]=append (_cfg ["\u0046\u006f\u006e\u0074"],_gca );};case "\u0067\u0073":_aeae :=_dbdc [0].String ();if _ ,_dgg :=_cfg ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];!_dgg {_cfg ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=[]string {_aeae };
}else {_cfg ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=append (_cfg ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"],_aeae );};};};};return _cfg ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_egac *ObjectStreams )Optimize (objects []_bd .PdfObject )(_aacf []_bd .PdfObject ,_ddc error ){_ccdg :=&_bd .PdfObjectStreams {};_fga :=make ([]_bd .PdfObject ,0,len (objects ));for _ ,_fee :=range objects {if _fcdc ,_cggf :=_fee .(*_bd .PdfIndirectObject );
_cggf &&_fcdc .GenerationNumber ==0{_ccdg .Append (_fee );}else {_fga =append (_fga ,_fee );};};if _ccdg .Len ()==0{return _fga ,nil ;};_aacf =make ([]_bd .PdfObject ,0,len (_fga )+_ccdg .Len ()+1);if _ccdg .Len ()> 1{_aacf =append (_aacf ,_ccdg );};_aacf =append (_aacf ,_ccdg .Elements ()...);
_aacf =append (_aacf ,_fga ...);return _aacf ,nil ;};

// CleanContentstream cleans up redundant operands in content streams, including Page and XObject Form
// contents. This process includes:
// 1. Marked content operators are removed.
// 2. Some operands are simplified (shorter form).
// TODO: Add more reduction methods and improving the methods for identifying unnecessary operands.
type CleanContentstream struct{};func _gdbb (_fbg _bd .PdfObject ,_ccd map[_bd .PdfObject ]struct{})error {if _dee ,_gcb :=_fbg .(*_bd .PdfIndirectObject );_gcb {_ccd [_fbg ]=struct{}{};_aabf :=_gdbb (_dee .PdfObject ,_ccd );if _aabf !=nil {return _aabf ;
};return nil ;};if _dge ,_cef :=_fbg .(*_bd .PdfObjectStream );_cef {_ccd [_dge ]=struct{}{};_afb :=_gdbb (_dge .PdfObjectDictionary ,_ccd );if _afb !=nil {return _afb ;};return nil ;};if _cgbf ,_bgee :=_fbg .(*_bd .PdfObjectDictionary );_bgee {for _ ,_bedg :=range _cgbf .Keys (){_dgf :=_cgbf .Get (_bedg );
_ =_dgf ;if _ega ,_bad :=_dgf .(*_bd .PdfObjectReference );_bad {_dgf =_ega .Resolve ();_cgbf .Set (_bedg ,_dgf );};if _bedg !="\u0050\u0061\u0072\u0065\u006e\u0074"{if _bbf :=_gdbb (_dgf ,_ccd );_bbf !=nil {return _bbf ;};};};return nil ;};if _fbb ,_gcfb :=_fbg .(*_bd .PdfObjectArray );
_gcfb {if _fbb ==nil {return _cd .New ("\u0061\u0072\u0072a\u0079\u0020\u0069\u0073\u0020\u006e\u0069\u006c");};for _ebe ,_fadb :=range _fbb .Elements (){if _ffe ,_eaf :=_fadb .(*_bd .PdfObjectReference );_eaf {_fadb =_ffe .Resolve ();_fbb .Set (_ebe ,_fadb );
};if _face :=_gdbb (_fadb ,_ccd );_face !=nil {return _face ;};};return nil ;};return nil ;};func _cdb (_aaga _bd .PdfObject )(string ,error ){_gag :=_bd .TraceToDirectObject (_aaga );switch _bedb :=_gag .(type ){case *_bd .PdfObjectString :return _bedb .Str (),nil ;
case *_bd .PdfObjectStream :_bff ,_bbbb :=_bd .DecodeStream (_bedb );if _bbbb !=nil {return "",_bbbb ;};return string (_bff ),nil ;};return "",_fa .Errorf ("\u0069\u006e\u0076\u0061\u006ci\u0064\u0020\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0020\u0073\u0074\u0072e\u0061\u006d\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020\u0068\u006f\u006c\u0064\u0065\u0072\u0020\u0028\u0025\u0054\u0029",_gag );
};func _dagf (_gedg []_bd .PdfObject ){for _dgdd ,_gafe :=range _gedg {switch _dda :=_gafe .(type ){case *_bd .PdfIndirectObject :_dda .ObjectNumber =int64 (_dgdd +1);_dda .GenerationNumber =0;case *_bd .PdfObjectStream :_dda .ObjectNumber =int64 (_dgdd +1);
_dda .GenerationNumber =0;case *_bd .PdfObjectStreams :_dda .ObjectNumber =int64 (_dgdd +1);_dda .GenerationNumber =0;};};};

// Optimize optimizes PDF objects to decrease PDF size.
func (_cbf *CombineIdenticalIndirectObjects )Optimize (objects []_bd .PdfObject )(_cefd []_bd .PdfObject ,_cbcb error ){_dagf (objects );_acf :=make (map[_bd .PdfObject ]_bd .PdfObject );_ebdf :=make (map[_bd .PdfObject ]struct{});_abb :=make (map[string ][]*_bd .PdfIndirectObject );
for _ ,_cgga :=range objects {_gaf ,_afee :=_cgga .(*_bd .PdfIndirectObject );if !_afee {continue ;};if _gdf ,_ddf :=_gaf .PdfObject .(*_bd .PdfObjectDictionary );_ddf {if _ebdd ,_fecg :=_gdf .Get ("\u0054\u0079\u0070\u0065").(*_bd .PdfObjectName );_fecg &&*_ebdd =="\u0050\u0061\u0067\u0065"{continue ;
};if _ade :=_gdf .Keys ();len (_ade )==0{continue ;};_faafa :=_e .New ();_faafa .Write (_gdf .Write ());_fege :=string (_faafa .Sum (nil ));_abb [_fege ]=append (_abb [_fege ],_gaf );};};for _ ,_cefc :=range _abb {if len (_cefc )< 2{continue ;};_edg :=_cefc [0];
for _dfee :=1;_dfee < len (_cefc );_dfee ++{_edda :=_cefc [_dfee ];_acf [_edda ]=_edg ;_ebdf [_edda ]=struct{}{};};};_cefd =make ([]_bd .PdfObject ,0,len (objects )-len (_ebdf ));for _ ,_egf :=range objects {if _ ,_ddd :=_ebdf [_egf ];_ddd {continue ;};
_cefd =append (_cefd ,_egf );};_aeac (_cefd ,_acf );return _cefd ,nil ;};

// CompressStreams compresses uncompressed streams.
// It implements interface model.Optimizer.
type CompressStreams struct{};

// ImagePPI optimizes images by scaling images such that the PPI (pixels per inch) is never higher than ImageUpperPPI.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type ImagePPI struct{ImageUpperPPI float64 ;};type content struct{_edce string ;_gdb *_df .PdfPageResources ;};func _cff (_cfac *_bd .PdfObjectDictionary )[]string {_feae :=[]string {};for _ ,_gdg :=range _cfac .Keys (){_feae =append (_feae ,_gdg .String ());
};return _feae ;};func _dfbd (_gcg *_df .Image ,_bggc float64 )(*_df .Image ,error ){_badd ,_bea :=_gcg .ToGoImage ();if _bea !=nil {return nil ,_bea ;};var _gae _de .Image ;_ceed ,_efag :=_badd .(*_de .Monochrome );if _efag {if _bea =_ceed .ResolveDecode ();
_bea !=nil {return nil ,_bea ;};_gae ,_bea =_ceed .Scale (_bggc );if _bea !=nil {return nil ,_bea ;};}else {_fcab :=int (_b .RoundToEven (float64 (_gcg .Width )*_bggc ));_cdbd :=int (_b .RoundToEven (float64 (_gcg .Height )*_bggc ));_gae ,_bea =_de .NewImage (_fcab ,_cdbd ,int (_gcg .BitsPerComponent ),_gcg .ColorComponents ,nil ,nil ,nil );
if _bea !=nil {return nil ,_bea ;};_d .CatmullRom .Scale (_gae ,_gae .Bounds (),_badd ,_badd .Bounds (),_d .Over ,&_d .Options {});};_gcbg :=_gae .Base ();_fag :=&_df .Image {Width :int64 (_gcbg .Width ),Height :int64 (_gcbg .Height ),BitsPerComponent :int64 (_gcbg .BitsPerComponent ),ColorComponents :_gcbg .ColorComponents ,Data :_gcbg .Data };
_fag .SetDecode (_gcbg .Decode );_fag .SetAlpha (_gcbg .Alpha );return _fag ,nil ;};

// Chain allows to use sequence of optimizers.
// It implements interface model.Optimizer.
type Chain struct{_ca []_df .Optimizer };func _aeeda (_edcg _bd .PdfObject )(_afgf string ,_gbd []_bd .PdfObject ){var _bggf _db .Buffer ;switch _beg :=_edcg .(type ){case *_bd .PdfIndirectObject :_gbd =append (_gbd ,_beg );_edcg =_beg .PdfObject ;};switch _aaf :=_edcg .(type ){case *_bd .PdfObjectStream :if _bdfc ,_gcbba :=_bd .DecodeStream (_aaf );
_gcbba ==nil {_bggf .Write (_bdfc );_gbd =append (_gbd ,_aaf );};case *_bd .PdfObjectArray :for _ ,_afae :=range _aaf .Elements (){switch _cfgg :=_afae .(type ){case *_bd .PdfObjectStream :if _cbe ,_dfge :=_bd .DecodeStream (_cfgg );_dfge ==nil {_bggf .Write (_cbe );
_gbd =append (_gbd ,_cfgg );};};};};return _bggf .String (),_gbd ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_agd *CombineDuplicateStreams )Optimize (objects []_bd .PdfObject )(_fda []_bd .PdfObject ,_gdd error ){_deef :=make (map[_bd .PdfObject ]_bd .PdfObject );_dad :=make (map[_bd .PdfObject ]struct{});_dfdf :=make (map[string ][]*_bd .PdfObjectStream );
for _ ,_gacd :=range objects {_adba ,_efa :=_gacd .(*_bd .PdfObjectStream );if !_efa {continue ;};if _adba .Lazy {continue ;};_dbb :=_g .New ();_dbb .Write (_adba .Stream );_dbb .Write (_adba .PdfObjectDictionary .Write ());_cbc :=string (_dbb .Sum (nil ));
_dfdf [_cbc ]=append (_dfdf [_cbc ],_adba );};for _ ,_ccdb :=range _dfdf {if len (_ccdb )< 2{continue ;};_ggd :=_ccdb [0];for _gfd :=1;_gfd < len (_ccdb );_gfd ++{_agg :=_ccdb [_gfd ];_deef [_agg ]=_ggd ;_dad [_agg ]=struct{}{};};};_fda =make ([]_bd .PdfObject ,0,len (objects )-len (_dad ));
for _ ,_afac :=range objects {if _ ,_faaf :=_dad [_afac ];_faaf {continue ;};_fda =append (_fda ,_afac );};_aeac (_fda ,_deef );return _fda ,nil ;};

// Options describes PDF optimization parameters.
type Options struct{CombineDuplicateStreams bool ;CombineDuplicateDirectObjects bool ;ImageUpperPPI float64 ;ImageQuality int ;UseObjectStreams bool ;CombineIdenticalIndirectObjects bool ;CompressStreams bool ;CleanFonts bool ;SubsetFonts bool ;CleanContentstream bool ;
CleanUnusedResources bool ;};

// GetOptimizers gets the list of optimizers in chain `c`.
func (_ee *Chain )GetOptimizers ()[]_df .Optimizer {return _ee ._ca };

// CombineIdenticalIndirectObjects combines identical indirect objects.
// It implements interface model.Optimizer.
type CombineIdenticalIndirectObjects struct{};type objectStructure struct{_cab *_bd .PdfObjectDictionary ;_gaff *_bd .PdfObjectDictionary ;_fbdb []*_bd .PdfIndirectObject ;};func _aeac (_egebg []_bd .PdfObject ,_gbec map[_bd .PdfObject ]_bd .PdfObject ){if len (_gbec )==0{return ;
};for _aef ,_geed :=range _egebg {if _cgbeg ,_fab :=_gbec [_geed ];_fab {_egebg [_aef ]=_cgbeg ;continue ;};_gbec [_geed ]=_geed ;switch _dbbe :=_geed .(type ){case *_bd .PdfObjectArray :_cgbee :=make ([]_bd .PdfObject ,_dbbe .Len ());copy (_cgbee ,_dbbe .Elements ());
_aeac (_cgbee ,_gbec );for _cecb ,_egc :=range _cgbee {_dbbe .Set (_cecb ,_egc );};case *_bd .PdfObjectStreams :_aeac (_dbbe .Elements (),_gbec );case *_bd .PdfObjectStream :_gbag :=[]_bd .PdfObject {_dbbe .PdfObjectDictionary };_aeac (_gbag ,_gbec );_dbbe .PdfObjectDictionary =_gbag [0].(*_bd .PdfObjectDictionary );
case *_bd .PdfObjectDictionary :_edceb :=_dbbe .Keys ();_beac :=make ([]_bd .PdfObject ,len (_edceb ));for _dgfe ,_bdgb :=range _edceb {_beac [_dgfe ]=_dbbe .Get (_bdgb );};_aeac (_beac ,_gbec );for _geeg ,_cea :=range _edceb {_dbbe .Set (_cea ,_beac [_geeg ]);
};case *_bd .PdfIndirectObject :_eefg :=[]_bd .PdfObject {_dbbe .PdfObject };_aeac (_eefg ,_gbec );_dbbe .PdfObject =_eefg [0];};};};

// Optimize optimizes PDF objects to decrease PDF size.
func (_dd *Chain )Optimize (objects []_bd .PdfObject )(_a []_bd .PdfObject ,_ed error ){_dfc :=objects ;for _ ,_gga :=range _dd ._ca {_ce ,_edd :=_gga .Optimize (_dfc );if _edd !=nil {_f .Log .Debug ("\u0045\u0052\u0052OR\u0020\u004f\u0070\u0074\u0069\u006d\u0069\u007a\u0061\u0074\u0069\u006f\u006e\u003a\u0020\u0025\u002b\u0076",_edd );
continue ;};_dfc =_ce ;};return _dfc ,nil ;};func _fd (_gc *_ga .ContentStreamOperations )*_ga .ContentStreamOperations {if _gc ==nil {return nil ;};_fdd :=_ga .ContentStreamOperations {};for _ ,_ef :=range *_gc {switch _ef .Operand {case "\u0042\u0044\u0043","\u0042\u004d\u0043","\u0045\u004d\u0043":continue ;
case "\u0054\u006d":if len (_ef .Params )==6{if _gd ,_fb :=_bd .GetNumbersAsFloat (_ef .Params );_fb ==nil {if _gd [0]==1&&_gd [1]==0&&_gd [2]==0&&_gd [3]==1{_ef =&_ga .ContentStreamOperation {Params :[]_bd .PdfObject {_ef .Params [4],_ef .Params [5]},Operand :"\u0054\u0064"};
};};};};_fdd =append (_fdd ,_ef );};return &_fdd ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bbfc *CompressStreams )Optimize (objects []_bd .PdfObject )(_gfdg []_bd .PdfObject ,_fgf error ){_gfdg =make ([]_bd .PdfObject ,len (objects ));copy (_gfdg ,objects );for _ ,_ggbc :=range objects {_dafg ,_ffca :=_bd .GetStream (_ggbc );if !_ffca {continue ;
};if _dae :=_dafg .Get ("\u0046\u0069\u006c\u0074\u0065\u0072");_dae !=nil {if _ ,_adc :=_bd .GetName (_dae );_adc {continue ;};if _cedc ,_dfca :=_bd .GetArray (_dae );_dfca &&_cedc .Len ()> 0{continue ;};};_dgfd :=_bd .NewFlateEncoder ();var _eab []byte ;
_eab ,_fgf =_dgfd .EncodeBytes (_dafg .Stream );if _fgf !=nil {return _gfdg ,_fgf ;};_cdc :=_dgfd .MakeStreamDict ();if len (_eab )+len (_cdc .Write ())< len (_dafg .Stream ){_dafg .Stream =_eab ;_dafg .PdfObjectDictionary .Merge (_cdc );_dafg .PdfObjectDictionary .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_bd .MakeInteger (int64 (len (_dafg .Stream ))));
};};return _gfdg ,nil ;};func _dgdf (_cgeb []_bd .PdfObject )(map[_bd .PdfObject ]struct{},error ){_cacf :=_gdbbg (_cgeb );_bga :=_cacf ._fbdb ;_dgde :=make (map[_bd .PdfObject ]struct{});_eeb :=_bge (_bga );for _ ,_gebg :=range _bga {_gef ,_gbb :=_bd .GetDict (_gebg .PdfObject );
if !_gbb {continue ;};_afde ,_gbb :=_bd .GetDict (_gef .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_gbb {continue ;};_dfb :=_eeb ["\u0058O\u0062\u006a\u0065\u0063\u0074"];_bbc ,_gbb :=_bd .GetDict (_afde .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));
if _gbb {_bde :=_cff (_bbc );for _ ,_bgbg :=range _bde {if _ffed (_bgbg ,_dfb ){continue ;};_bca :=*_bd .MakeName (_bgbg );_ebd :=_bbc .Get (_bca );_dgde [_ebd ]=struct{}{};_bbc .Remove (_bca );_ffab :=_gdbb (_ebd ,_dgde );if _ffab !=nil {_f .Log .Debug ("\u0066\u0061\u0069\u006ce\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065r\u0073e\u0020\u006f\u0062\u006a\u0065\u0063\u0074 \u0025\u0076",_ebd );
};};};_caf ,_gbb :=_bd .GetDict (_afde .Get ("\u0046\u006f\u006e\u0074"));_fdf :=_eeb ["\u0046\u006f\u006e\u0074"];if _gbb {_feab :=_cff (_caf );for _ ,_fgg :=range _feab {if _ffed (_fgg ,_fdf ){continue ;};_fbd :=*_bd .MakeName (_fgg );_dfg :=_caf .Get (_fbd );
_dgde [_dfg ]=struct{}{};_caf .Remove (_fbd );_bede :=_gdbb (_dfg ,_dgde );if _bede !=nil {_f .Log .Debug ("\u0046\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_dfg );
};};};_efdb ,_gbb :=_bd .GetDict (_afde .Get ("\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"));if _gbb {_bec :=_cff (_efdb );_dfdc :=_eeb ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];for _ ,_ceda :=range _bec {if _ffed (_ceda ,_dfdc ){continue ;};_cag :=*_bd .MakeName (_ceda );
_dea :=_efdb .Get (_cag );_dgde [_dea ]=struct{}{};_efdb .Remove (_cag );_fec :=_gdbb (_dea ,_dgde );if _fec !=nil {_f .Log .Debug ("\u0066\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_dea );
};};};};return _dgde ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_debd *CombineDuplicateDirectObjects )Optimize (objects []_bd .PdfObject )(_ege []_bd .PdfObject ,_gfb error ){_dagf (objects );_gffg :=make (map[string ][]*_bd .PdfObjectDictionary );var _debdd func (_adb *_bd .PdfObjectDictionary );_debdd =func (_bba *_bd .PdfObjectDictionary ){for _ ,_dfgb :=range _bba .Keys (){_gbg :=_bba .Get (_dfgb );
if _cee ,_gffc :=_gbg .(*_bd .PdfObjectDictionary );_gffc {if _cgg :=_cee .Keys ();len (_cgg )==0{continue ;};_egg :=_e .New ();_egg .Write (_cee .Write ());_cbd :=string (_egg .Sum (nil ));_gffg [_cbd ]=append (_gffg [_cbd ],_cee );_debdd (_cee );};};
};for _ ,_ccbb :=range objects {_dfdgd ,_bcb :=_ccbb .(*_bd .PdfIndirectObject );if !_bcb {continue ;};if _egbe ,_dfda :=_dfdgd .PdfObject .(*_bd .PdfObjectDictionary );_dfda {_debdd (_egbe );};};_fdbd :=make ([]_bd .PdfObject ,0,len (_gffg ));_ggaae :=make (map[_bd .PdfObject ]_bd .PdfObject );
for _ ,_egdc :=range _gffg {if len (_egdc )< 2{continue ;};_gge :=_bd .MakeDict ();_gge .Merge (_egdc [0]);_efb :=_bd .MakeIndirectObject (_gge );_fdbd =append (_fdbd ,_efb );for _feda :=0;_feda < len (_egdc );_feda ++{_cafd :=_egdc [_feda ];_ggaae [_cafd ]=_efb ;
};};_ege =make ([]_bd .PdfObject ,len (objects ));copy (_ege ,objects );_ege =append (_fdbd ,_ege ...);_aeac (_ege ,_ggaae );return _ege ,nil ;};type imageModifications struct{Scale float64 ;Encoding _bd .StreamEncoder ;};func _bdg (_ag *_bd .PdfObjectStream )error {_bgc ,_fg :=_bd .DecodeStream (_ag );
if _fg !=nil {return _fg ;};_cb :=_ga .NewContentStreamParser (string (_bgc ));_da ,_fg :=_cb .Parse ();if _fg !=nil {return _fg ;};_da =_fd (_da );_deg :=_da .Bytes ();if len (_deg )>=len (_bgc ){return nil ;};_ac ,_fg :=_bd .MakeStream (_da .Bytes (),_bd .NewFlateEncoder ());
if _fg !=nil {return _fg ;};_ag .Stream =_ac .Stream ;_ag .Merge (_ac .PdfObjectDictionary );return nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_fe *CleanContentstream )Optimize (objects []_bd .PdfObject )(_gaa []_bd .PdfObject ,_dfd error ){_be :=map[*_bd .PdfObjectStream ]struct{}{};var _cg []*_bd .PdfObjectStream ;_gf :=func (_dag *_bd .PdfObjectStream ){if _ ,_gac :=_be [_dag ];!_gac {_be [_dag ]=struct{}{};
_cg =append (_cg ,_dag );};};_ab :=map[_bd .PdfObject ]bool {};_eb :=map[_bd .PdfObject ]bool {};for _ ,_feg :=range objects {switch _fc :=_feg .(type ){case *_bd .PdfIndirectObject :switch _ggfc :=_fc .PdfObject .(type ){case *_bd .PdfObjectDictionary :if _cgc ,_gfe :=_bd .GetName (_ggfc .Get ("\u0054\u0079\u0070\u0065"));
!_gfe ||_cgc .String ()!="\u0050\u0061\u0067\u0065"{continue ;};if _dg ,_cge :=_bd .GetStream (_ggfc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_cge {_gf (_dg );}else if _edf ,_ge :=_bd .GetArray (_ggfc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));
_ge {var _fba []*_bd .PdfObjectStream ;for _ ,_def :=range _edf .Elements (){if _fea ,_af :=_bd .GetStream (_def );_af {_fba =append (_fba ,_fea );};};if len (_fba )> 0{var _ba _db .Buffer ;for _ ,_bfd :=range _fba {if _agf ,_dc :=_bd .DecodeStream (_bfd );
_dc ==nil {_ba .Write (_agf );};_ab [_bfd ]=true ;};_dcc ,_eg :=_bd .MakeStream (_ba .Bytes (),_bd .NewFlateEncoder ());if _eg !=nil {return nil ,_eg ;};_eb [_dcc ]=true ;_ggfc .Set ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073",_dcc );_gf (_dcc );
};};};case *_bd .PdfObjectStream :if _bbg ,_ggg :=_bd .GetName (_fc .Get ("\u0054\u0079\u0070\u0065"));!_ggg ||_bbg .String ()!="\u0058O\u0062\u006a\u0065\u0063\u0074"{continue ;};if _ec ,_gb :=_bd .GetName (_fc .Get ("\u0053u\u0062\u0074\u0079\u0070\u0065"));
!_gb ||_ec .String ()!="\u0046\u006f\u0072\u006d"{continue ;};_gf (_fc );};};for _ ,_egd :=range _cg {_dfd =_bdg (_egd );if _dfd !=nil {return nil ,_dfd ;};};_gaa =nil ;for _ ,_fcd :=range objects {if _ab [_fcd ]{continue ;};_gaa =append (_gaa ,_fcd );
};for _efd :=range _eb {_gaa =append (_gaa ,_efd );};return _gaa ,nil ;};func _gbgg (_dgdfe *_df .XObjectImage ,_debe imageModifications )error {_eafe ,_deee :=_dgdfe .ToImage ();if _deee !=nil {return _deee ;};if _debe .Scale !=0{_eafe ,_deee =_dfbd (_eafe ,_debe .Scale );
if _deee !=nil {return _deee ;};};if _debe .Encoding !=nil {_dgdfe .Filter =_debe .Encoding ;};_dgdfe .Decode =nil ;switch _dfa :=_dgdfe .Filter .(type ){case *_bd .FlateEncoder :if _dfa .Predictor !=1&&_dfa .Predictor !=11{_dfa .Predictor =1;};};if _deee =_dgdfe .SetImage (_eafe ,nil );
_deee !=nil {_f .Log .Debug ("\u0045\u0072\u0072or\u0020\u0073\u0065\u0074\u0074\u0069\u006e\u0067\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0076",_deee );return _deee ;};_dgdfe .ToPdfObject ();return nil ;};func _gdbbg (_ffdca []_bd .PdfObject )objectStructure {_ffddc :=objectStructure {};
_gggb :=false ;for _ ,_egfd :=range _ffdca {switch _bcff :=_egfd .(type ){case *_bd .PdfIndirectObject :_dagfb ,_dbgg :=_bd .GetDict (_bcff );if !_dbgg {continue ;};_gadg ,_dbgg :=_bd .GetName (_dagfb .Get ("\u0054\u0079\u0070\u0065"));if !_dbgg {continue ;
};switch _gadg .String (){case "\u0043a\u0074\u0061\u006c\u006f\u0067":_ffddc ._cab =_dagfb ;_gggb =true ;};};if _gggb {break ;};};if !_gggb {return _ffddc ;};_ddga ,_ddgf :=_bd .GetDict (_ffddc ._cab .Get ("\u0050\u0061\u0067e\u0073"));if !_ddgf {return _ffddc ;
};_ffddc ._gaff =_ddga ;_aba ,_ddgf :=_bd .GetArray (_ddga .Get ("\u004b\u0069\u0064\u0073"));if !_ddgf {return _ffddc ;};for _ ,_bfa :=range _aba .Elements (){_adeg ,_bfcc :=_bd .GetIndirect (_bfa );if !_bfcc {break ;};_ffddc ._fbdb =append (_ffddc ._fbdb ,_adeg );
};return _ffddc ;};func _cefg (_gefa []_bd .PdfObject )[]*imageInfo {_egbg :=_bd .PdfObjectName ("\u0053u\u0062\u0074\u0079\u0070\u0065");_aeb :=make (map[*_bd .PdfObjectStream ]struct{});var _gcbb []*imageInfo ;for _ ,_abf :=range _gefa {_cgeg ,_ggbe :=_bd .GetStream (_abf );
if !_ggbe {continue ;};if _ ,_gbae :=_aeb [_cgeg ];_gbae {continue ;};_aeb [_cgeg ]=struct{}{};_egeb :=_cgeg .PdfObjectDictionary .Get (_egbg );_add ,_ggbe :=_bd .GetName (_egeb );if !_ggbe ||string (*_add )!="\u0049\u006d\u0061g\u0065"{continue ;};_gad :=&imageInfo {Stream :_cgeg ,BitsPerComponent :8};
if _aae ,_acbg :=_bd .GetIntVal (_cgeg .Get ("\u0042\u0069t\u0073\u0050\u0065r\u0043\u006f\u006d\u0070\u006f\u006e\u0065\u006e\u0074"));_acbg {_gad .BitsPerComponent =_aae ;};if _fae ,_gbbd :=_bd .GetIntVal (_cgeg .Get ("\u0057\u0069\u0064t\u0068"));_gbbd {_gad .Width =_fae ;
};if _ddb ,_ffdd :=_bd .GetIntVal (_cgeg .Get ("\u0048\u0065\u0069\u0067\u0068\u0074"));_ffdd {_gad .Height =_ddb ;};_gdec ,_cbcbe :=_df .NewPdfColorspaceFromPdfObject (_cgeg .Get ("\u0043\u006f\u006c\u006f\u0072\u0053\u0070\u0061\u0063\u0065"));if _cbcbe !=nil {_f .Log .Debug ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_cbcbe );
continue ;};if _gdec ==nil {_gbed ,_gfg :=_bd .GetName (_cgeg .Get ("\u0046\u0069\u006c\u0074\u0065\u0072"));if _gfg {switch _gbed .String (){case "\u0043\u0043\u0049\u0054\u0054\u0046\u0061\u0078\u0044e\u0063\u006f\u0064\u0065","J\u0042\u0049\u0047\u0032\u0044\u0065\u0063\u006f\u0064\u0065":_gdec =_df .NewPdfColorspaceDeviceGray ();
_gad .BitsPerComponent =1;};};};switch _cagg :=_gdec .(type ){case *_df .PdfColorspaceDeviceRGB :_gad .ColorComponents =3;case *_df .PdfColorspaceDeviceGray :_gad .ColorComponents =1;default:_f .Log .Debug ("\u004f\u0070\u0074\u0069\u006d\u0069\u007aa\u0074\u0069\u006fn\u0020\u0069\u0073 \u006e\u006ft\u0020\u0073\u0075\u0070\u0070\u006fr\u0074ed\u0020\u0066\u006f\u0072\u0020\u0063\u006f\u006c\u006f\u0072\u0020\u0073\u0070\u0061\u0063\u0065\u0020\u0025\u0054\u0020\u002d\u0020\u0073\u006b\u0069\u0070",_cagg );
continue ;};_gcbb =append (_gcbb ,_gad );};return _gcbb ;};func _aa (_bbb []_bd .PdfObject )(_edfc map[*_bd .PdfObjectStream ]struct{},_cfa error ){_edfc =map[*_bd .PdfObjectStream ]struct{}{};_afd :=map[*_df .PdfFont ]struct{}{};_cfe :=_gdbbg (_bbb );
for _ ,_gcf :=range _cfe ._fbdb {_cac ,_defd :=_bd .GetDict (_gcf .PdfObject );if !_defd {continue ;};_cbb ,_defd :=_bd .GetDict (_cac .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_defd {continue ;};_ggc ,_ :=_aeeda (_cac .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));
_eda ,_dagb :=_df .NewPdfPageResourcesFromDict (_cbb );if _dagb !=nil {return nil ,_dagb ;};_ae :=[]content {{_edce :_ggc ,_gdb :_eda }};_geb :=_cca (_cac .Get ("\u0041\u006e\u006e\u006f\u0074\u0073"));if _geb !=nil {_ae =append (_ae ,_geb ...);};for _ ,_bgb :=range _ae {_aag ,_bed :=_gg .NewFromContents (_bgb ._edce ,_bgb ._gdb );
if _bed !=nil {return nil ,_bed ;};_aab ,_ ,_ ,_bed :=_aag .ExtractPageText ();if _bed !=nil {return nil ,_bed ;};for _ ,_bdf :=range _aab .Marks ().Elements (){if _bdf .Font ==nil {continue ;};if _ ,_ggaa :=_afd [_bdf .Font ];!_ggaa {_afd [_bdf .Font ]=struct{}{};
};};};};_dbd :=map[*_bd .PdfObjectStream ][]*_df .PdfFont {};for _aca :=range _afd {_ccb :=_aca .FontDescriptor ();if _ccb ==nil ||_ccb .FontFile2 ==nil {continue ;};_aea ,_fgd :=_bd .GetStream (_ccb .FontFile2 );if !_fgd {continue ;};_dbd [_aea ]=append (_dbd [_aea ],_aca );
};for _bgce :=range _dbd {var _degc []rune ;var _ffa []_bb .GlyphIndex ;for _ ,_cgbe :=range _dbd [_bgce ]{switch _ecg :=_cgbe .Encoder ().(type ){case *_bg .IdentityEncoder :_egb :=_ecg .RegisteredRunes ();_ccf :=make ([]_bb .GlyphIndex ,len (_egb ));
for _gee ,_cdg :=range _egb {_ccf [_gee ]=_bb .GlyphIndex (_cdg );};_ffa =append (_ffa ,_ccf ...);case *_bg .TrueTypeFontEncoder :_fce :=_ecg .RegisteredRunes ();_degc =append (_degc ,_fce ...);case _bg .SimpleEncoder :_cda :=_ecg .Charcodes ();for _ ,_gcc :=range _cda {_ecd ,_edfe :=_ecg .CharcodeToRune (_gcc );
if !_edfe {_f .Log .Debug ("\u0043\u0068a\u0072\u0063\u006f\u0064\u0065\u003c\u002d\u003e\u0072\u0075\u006e\u0065\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064: \u0025\u0064",_gcc );continue ;};_degc =append (_degc ,_ecd );};};};_cfa =_bef (_bgce ,_degc ,_ffa );
if _cfa !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006eg\u0020f\u006f\u006e\u0074\u0020\u0073\u0074\u0072\u0065\u0061\u006d\u003a\u0020\u0025\u0076",_cfa );return nil ,_cfa ;};_edfc [_bgce ]=struct{}{};
};return _edfc ,nil ;};

// Image optimizes images by rewrite images into JPEG format with quality equals to ImageQuality.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type Image struct{ImageQuality int ;};type imageInfo struct{BitsPerComponent int ;ColorComponents int ;Width int ;Height int ;Stream *_bd .PdfObjectStream ;PPI float64 ;};

// New creates a optimizers chain from options.
func New (options Options )*Chain {_cdce :=new (Chain );if options .CleanFonts ||options .SubsetFonts {_cdce .Append (&CleanFonts {Subset :options .SubsetFonts });};if options .CleanContentstream {_cdce .Append (new (CleanContentstream ));};if options .ImageUpperPPI > 0{_adca :=new (ImagePPI );
_adca .ImageUpperPPI =options .ImageUpperPPI ;_cdce .Append (_adca );};if options .ImageQuality > 0{_cbce :=new (Image );_cbce .ImageQuality =options .ImageQuality ;_cdce .Append (_cbce );};if options .CombineDuplicateDirectObjects {_cdce .Append (new (CombineDuplicateDirectObjects ));
};if options .CombineDuplicateStreams {_cdce .Append (new (CombineDuplicateStreams ));};if options .CombineIdenticalIndirectObjects {_cdce .Append (new (CombineIdenticalIndirectObjects ));};if options .UseObjectStreams {_cdce .Append (new (ObjectStreams ));
};if options .CompressStreams {_cdce .Append (new (CompressStreams ));};if options .CleanUnusedResources {_cdce .Append (new (CleanUnusedResources ));};return _cdce ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_cfb *CleanFonts )Optimize (objects []_bd .PdfObject )(_gbe []_bd .PdfObject ,_fcdf error ){var _dfde map[*_bd .PdfObjectStream ]struct{};if _cfb .Subset {var _beb error ;_dfde ,_beb =_aa (objects );if _beb !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004fR\u003a\u0020\u0046\u0061\u0069\u006c\u0065\u0064\u0020\u0073u\u0062s\u0065\u0074\u0074\u0069\u006e\u0067\u003a \u0025\u0076",_beb );
return nil ,_beb ;};};for _ ,_bfc :=range objects {_acg ,_ecf :=_bd .GetStream (_bfc );if !_ecf {continue ;};if _ ,_bdfag :=_dfde [_acg ];_bdfag {continue ;};_ffc ,_fdde :=_bd .NewEncoderFromStream (_acg );if _fdde !=nil {_f .Log .Debug ("\u0045\u0052RO\u0052\u0020\u0067e\u0074\u0074\u0069\u006eg e\u006eco\u0064\u0065\u0072\u003a\u0020\u0025\u0076 -\u0020\u0069\u0067\u006e\u006f\u0072\u0069n\u0067",_fdde );
continue ;};_fca ,_fdde :=_ffc .DecodeStream (_acg );if _fdde !=nil {_f .Log .Debug ("\u0044\u0065\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0065r\u0072\u006f\u0072\u0020\u003a\u0020\u0025v\u0020\u002d\u0020\u0069\u0067\u006e\u006f\u0072\u0069\u006e\u0067",_fdde );
continue ;};if len (_fca )< 4{continue ;};_ceb :=string (_fca [:4]);if _ceb =="\u004f\u0054\u0054\u004f"{continue ;};if _ceb !="\u0000\u0001\u0000\u0000"&&_ceb !="\u0074\u0072\u0075\u0065"{continue ;};_gfc ,_fdde :=_bb .Parse (_db .NewReader (_fca ));if _fdde !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020P\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_fdde );
continue ;};_fdde =_gfc .Optimize ();if _fdde !=nil {_f .Log .Debug ("\u0045\u0052RO\u0052\u0020\u004fp\u0074\u0069\u006d\u0069zin\u0067 f\u006f\u006e\u0074\u003a\u0020\u0025\u0076 -\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067",_fdde );continue ;};
var _afa _db .Buffer ;_fdde =_gfc .Write (&_afa );if _fdde !=nil {_f .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020W\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_fdde );
continue ;};if _afa .Len ()> len (_fca ){_f .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
continue ;};_bbbc ,_fdde :=_bd .MakeStream (_afa .Bytes (),_bd .NewFlateEncoder ());if _fdde !=nil {continue ;};*_acg =*_bbbc ;_acg .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_bd .MakeInteger (int64 (_afa .Len ())));};return objects ,nil ;};