//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package optimize ;import (_gf "bytes";_fb "crypto/md5";_ebe "errors";_g "fmt";_c "github.com/unidoc/unipdf/v4/common";_ed "github.com/unidoc/unipdf/v4/contentstream";_gc "github.com/unidoc/unipdf/v4/core";_a "github.com/unidoc/unipdf/v4/extractor";_da "github.com/unidoc/unipdf/v4/internal/imageutil";
_eb "github.com/unidoc/unipdf/v4/internal/textencoding";_ga "github.com/unidoc/unipdf/v4/model";_dd "github.com/unidoc/unitype";_f "golang.org/x/image/draw";_d "math";_eg "strings";);

// Optimize implements Optimizer interface.
func (_fec *CleanUnusedResources )Optimize (objects []_gc .PdfObject )(_fbdbf []_gc .PdfObject ,_gab error ){_aaf ,_gab :=_gba (objects );if _gab !=nil {return nil ,_gab ;};_dafd :=[]_gc .PdfObject {};for _ ,_efe :=range objects {_ ,_cce :=_aaf [_efe ];
if _cce {continue ;};_dafd =append (_dafd ,_efe );};return _dafd ,nil ;};func _acc (_bbbf []*_gc .PdfIndirectObject )map[string ][]string {_ebd :=map[string ][]string {};for _ ,_feb :=range _bbbf {_dcd ,_bfc :=_gc .GetDict (_feb .PdfObject );if !_bfc {continue ;
};_aaee :=_dcd .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073");_dea :=_gc .TraceToDirectObject (_aaee );_dbc :="";if _fbc ,_edcg :=_dea .(*_gc .PdfObjectArray );_edcg {var _feae []string ;for _ ,_eee :=range _fbc .Elements (){_gcf ,_fdba :=_gdd (_eee );
if _fdba !=nil {continue ;};_feae =append (_feae ,_gcf );};_dbc =_eg .Join (_feae ,"\u0020");};if _edb ,_eeec :=_dea .(*_gc .PdfObjectStream );_eeec {_bgg ,_dg :=_gc .DecodeStream (_edb );if _dg !=nil {continue ;};_dbc =string (_bgg );};_fae :=_ed .NewContentStreamParser (_dbc );
_fbfg ,_fda :=_fae .Parse ();if _fda !=nil {continue ;};for _ ,_eab :=range *_fbfg {_cba :=_eab .Operand ;_ccea :=_eab .Params ;switch _cba {case "\u0044\u006f":_eefa :=_ccea [0].String ();if _ ,_baa :=_ebd ["\u0058O\u0062\u006a\u0065\u0063\u0074"];!_baa {_ebd ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=[]string {_eefa };
}else {_ebd ["\u0058O\u0062\u006a\u0065\u0063\u0074"]=append (_ebd ["\u0058O\u0062\u006a\u0065\u0063\u0074"],_eefa );};case "\u0054\u0066":_cfbb :=_ccea [0].String ();if _ ,_fag :=_ebd ["\u0046\u006f\u006e\u0074"];!_fag {_ebd ["\u0046\u006f\u006e\u0074"]=[]string {_cfbb };
}else {_ebd ["\u0046\u006f\u006e\u0074"]=append (_ebd ["\u0046\u006f\u006e\u0074"],_cfbb );};case "\u0067\u0073":_gede :=_ccea [0].String ();if _ ,_efee :=_ebd ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];!_efee {_ebd ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=[]string {_gede };
}else {_ebd ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"]=append (_ebd ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"],_gede );};};};};return _ebd ;};func _aeg (_cfb []_gc .PdfObject )(_egd map[*_gc .PdfObjectStream ]struct{},_cae error ){_egd =map[*_gc .PdfObjectStream ]struct{}{};
_gfg :=map[*_ga .PdfFont ]struct{}{};_gcg :=_dbb (_cfb );for _ ,_fef :=range _gcg ._cfe {_dda ,_dfa :=_gc .GetDict (_fef .PdfObject );if !_dfa {continue ;};_eec ,_dfa :=_gc .GetDict (_dda .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_dfa {continue ;
};_bee ,_ :=_eccd (_dda .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_afcd ,_fcd :=_ga .NewPdfPageResourcesFromDict (_eec );if _fcd !=nil {return nil ,_fcd ;};_fbda :=[]content {{_aag :_bee ,_dee :_afcd }};_fcdb :=_ccc (_dda .Get ("\u0041\u006e\u006e\u006f\u0074\u0073"));
if _fcdb !=nil {_fbda =append (_fbda ,_fcdb ...);};for _ ,_bf :=range _fbda {_ccd ,_ecea :=_a .NewFromContents (_bf ._aag ,_bf ._dee );if _ecea !=nil {return nil ,_ecea ;};_gd ,_ ,_ ,_ecea :=_ccd .ExtractPageText ();if _ecea !=nil {return nil ,_ecea ;};
for _ ,_gcc :=range _gd .Marks ().Elements (){if _gcc .Font ==nil {continue ;};if _ ,_adbe :=_gfg [_gcc .Font ];!_adbe {_gfg [_gcc .Font ]=struct{}{};};};};};_gbg :=map[*_gc .PdfObjectStream ][]*_ga .PdfFont {};for _gge :=range _gfg {_cd :=_gge .FontDescriptor ();
if _cd ==nil ||_cd .FontFile2 ==nil {continue ;};_cgf ,_aac :=_gc .GetStream (_cd .FontFile2 );if !_aac {continue ;};_gbg [_cgf ]=append (_gbg [_cgf ],_gge );};for _fgg :=range _gbg {var _aded []rune ;var _bbb []_dd .GlyphIndex ;for _ ,_eda :=range _gbg [_fgg ]{switch _caa :=_eda .Encoder ().(type ){case *_eb .IdentityEncoder :_ffe :=_caa .RegisteredRunes ();
_fgd :=make ([]_dd .GlyphIndex ,len (_ffe ));for _eff ,_bff :=range _ffe {_fgd [_eff ]=_dd .GlyphIndex (_bff );};_bbb =append (_bbb ,_fgd ...);case *_eb .TrueTypeFontEncoder :_bgf :=_caa .RegisteredRunes ();_aded =append (_aded ,_bgf ...);case _eb .SimpleEncoder :_aef :=_caa .Charcodes ();
for _ ,_dc :=range _aef {_bga ,_eeg :=_caa .CharcodeToRune (_dc );if !_eeg {_c .Log .Debug ("\u0043\u0068a\u0072\u0063\u006f\u0064\u0065\u003c\u002d\u003e\u0072\u0075\u006e\u0065\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064: \u0025\u0064",_dc );
continue ;};_aded =append (_aded ,_bga );};};};_cae =_aae (_fgg ,_aded ,_bbb );if _cae !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006eg\u0020f\u006f\u006e\u0074\u0020\u0073\u0074\u0072\u0065\u0061\u006d\u003a\u0020\u0025\u0076",_cae );
return nil ,_cae ;};_egd [_fgg ]=struct{}{};};return _egd ,nil ;};func _ccc (_fca _gc .PdfObject )[]content {if _fca ==nil {return nil ;};_abd ,_gaea :=_gc .GetArray (_fca );if !_gaea {_c .Log .Debug ("\u0041\u006e\u006e\u006fts\u0020\u006e\u006f\u0074\u0020\u0061\u006e\u0020\u0061\u0072\u0072\u0061\u0079");
return nil ;};var _cge []content ;for _ ,_eaf :=range _abd .Elements (){_ced ,_ace :=_gc .GetDict (_eaf );if !_ace {_c .Log .Debug ("I\u0067\u006e\u006f\u0072\u0069\u006eg\u0020\u006e\u006f\u006e\u002d\u0064i\u0063\u0074\u0020\u0065\u006c\u0065\u006de\u006e\u0074\u0020\u0069\u006e\u0020\u0041\u006e\u006e\u006ft\u0073");
continue ;};_gdb ,_ace :=_gc .GetDict (_ced .Get ("\u0041\u0050"));if !_ace {_c .Log .Debug ("\u004e\u006f\u0020\u0041P \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_fbdb :=_gc .TraceToDirectObject (_gdb .Get ("\u004e"));
if _fbdb ==nil {_c .Log .Debug ("N\u006f\u0020\u004e\u0020en\u0074r\u0079\u0020\u002d\u0020\u0073k\u0069\u0070\u0070\u0069\u006e\u0067");continue ;};var _acb *_gc .PdfObjectStream ;switch _bfb :=_fbdb .(type ){case *_gc .PdfObjectDictionary :_fac ,_eef :=_gc .GetName (_ced .Get ("\u0041\u0053"));
if !_eef {_c .Log .Debug ("\u004e\u006f\u0020\u0041S \u0065\u006e\u0074\u0072\u0079\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067");continue ;};_acb ,_eef =_gc .GetStream (_bfb .Get (*_fac ));if !_eef {_c .Log .Debug ("\u0046o\u0072\u006d\u0020\u006eo\u0074\u0020\u0066\u006f\u0075n\u0064 \u002d \u0073\u006b\u0069\u0070\u0070\u0069\u006eg");
continue ;};case *_gc .PdfObjectStream :_acb =_bfb ;};if _acb ==nil {_c .Log .Debug ("\u0046\u006f\u0072m\u0020\u006e\u006f\u0074 \u0066\u006f\u0075\u006e\u0064\u0020\u0028n\u0069\u006c\u0029\u0020\u002d\u0020\u0073\u006b\u0069\u0070\u0070\u0069\u006e\u0067");
continue ;};_dca ,_aagd :=_ga .NewXObjectFormFromStream (_acb );if _aagd !=nil {_c .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020l\u006f\u0061\u0064\u0069\u006e\u0067\u0020\u0066\u006f\u0072\u006d\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_aagd );
continue ;};_bbf ,_aagd :=_dca .GetContentStream ();if _aagd !=nil {_c .Log .Debug ("E\u0072\u0072\u006f\u0072\u0020\u0064e\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0063\u006fn\u0074\u0065\u006et\u0073:\u0020\u0025\u0076",_aagd );continue ;};_cge =append (_cge ,content {_aag :string (_bbf ),_dee :_dca .Resources });
};return _cge ;};

// ImagePPI optimizes images by scaling images such that the PPI (pixels per inch) is never higher than ImageUpperPPI.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type ImagePPI struct{ImageUpperPPI float64 ;};func _dbb (_geeg []_gc .PdfObject )objectStructure {_febb :=objectStructure {};_cbf :=false ;for _ ,_fggd :=range _geeg {switch _gfae :=_fggd .(type ){case *_gc .PdfIndirectObject :_agfg ,_fdbfc :=_gc .GetDict (_gfae );
if !_fdbfc {continue ;};_ecec ,_fdbfc :=_gc .GetName (_agfg .Get ("\u0054\u0079\u0070\u0065"));if !_fdbfc {continue ;};switch _ecec .String (){case "\u0043a\u0074\u0061\u006c\u006f\u0067":_febb ._acg =_agfg ;_cbf =true ;};};if _cbf {break ;};};if !_cbf {return _febb ;
};_fgb ,_fad :=_gc .GetDict (_febb ._acg .Get ("\u0050\u0061\u0067e\u0073"));if !_fad {return _febb ;};_febb ._ebda =_fgb ;_aab ,_fad :=_gc .GetArray (_fgb .Get ("\u004b\u0069\u0064\u0073"));if !_fad {return _febb ;};for _ ,_beb :=range _aab .Elements (){_ccfa ,_cgbb :=_gc .GetIndirect (_beb );
if !_cgbb {break ;};_febb ._cfe =append (_febb ._cfe ,_ccfa );};return _febb ;};

// New creates a optimizers chain from options.
func New (options Options )*Chain {_bce :=new (Chain );if options .CleanFonts ||options .SubsetFonts {_bce .Append (&CleanFonts {Subset :options .SubsetFonts });};if options .CleanContentstream {_bce .Append (new (CleanContentstream ));};if options .ImageUpperPPI > 0{_degd :=new (ImagePPI );
_degd .ImageUpperPPI =options .ImageUpperPPI ;_bce .Append (_degd );};if options .ImageQuality > 0{_bccb :=new (Image );_bccb .ImageQuality =options .ImageQuality ;_bce .Append (_bccb );};if options .CombineDuplicateDirectObjects {_bce .Append (new (CombineDuplicateDirectObjects ));
};if options .CombineDuplicateStreams {_bce .Append (new (CombineDuplicateStreams ));};if options .CombineIdenticalIndirectObjects {_bce .Append (new (CombineIdenticalIndirectObjects ));};if options .UseObjectStreams {_bce .Append (new (ObjectStreams ));
};if options .CompressStreams {_bce .Append (new (CompressStreams ));};if options .CleanUnusedResources {_bce .Append (new (CleanUnusedResources ));};return _bce ;};func _cdaf (_geed *_gc .PdfObjectDictionary )[]string {_dcce :=[]string {};for _ ,_ddb :=range _geed .Keys (){_dcce =append (_dcce ,_ddb .String ());
};return _dcce ;};type imageModifications struct{Scale float64 ;Encoding _gc .StreamEncoder ;};func _gdd (_cgba _gc .PdfObject )(string ,error ){_baae :=_gc .TraceToDirectObject (_cgba );switch _bfbg :=_baae .(type ){case *_gc .PdfObjectString :return _bfbg .Str (),nil ;
case *_gc .PdfObjectStream :_caf ,_eeb :=_gc .DecodeStream (_bfbg );if _eeb !=nil {return "",_eeb ;};return string (_caf ),nil ;};return "",_g .Errorf ("\u0069\u006e\u0076\u0061\u006ci\u0064\u0020\u0063\u006f\u006e\u0074\u0065\u006e\u0074\u0020\u0073\u0074\u0072e\u0061\u006d\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020\u0068\u006f\u006c\u0064\u0065\u0072\u0020\u0028\u0025\u0054\u0029",_baae );
};

// CombineDuplicateStreams combines duplicated streams by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateStreams struct{};func _add (_gdge string ,_aee []string )bool {for _ ,_edd :=range _aee {if _gdge ==_edd {return true ;};};return false ;};func _gdbg (_adgb *_ga .XObjectImage ,_fefc imageModifications )error {_bbg ,_cagb :=_adgb .ToImage ();
if _cagb !=nil {return _cagb ;};if _fefc .Scale !=0{_bbg ,_cagb =_dfff (_bbg ,_fefc .Scale );if _cagb !=nil {return _cagb ;};};if _fefc .Encoding !=nil {_adgb .Filter =_fefc .Encoding ;};_adgb .Decode =nil ;switch _cdec :=_adgb .Filter .(type ){case *_gc .FlateEncoder :if _cdec .Predictor !=1&&_cdec .Predictor !=11{_cdec .Predictor =1;
};};if _cagb =_adgb .SetImage (_bbg ,nil );_cagb !=nil {_c .Log .Debug ("\u0045\u0072\u0072or\u0020\u0073\u0065\u0074\u0074\u0069\u006e\u0067\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0076",_cagb );return _cagb ;};_adgb .ToPdfObject ();return nil ;
};

// CompressStreams compresses uncompressed streams.
// It implements interface model.Optimizer.
type CompressStreams struct{};

// GetOptimizers gets the list of optimizers in chain `c`.
func (_ddd *Chain )GetOptimizers ()[]_ga .Optimizer {return _ddd ._ca };func _dfff (_bcde *_ga .Image ,_bbab float64 )(*_ga .Image ,error ){_fbgc ,_bbbe :=_bcde .ToGoImage ();if _bbbe !=nil {return nil ,_bbbe ;};var _bdefd _da .Image ;_dcgf ,_aafa :=_fbgc .(*_da .Monochrome );
if _aafa {if _bbbe =_dcgf .ResolveDecode ();_bbbe !=nil {return nil ,_bbbe ;};_bdefd ,_bbbe =_dcgf .Scale (_bbab );if _bbbe !=nil {return nil ,_bbbe ;};}else {_faca :=int (_d .RoundToEven (float64 (_bcde .Width )*_bbab ));_egdf :=int (_d .RoundToEven (float64 (_bcde .Height )*_bbab ));
_bdefd ,_bbbe =_da .NewImage (_faca ,_egdf ,int (_bcde .BitsPerComponent ),_bcde .ColorComponents ,nil ,nil ,nil );if _bbbe !=nil {return nil ,_bbbe ;};_f .CatmullRom .Scale (_bdefd ,_bdefd .Bounds (),_fbgc ,_fbgc .Bounds (),_f .Over ,&_f .Options {});
};_ffde :=_bdefd .Base ();_aea :=&_ga .Image {Width :int64 (_ffde .Width ),Height :int64 (_ffde .Height ),BitsPerComponent :int64 (_ffde .BitsPerComponent ),ColorComponents :_ffde .ColorComponents ,Data :_ffde .Data };_aea .SetDecode (_ffde .Decode );_aea .SetAlpha (_ffde .Alpha );
return _aea ,nil ;};

// Append appends optimizers to the chain.
func (_ea *Chain )Append (optimizers ..._ga .Optimizer ){_ea ._ca =append (_ea ._ca ,optimizers ...)};

// CombineDuplicateDirectObjects combines duplicated direct objects by its data hash.
// It implements interface model.Optimizer.
type CombineDuplicateDirectObjects struct{};

// Optimize optimizes PDF objects to decrease PDF size.
func (_dcag *CompressStreams )Optimize (objects []_gc .PdfObject )(_baga []_gc .PdfObject ,_dcb error ){_baga =make ([]_gc .PdfObject ,len (objects ));copy (_baga ,objects );for _ ,_ffee :=range objects {_gde ,_efed :=_gc .GetStream (_ffee );if !_efed {continue ;
};if _ffa :=_gde .Get ("\u0046\u0069\u006c\u0074\u0065\u0072");_ffa !=nil {if _ ,_adee :=_gc .GetName (_ffa );_adee {continue ;};if _adfe ,_bcc :=_gc .GetArray (_ffa );_bcc &&_adfe .Len ()> 0{continue ;};};_cbd :=_gc .NewFlateEncoder ();var _cga []byte ;
_cga ,_dcb =_cbd .EncodeBytes (_gde .Stream );if _dcb !=nil {return _baga ,_dcb ;};_aafd :=_cbd .MakeStreamDict ();if len (_cga )+len (_aafd .Write ())< len (_gde .Stream ){_gde .Stream =_cga ;_gde .PdfObjectDictionary .Merge (_aafd );_gde .PdfObjectDictionary .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_gc .MakeInteger (int64 (len (_gde .Stream ))));
};};return _baga ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_ccbc *ObjectStreams )Optimize (objects []_gc .PdfObject )(_bgda []_gc .PdfObject ,_gfba error ){_ccdg :=&_gc .PdfObjectStreams {};_gfdgg :=make ([]_gc .PdfObject ,0,len (objects ));for _ ,_bafd :=range objects {if _gbaa ,_adbb :=_bafd .(*_gc .PdfIndirectObject );
_adbb &&_gbaa .GenerationNumber ==0{_ccdg .Append (_bafd );}else {_gfdgg =append (_gfdgg ,_bafd );};};if _ccdg .Len ()==0{return _gfdgg ,nil ;};_bgda =make ([]_gc .PdfObject ,0,len (_gfdgg )+_ccdg .Len ()+1);if _ccdg .Len ()> 1{_bgda =append (_bgda ,_ccdg );
};_bgda =append (_bgda ,_ccdg .Elements ()...);_bgda =append (_bgda ,_gfdgg ...);return _bgda ,nil ;};func _adbbf (_ffad []_gc .PdfObject ){for _decd ,_cbae :=range _ffad {switch _eaga :=_cbae .(type ){case *_gc .PdfIndirectObject :_eaga .ObjectNumber =int64 (_decd +1);
_eaga .GenerationNumber =0;case *_gc .PdfObjectStream :_eaga .ObjectNumber =int64 (_decd +1);_eaga .GenerationNumber =0;case *_gc .PdfObjectStreams :_eaga .ObjectNumber =int64 (_decd +1);_eaga .GenerationNumber =0;};};};func _aefb (_aacc []_gc .PdfObject ,_bcfa map[_gc .PdfObject ]_gc .PdfObject ){if len (_bcfa )==0{return ;
};for _bbbee ,_gga :=range _aacc {if _geab ,_agcd :=_bcfa [_gga ];_agcd {_aacc [_bbbee ]=_geab ;continue ;};_bcfa [_gga ]=_gga ;switch _geb :=_gga .(type ){case *_gc .PdfObjectArray :_fdce :=make ([]_gc .PdfObject ,_geb .Len ());copy (_fdce ,_geb .Elements ());
_aefb (_fdce ,_bcfa );for _aagg ,_feg :=range _fdce {_geb .Set (_aagg ,_feg );};case *_gc .PdfObjectStreams :_aefb (_geb .Elements (),_bcfa );case *_gc .PdfObjectStream :_bfba :=[]_gc .PdfObject {_geb .PdfObjectDictionary };_aefb (_bfba ,_bcfa );_geb .PdfObjectDictionary =_bfba [0].(*_gc .PdfObjectDictionary );
case *_gc .PdfObjectDictionary :_accc :=_geb .Keys ();_fdbfd :=make ([]_gc .PdfObject ,len (_accc ));for _abce ,_adfa :=range _accc {_fdbfd [_abce ]=_geb .Get (_adfa );};_aefb (_fdbfd ,_bcfa );for _gdfc ,_aaega :=range _accc {_geb .Set (_aaega ,_fdbfd [_gdfc ]);
};case *_gc .PdfIndirectObject :_edcf :=[]_gc .PdfObject {_geb .PdfObject };_aefb (_edcf ,_bcfa );_geb .PdfObject =_edcf [0];};};};func _ec (_ebg *_ed .ContentStreamOperations )*_ed .ContentStreamOperations {if _ebg ==nil {return nil ;};_ce :=_ed .ContentStreamOperations {};
for _ ,_gg :=range *_ebg {switch _gg .Operand {case "\u0042\u0044\u0043","\u0042\u004d\u0043","\u0045\u004d\u0043":continue ;case "\u0054\u006d":if len (_gg .Params )==6{if _cg ,_ag :=_gc .GetNumbersAsFloat (_gg .Params );_ag ==nil {if _cg [0]==1&&_cg [1]==0&&_cg [2]==0&&_cg [3]==1{_gg =&_ed .ContentStreamOperation {Params :[]_gc .PdfObject {_gg .Params [4],_gg .Params [5]},Operand :"\u0054\u0064"};
};};};};_ce =append (_ce ,_gg );};return &_ce ;};type imageInfo struct{BitsPerComponent int ;ColorComponents int ;Width int ;Height int ;Stream *_gc .PdfObjectStream ;PPI float64 ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_gfbe *CombineIdenticalIndirectObjects )Optimize (objects []_gc .PdfObject )(_gag []_gc .PdfObject ,_eebc error ){_adbbf (objects );_dcda :=make (map[_gc .PdfObject ]_gc .PdfObject );_cggg :=make (map[_gc .PdfObject ]struct{});_gbce :=make (map[string ][]*_gc .PdfIndirectObject );
for _ ,_feef :=range objects {_acd ,_baf :=_feef .(*_gc .PdfIndirectObject );if !_baf {continue ;};if _bbac ,_bdd :=_acd .PdfObject .(*_gc .PdfObjectDictionary );_bdd {if _bgfc ,_ffbc :=_bbac .Get ("\u0054\u0079\u0070\u0065").(*_gc .PdfObjectName );_ffbc &&*_bgfc =="\u0050\u0061\u0067\u0065"{continue ;
};if _cdad :=_bbac .Keys ();len (_cdad )==0{continue ;};_gca :=_fb .New ();_gca .Write (_bbac .Write ());_eeeg :=string (_gca .Sum (nil ));_gbce [_eeeg ]=append (_gbce [_eeeg ],_acd );};};for _ ,_cagf :=range _gbce {if len (_cagf )< 2{continue ;};_eabf :=_cagf [0];
for _defe :=1;_defe < len (_cagf );_defe ++{_acfef :=_cagf [_defe ];_dcda [_acfef ]=_eabf ;_cggg [_acfef ]=struct{}{};};};_gag =make ([]_gc .PdfObject ,0,len (objects )-len (_cggg ));for _ ,_faa :=range objects {if _ ,_dae :=_cggg [_faa ];_dae {continue ;
};_gag =append (_gag ,_faa );};_aefb (_gag ,_dcda );return _gag ,nil ;};func _cgg (_gfdg _gc .PdfObject ,_gfa map[_gc .PdfObject ]struct{})error {if _ddcf ,_aca :=_gfdg .(*_gc .PdfIndirectObject );_aca {_gfa [_gfdg ]=struct{}{};_bae :=_cgg (_ddcf .PdfObject ,_gfa );
if _bae !=nil {return _bae ;};return nil ;};if _agcg ,_bgaf :=_gfdg .(*_gc .PdfObjectStream );_bgaf {_gfa [_agcg ]=struct{}{};_egbe :=_cgg (_agcg .PdfObjectDictionary ,_gfa );if _egbe !=nil {return _egbe ;};return nil ;};if _ecb ,_bad :=_gfdg .(*_gc .PdfObjectDictionary );
_bad {for _ ,_eea :=range _ecb .Keys (){_adg :=_ecb .Get (_eea );_ =_adg ;if _acf ,_gef :=_adg .(*_gc .PdfObjectReference );_gef {_adg =_acf .Resolve ();_ecb .Set (_eea ,_adg );};if _eea !="\u0050\u0061\u0072\u0065\u006e\u0074"{if _bab :=_cgg (_adg ,_gfa );
_bab !=nil {return _bab ;};};};return nil ;};if _deb ,_fdc :=_gfdg .(*_gc .PdfObjectArray );_fdc {if _deb ==nil {return _ebe .New ("\u0061\u0072\u0072a\u0079\u0020\u0069\u0073\u0020\u006e\u0069\u006c");};for _fdbg ,_ecbe :=range _deb .Elements (){if _gfbf ,_dfd :=_ecbe .(*_gc .PdfObjectReference );
_dfd {_ecbe =_gfbf .Resolve ();_deb .Set (_fdbg ,_ecbe );};if _gdbc :=_cgg (_ecbe ,_gfa );_gdbc !=nil {return _gdbc ;};};return nil ;};return nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_fbb *CombineDuplicateDirectObjects )Optimize (objects []_gc .PdfObject )(_bfd []_gc .PdfObject ,_geff error ){_adbbf (objects );_daa :=make (map[string ][]*_gc .PdfObjectDictionary );var _fdaa func (_ggg *_gc .PdfObjectDictionary );_fdaa =func (_gfaa *_gc .PdfObjectDictionary ){for _ ,_bba :=range _gfaa .Keys (){_dfg :=_gfaa .Get (_bba );
if _ggf ,_ceg :=_dfg .(*_gc .PdfObjectDictionary );_ceg {if _cbb :=_ggf .Keys ();len (_cbb )==0{continue ;};_cfd :=_fb .New ();_cfd .Write (_ggf .Write ());_dfad :=string (_cfd .Sum (nil ));_daa [_dfad ]=append (_daa [_dfad ],_ggf );_fdaa (_ggf );};};};
for _ ,_bfcf :=range objects {_cdafb ,_cab :=_bfcf .(*_gc .PdfIndirectObject );if !_cab {continue ;};if _fcff ,_cdfc :=_cdafb .PdfObject .(*_gc .PdfObjectDictionary );_cdfc {_fdaa (_fcff );};};_feag :=make ([]_gc .PdfObject ,0,len (_daa ));_feeg :=make (map[_gc .PdfObject ]_gc .PdfObject );
for _ ,_gfe :=range _daa {if len (_gfe )< 2{continue ;};_ede :=_gc .MakeDict ();_ede .Merge (_gfe [0]);_dbac :=_gc .MakeIndirectObject (_ede );_feag =append (_feag ,_dbac );for _fgdg :=0;_fgdg < len (_gfe );_fgdg ++{_ggc :=_gfe [_fgdg ];_feeg [_ggc ]=_dbac ;
};};_bfd =make ([]_gc .PdfObject ,len (objects ));copy (_bfd ,objects );_bfd =append (_feag ,_bfd ...);_aefb (_bfd ,_feeg );return _bfd ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_dege *ImagePPI )Optimize (objects []_gc .PdfObject )(_deac []_gc .PdfObject ,_ccda error ){if _dege .ImageUpperPPI <=0{return objects ,nil ;};_acac :=_aeff (objects );if len (_acac )==0{return objects ,nil ;};_cca :=make (map[_gc .PdfObject ]struct{});
for _ ,_gdbcf :=range _acac {_ccef :=_gdbcf .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b");_cca [_ccef ]=struct{}{};};_efeff :=make (map[*_gc .PdfObjectStream ]*imageInfo );for _ ,_cfab :=range _acac {_efeff [_cfab .Stream ]=_cfab ;};var _bdfbe *_gc .PdfObjectDictionary ;
for _ ,_dec :=range objects {if _aegf ,_gbba :=_gc .GetDict (_dec );_bdfbe ==nil &&_gbba {if _ccgb ,_gff :=_gc .GetName (_aegf .Get ("\u0054\u0079\u0070\u0065"));_gff &&*_ccgb =="\u0043a\u0074\u0061\u006c\u006f\u0067"{_bdfbe =_aegf ;};};};if _bdfbe ==nil {return objects ,nil ;
};_fcc ,_cdg :=_gc .GetDict (_bdfbe .Get ("\u0050\u0061\u0067e\u0073"));if !_cdg {return objects ,nil ;};_gea ,_edca :=_gc .GetArray (_fcc .Get ("\u004b\u0069\u0064\u0073"));if !_edca {return objects ,nil ;};for _ ,_gaaa :=range _gea .Elements (){_efbc :=make (map[string ]*imageInfo );
_cecg ,_ccb :=_gc .GetDict (_gaaa );if !_ccb {continue ;};_fgga ,_ :=_eccd (_cecg .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));if len (_fgga )==0{continue ;};_dgg ,_afe :=_gc .GetDict (_cecg .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));
if !_afe {continue ;};_acbb ,_cdda :=_ga .NewPdfPageResourcesFromDict (_dgg );if _cdda !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020\u0070\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0072\u0065\u0073\u006f\u0075\u0072\u0063\u0065\u0073\u0020-\u0020\u0069\u0067\u006e\u006fr\u0069\u006eg\u003a\u0020\u0025\u0076",_cdda );
continue ;};_fcfb ,_cafb :=_gc .GetDict (_dgg .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));if !_cafb {continue ;};_gdf :=_fcfb .Keys ();for _ ,_gbf :=range _gdf {if _ddcb ,_bgc :=_gc .GetStream (_fcfb .Get (_gbf ));_bgc {if _ege ,_cgbab :=_efeff [_ddcb ];
_cgbab {_efbc [string (_gbf )]=_ege ;};};};_gggg :=_ed .NewContentStreamParser (_fgga );_afec ,_cdda :=_gggg .Parse ();if _cdda !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_cdda );continue ;};_efeaa :=_ed .NewContentStreamProcessor (*_afec );
_efeaa .AddHandler (_ed .HandlerConditionEnumAllOperands ,"",func (_gcee *_ed .ContentStreamOperation ,_dgb _ed .GraphicsState ,_bbfd *_ga .PdfPageResources )error {switch _gcee .Operand {case "\u0044\u006f":if len (_gcee .Params )!=1{_c .Log .Debug ("E\u0052\u0052\u004f\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020w\u0069\u0074\u0068\u0020\u006c\u0065\u006e\u0028\u0070\u0061ra\u006d\u0073\u0029 \u0021=\u0020\u0031");
return nil ;};_aaeg ,_dbca :=_gc .GetName (_gcee .Params [0]);if !_dbca {_c .Log .Debug ("\u0045\u0052\u0052O\u0052\u003a\u0020\u0049\u0067\u006e\u006f\u0072\u0069\u006e\u0067\u0020\u0044\u006f\u0020\u0077\u0069\u0074\u0068\u0020\u006e\u006f\u006e\u0020\u004e\u0061\u006d\u0065\u0020p\u0061\u0072\u0061\u006d\u0065\u0074\u0065\u0072");
return nil ;};if _fdca ,_bfda :=_efbc [string (*_aaeg )];_bfda {_badg :=_dgb .CTM .ScalingFactorX ();_egg :=_dgb .CTM .ScalingFactorY ();_gaf ,_aed :=_badg /72.0,_egg /72.0;_efg ,_bggc :=float64 (_fdca .Width )/_gaf ,float64 (_fdca .Height )/_aed ;if _gaf ==0||_aed ==0{_efg =72.0;
_bggc =72.0;};_fdca .PPI =_d .Max (_fdca .PPI ,_efg );_fdca .PPI =_d .Max (_fdca .PPI ,_bggc );};};return nil ;});_cdda =_efeaa .Process (_acbb );if _cdda !=nil {_c .Log .Debug ("E\u0052\u0052\u004f\u0052 p\u0072o\u0063\u0065\u0073\u0073\u0069n\u0067\u003a\u0020\u0025\u002b\u0076",_cdda );
continue ;};};for _ ,_gfce :=range _acac {if _ ,_cfba :=_cca [_gfce .Stream ];_cfba {continue ;};if _gfce .PPI <=_dege .ImageUpperPPI {continue ;};_ddcd ,_gagb :=_ga .NewXObjectImageFromStream (_gfce .Stream );if _gagb !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_gagb );
continue ;};var _fab imageModifications ;_fab .Scale =_dege .ImageUpperPPI /_gfce .PPI ;if _gfce .BitsPerComponent ==1&&_gfce .ColorComponents ==1{_dace :=_d .Round (_gfce .PPI /_dege .ImageUpperPPI );_egge :=_da .NextPowerOf2 (uint (_dace ));if _da .InDelta (float64 (_egge ),1/_fab .Scale ,0.3){_fab .Scale =float64 (1)/float64 (_egge );
};if _ ,_fdac :=_ddcd .Filter .(*_gc .JBIG2Encoder );!_fdac {_fab .Encoding =_gc .NewJBIG2Encoder ();};};if _gagb =_gdbg (_ddcd ,_fab );_gagb !=nil {_c .Log .Debug ("\u0045\u0072\u0072\u006f\u0072 \u0073\u0063\u0061\u006c\u0065\u0020\u0069\u006d\u0061\u0067\u0065\u0020\u006be\u0065\u0070\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u0069\u006d\u0061\u0067\u0065\u003a\u0020\u0025\u0073",_gagb );
continue ;};_fab .Encoding =nil ;if _egc ,_dcf :=_gc .GetStream (_gfce .Stream .PdfObjectDictionary .Get ("\u0053\u004d\u0061s\u006b"));_dcf {_dbcg ,_fge :=_ga .NewXObjectImageFromStream (_egc );if _fge !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fge );
continue ;};if _fge =_gdbg (_dbcg ,_fab );_fge !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_fge );continue ;};};};return objects ,nil ;};type objectStructure struct{_acg *_gc .PdfObjectDictionary ;_ebda *_gc .PdfObjectDictionary ;
_cfe []*_gc .PdfIndirectObject ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_ab *Chain )Optimize (objects []_gc .PdfObject )(_b []_gc .PdfObject ,_ge error ){_af :=objects ;for _ ,_fbd :=range _ab ._ca {_eac ,_be :=_fbd .Optimize (_af );if _be !=nil {_c .Log .Debug ("\u0045\u0052\u0052OR\u0020\u004f\u0070\u0074\u0069\u006d\u0069\u007a\u0061\u0074\u0069\u006f\u006e\u003a\u0020\u0025\u002b\u0076",_be );
continue ;};_af =_eac ;};return _af ,nil ;};

// ObjectStreams groups PDF objects to object streams.
// It implements interface model.Optimizer.
type ObjectStreams struct{};

// CombineIdenticalIndirectObjects combines identical indirect objects.
// It implements interface model.Optimizer.
type CombineIdenticalIndirectObjects struct{};

// CleanUnusedResources represents an optimizer used to clean unused resources.
type CleanUnusedResources struct{};type content struct{_aag string ;_dee *_ga .PdfPageResources ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_eag *CleanFonts )Optimize (objects []_gc .PdfObject )(_fa []_gc .PdfObject ,_gfb error ){var _afd map[*_gc .PdfObjectStream ]struct{};if _eag .Subset {var _bgb error ;_afd ,_bgb =_aeg (objects );if _bgb !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004fR\u003a\u0020\u0046\u0061\u0069\u006c\u0065\u0064\u0020\u0073u\u0062s\u0065\u0074\u0074\u0069\u006e\u0067\u003a \u0025\u0076",_bgb );
return nil ,_bgb ;};};for _ ,_dff :=range objects {_aegc ,_eae :=_gc .GetStream (_dff );if !_eae {continue ;};if _ ,_bgd :=_afd [_aegc ];_bgd {continue ;};_effe ,_dac :=_gc .NewEncoderFromStream (_aegc );if _dac !=nil {_c .Log .Debug ("\u0045\u0052RO\u0052\u0020\u0067e\u0074\u0074\u0069\u006eg e\u006eco\u0064\u0065\u0072\u003a\u0020\u0025\u0076 -\u0020\u0069\u0067\u006e\u006f\u0072\u0069n\u0067",_dac );
continue ;};_cdb ,_dac :=_effe .DecodeStream (_aegc );if _dac !=nil {_c .Log .Debug ("\u0044\u0065\u0063\u006f\u0064\u0069\u006e\u0067\u0020\u0065r\u0072\u006f\u0072\u0020\u003a\u0020\u0025v\u0020\u002d\u0020\u0069\u0067\u006e\u006f\u0072\u0069\u006e\u0067",_dac );
continue ;};if len (_cdb )< 4{continue ;};_aeb :=string (_cdb [:4]);if _aeb =="\u004f\u0054\u0054\u004f"{continue ;};if _aeb !="\u0000\u0001\u0000\u0000"&&_aeb !="\u0074\u0072\u0075\u0065"{continue ;};_agc ,_dac :=_dd .Parse (_gf .NewReader (_cdb ));if _dac !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020P\u0061\u0072\u0073\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_dac );
continue ;};_dac =_agc .Optimize ();if _dac !=nil {_c .Log .Debug ("\u0045\u0052RO\u0052\u0020\u004fp\u0074\u0069\u006d\u0069zin\u0067 f\u006f\u006e\u0074\u003a\u0020\u0025\u0076 -\u0020\u0073\u006b\u0069\u0070\u0070\u0069n\u0067",_dac );continue ;};var _bef _gf .Buffer ;
_dac =_agc .Write (&_bef );if _dac !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u0020W\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076\u0020\u002d\u0020\u0069\u0067\u006eo\u0072\u0069\u006e\u0067",_dac );continue ;
};if _bef .Len ()> len (_cdb ){_c .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
continue ;};_dfb ,_dac :=_gc .MakeStream (_bef .Bytes (),_gc .NewFlateEncoder ());if _dac !=nil {continue ;};*_aegc =*_dfb ;_aegc .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_gc .MakeInteger (int64 (_bef .Len ())));};return objects ,nil ;};func _daf (_bb *_gc .PdfObjectStream )error {_cgb ,_df :=_gc .DecodeStream (_bb );
if _df !=nil {return _df ;};_gae :=_ed .NewContentStreamParser (string (_cgb ));_egb ,_df :=_gae .Parse ();if _df !=nil {return _df ;};_egb =_ec (_egb );_ff :=_egb .Bytes ();if len (_ff )>=len (_cgb ){return nil ;};_fe ,_df :=_gc .MakeStream (_egb .Bytes (),_gc .NewFlateEncoder ());
if _df !=nil {return _df ;};_bb .Stream =_fe .Stream ;_bb .Merge (_fe .PdfObjectDictionary );return nil ;};

// Image optimizes images by rewrite images into JPEG format with quality equals to ImageQuality.
// TODO(a5i): Add support for inline images.
// It implements interface model.Optimizer.
type Image struct{ImageQuality int ;};func _aeff (_dcg []_gc .PdfObject )[]*imageInfo {_bdg :=_gc .PdfObjectName ("\u0053u\u0062\u0074\u0079\u0070\u0065");_agb :=make (map[*_gc .PdfObjectStream ]struct{});var _gaba []*imageInfo ;for _ ,_gaa :=range _dcg {_ffg ,_fecb :=_gc .GetStream (_gaa );
if !_fecb {continue ;};if _ ,_cbdf :=_agb [_ffg ];_cbdf {continue ;};_agb [_ffg ]=struct{}{};_cdbd :=_ffg .PdfObjectDictionary .Get (_bdg );_gabf ,_fecb :=_gc .GetName (_cdbd );if !_fecb ||string (*_gabf )!="\u0049\u006d\u0061g\u0065"{continue ;};_deg :=&imageInfo {Stream :_ffg ,BitsPerComponent :8};
if _cgcg ,_gfca :=_gc .GetIntVal (_ffg .Get ("\u0042\u0069t\u0073\u0050\u0065r\u0043\u006f\u006d\u0070\u006f\u006e\u0065\u006e\u0074"));_gfca {_deg .BitsPerComponent =_cgcg ;};if _abf ,_ccg :=_gc .GetIntVal (_ffg .Get ("\u0057\u0069\u0064t\u0068"));_ccg {_deg .Width =_abf ;
};if _deae ,_eabd :=_gc .GetIntVal (_ffg .Get ("\u0048\u0065\u0069\u0067\u0068\u0074"));_eabd {_deg .Height =_deae ;};_deagc ,_gbd :=_ga .NewPdfColorspaceFromPdfObject (_ffg .Get ("\u0043\u006f\u006c\u006f\u0072\u0053\u0070\u0061\u0063\u0065"));if _gbd !=nil {_c .Log .Debug ("\u0045R\u0052\u004f\u0052\u003a\u0020\u0025v",_gbd );
continue ;};if _deagc ==nil {_gec ,_ggec :=_gc .GetName (_ffg .Get ("\u0046\u0069\u006c\u0074\u0065\u0072"));if _ggec {switch _gec .String (){case "\u0043\u0043\u0049\u0054\u0054\u0046\u0061\u0078\u0044e\u0063\u006f\u0064\u0065","J\u0042\u0049\u0047\u0032\u0044\u0065\u0063\u006f\u0064\u0065":_deagc =_ga .NewPdfColorspaceDeviceGray ();
_deg .BitsPerComponent =1;};};};switch _bggd :=_deagc .(type ){case *_ga .PdfColorspaceDeviceRGB :_deg .ColorComponents =3;case *_ga .PdfColorspaceDeviceGray :_deg .ColorComponents =1;default:_c .Log .Debug ("\u004f\u0070\u0074\u0069\u006d\u0069\u007aa\u0074\u0069\u006fn\u0020\u0069\u0073 \u006e\u006ft\u0020\u0073\u0075\u0070\u0070\u006fr\u0074ed\u0020\u0066\u006f\u0072\u0020\u0063\u006f\u006c\u006f\u0072\u0020\u0073\u0070\u0061\u0063\u0065\u0020\u0025\u0054\u0020\u002d\u0020\u0073\u006b\u0069\u0070",_bggd );
continue ;};_gaba =append (_gaba ,_deg );};return _gaba ;};

// CleanFonts cleans up embedded fonts, reducing font sizes.
type CleanFonts struct{

// Subset embedded fonts if encountered (if true).
// Otherwise attempts to reduce the font program.
Subset bool ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_bg *CleanContentstream )Optimize (objects []_gc .PdfObject )(_edc []_gc .PdfObject ,_aa error ){_ac :=map[*_gc .PdfObjectStream ]struct{}{};var _abe []*_gc .PdfObjectStream ;_ef :=func (_ad *_gc .PdfObjectStream ){if _ ,_ba :=_ac [_ad ];!_ba {_ac [_ad ]=struct{}{};
_abe =append (_abe ,_ad );};};_gbb :=map[_gc .PdfObject ]bool {};_de :=map[_gc .PdfObject ]bool {};for _ ,_ecf :=range objects {switch _ecd :=_ecf .(type ){case *_gc .PdfIndirectObject :switch _cc :=_ecd .PdfObject .(type ){case *_gc .PdfObjectDictionary :if _afc ,_ada :=_gc .GetName (_cc .Get ("\u0054\u0079\u0070\u0065"));
!_ada ||_afc .String ()!="\u0050\u0061\u0067\u0065"{continue ;};if _ffb ,_fbf :=_gc .GetStream (_cc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));_fbf {_ef (_ffb );}else if _def ,_ccf :=_gc .GetArray (_cc .Get ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073"));
_ccf {var _ae []*_gc .PdfObjectStream ;for _ ,_gbc :=range _def .Elements (){if _cb ,_aaa :=_gc .GetStream (_gbc );_aaa {_ae =append (_ae ,_cb );};};if len (_ae )> 0{var _geg _gf .Buffer ;for _ ,_cf :=range _ae {if _efb ,_ecfa :=_gc .DecodeStream (_cf );
_ecfa ==nil {_geg .Write (_efb );};_gbb [_cf ]=true ;};_cfa ,_cea :=_gc .MakeStream (_geg .Bytes (),_gc .NewFlateEncoder ());if _cea !=nil {return nil ,_cea ;};_de [_cfa ]=true ;_cc .Set ("\u0043\u006f\u006e\u0074\u0065\u006e\u0074\u0073",_cfa );_ef (_cfa );
};};};case *_gc .PdfObjectStream :if _bac ,_cee :=_gc .GetName (_ecd .Get ("\u0054\u0079\u0070\u0065"));!_cee ||_bac .String ()!="\u0058O\u0062\u006a\u0065\u0063\u0074"{continue ;};if _ebb ,_cef :=_gc .GetName (_ecd .Get ("\u0053u\u0062\u0074\u0079\u0070\u0065"));
!_cef ||_ebb .String ()!="\u0046\u006f\u0072\u006d"{continue ;};_ef (_ecd );};};for _ ,_fbg :=range _abe {_aa =_daf (_fbg );if _aa !=nil {return nil ,_aa ;};};_edc =nil ;for _ ,_fea :=range objects {if _gbb [_fea ]{continue ;};_edc =append (_edc ,_fea );
};for _gac :=range _de {_edc =append (_edc ,_gac );};return _edc ,nil ;};

// CleanContentstream cleans up redundant operands in content streams, including Page and XObject Form
// contents. This process includes:
// 1. Marked content operators are removed.
// 2. Some operands are simplified (shorter form).
// TODO: Add more reduction methods and improving the methods for identifying unnecessary operands.
type CleanContentstream struct{};func _gba (_fdbf []_gc .PdfObject )(map[_gc .PdfObject ]struct{},error ){_cag :=_dbb (_fdbf );_bagb :=_cag ._cfe ;_cfc :=make (map[_gc .PdfObject ]struct{});_ddc :=_acc (_bagb );for _ ,_fcf :=range _bagb {_eacc ,_eaa :=_gc .GetDict (_fcf .PdfObject );
if !_eaa {continue ;};_ffd ,_eaa :=_gc .GetDict (_eacc .Get ("\u0052e\u0073\u006f\u0075\u0072\u0063\u0065s"));if !_eaa {continue ;};_gdcc :=_ddc ["\u0058O\u0062\u006a\u0065\u0063\u0074"];_fga ,_eaa :=_gc .GetDict (_ffd .Get ("\u0058O\u0062\u006a\u0065\u0063\u0074"));
if _eaa {_daca :=_cdaf (_fga );for _ ,_cefb :=range _daca {if _add (_cefb ,_gdcc ){continue ;};_dcc :=*_gc .MakeName (_cefb );_fgc :=_fga .Get (_dcc );_cfc [_fgc ]=struct{}{};_fga .Remove (_dcc );_efd :=_cgg (_fgc ,_cfc );if _efd !=nil {_c .Log .Debug ("\u0066\u0061\u0069\u006ce\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065r\u0073e\u0020\u006f\u0062\u006a\u0065\u0063\u0074 \u0025\u0076",_fgc );
};};};_efef ,_eaa :=_gc .GetDict (_ffd .Get ("\u0046\u006f\u006e\u0074"));_fgf :=_ddc ["\u0046\u006f\u006e\u0074"];if _eaa {_bgee :=_cdaf (_efef );for _ ,_abc :=range _bgee {if _add (_abc ,_fgf ){continue ;};_aagc :=*_gc .MakeName (_abc );_agf :=_efef .Get (_aagc );
_cfc [_agf ]=struct{}{};_efef .Remove (_aagc );_gbe :=_cgg (_agf ,_cfc );if _gbe !=nil {_c .Log .Debug ("\u0046\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_agf );
};};};_cdf ,_eaa :=_gc .GetDict (_ffd .Get ("\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"));if _eaa {_bdc :=_cdaf (_cdf );_afcg :=_ddc ["\u0045x\u0074\u0047\u0053\u0074\u0061\u0074e"];for _ ,_fed :=range _bdc {if _add (_fed ,_afcg ){continue ;};_fce :=*_gc .MakeName (_fed );
_agcf :=_cdf .Get (_fce );_cfc [_agcf ]=struct{}{};_cdf .Remove (_fce );_ged :=_cgg (_agcf ,_cfc );if _ged !=nil {_c .Log .Debug ("\u0066\u0061i\u006c\u0065\u0064\u0020\u0074\u006f\u0020\u0074\u0072\u0061\u0076\u0065\u0072\u0073\u0065\u0020\u006f\u0062\u006a\u0065\u0063\u0074 %\u0076\u000a",_agcf );
};};};};return _cfc ,nil ;};

// Options describes PDF optimization parameters.
type Options struct{CombineDuplicateStreams bool ;CombineDuplicateDirectObjects bool ;ImageUpperPPI float64 ;ImageQuality int ;UseObjectStreams bool ;CombineIdenticalIndirectObjects bool ;CompressStreams bool ;CleanFonts bool ;SubsetFonts bool ;CleanContentstream bool ;
CleanUnusedResources bool ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_cbbd *Image )Optimize (objects []_gc .PdfObject )(_cec []_gc .PdfObject ,_eega error ){if _cbbd .ImageQuality <=0{return objects ,nil ;};_faag :=_aeff (objects );if len (_faag )==0{return objects ,nil ;};_edab :=make (map[_gc .PdfObject ]_gc .PdfObject );
_cddb :=make (map[_gc .PdfObject ]struct{});for _ ,_dfeb :=range _faag {_fcb :=_dfeb .Stream .Get ("\u0053\u004d\u0061s\u006b");_cddb [_fcb ]=struct{}{};};for _geea ,_daab :=range _faag {_beff :=_daab .Stream ;if _ ,_fddg :=_cddb [_beff ];_fddg {continue ;
};_bgec ,_efbf :=_ga .NewXObjectImageFromStream (_beff );if _efbf !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_efbf );continue ;};switch _bgec .Filter .(type ){case *_gc .JBIG2Encoder :continue ;case *_gc .CCITTFaxEncoder :continue ;
};_ffga ,_efbf :=_bgec .ToImage ();if _efbf !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_efbf );continue ;};_fgff :=_gc .NewDCTEncoder ();_fgff .ColorComponents =_ffga .ColorComponents ;_fgff .Quality =_cbbd .ImageQuality ;
_fgff .BitsPerComponent =_daab .BitsPerComponent ;_fgff .Width =_daab .Width ;_fgff .Height =_daab .Height ;_fdec ,_efbf :=_fgff .EncodeBytes (_ffga .Data );if _efbf !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_efbf );
continue ;};var _gbbb _gc .StreamEncoder ;_gbbb =_fgff ;{_bdee :=_gc .NewFlateEncoder ();_gcec :=_gc .NewMultiEncoder ();_gcec .AddEncoder (_bdee );_gcec .AddEncoder (_fgff );_aff ,_bdfb :=_gcec .EncodeBytes (_ffga .Data );if _bdfb !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004f\u0052\u003a\u0020\u0025\u002b\u0076",_bdfb );
continue ;};if len (_aff )< len (_fdec ){_c .Log .Trace ("\u004d\u0075\u006c\u0074\u0069\u0020\u0065\u006e\u0063\u0020\u0069\u006d\u0070\u0072\u006f\u0076\u0065\u0073\u003a\u0020\u0025\u0064\u0020\u0074o\u0020\u0025\u0064\u0020\u0028o\u0072\u0069g\u0020\u0025\u0064\u0029",len (_fdec ),len (_aff ),len (_beff .Stream ));
_fdec =_aff ;_gbbb =_gcec ;};};_eefc :=len (_beff .Stream );if _eefc < len (_fdec ){continue ;};_bdef :=&_gc .PdfObjectStream {Stream :_fdec };_bdef .PdfObjectReference =_beff .PdfObjectReference ;_bdef .PdfObjectDictionary =_gc .MakeDict ();_bdef .Merge (_beff .PdfObjectDictionary );
_bdef .Merge (_gbbb .MakeStreamDict ());_bdef .Set ("\u004c\u0065\u006e\u0067\u0074\u0068",_gc .MakeInteger (int64 (len (_fdec ))));_edab [_beff ]=_bdef ;_faag [_geea ].Stream =_bdef ;};_cec =make ([]_gc .PdfObject ,len (objects ));copy (_cec ,objects );
_aefb (_cec ,_edab );return _cec ,nil ;};

// Optimize optimizes PDF objects to decrease PDF size.
func (_fcac *CombineDuplicateStreams )Optimize (objects []_gc .PdfObject )(_acfe []_gc .PdfObject ,_fde error ){_gfec :=make (map[_gc .PdfObject ]_gc .PdfObject );_fcg :=make (map[_gc .PdfObject ]struct{});_fbff :=make (map[string ][]*_gc .PdfObjectStream );
for _ ,_bgdd :=range objects {if _caec ,_bacc :=_bgdd .(*_gc .PdfObjectStream );_bacc {_bdfc :=_fb .New ();_bdfc .Write (_caec .Stream );_bdfc .Write (_caec .PdfObjectDictionary .Write ());_dfe :=string (_bdfc .Sum (nil ));_fbff [_dfe ]=append (_fbff [_dfe ],_caec );
};};for _ ,_gggc :=range _fbff {if len (_gggc )< 2{continue ;};_ecga :=_gggc [0];for _dfab :=1;_dfab < len (_gggc );_dfab ++{_ggcb :=_gggc [_dfab ];_gfec [_ggcb ]=_ecga ;_fcg [_ggcb ]=struct{}{};};};_acfe =make ([]_gc .PdfObject ,0,len (objects )-len (_fcg ));
for _ ,_cdd :=range objects {if _ ,_dfea :=_fcg [_cdd ];_dfea {continue ;};_acfe =append (_acfe ,_cdd );};_aefb (_acfe ,_gfec );return _acfe ,nil ;};

// Chain allows to use sequence of optimizers.
// It implements interface model.Optimizer.
type Chain struct{_ca []_ga .Optimizer };func _aae (_dde *_gc .PdfObjectStream ,_bfe []rune ,_bd []_dd .GlyphIndex )error {_dde ,_gfc :=_gc .GetStream (_dde );if !_gfc {_c .Log .Debug ("\u0045\u006d\u0062\u0065\u0064\u0064\u0065\u0064\u0020\u0066\u006f\u006e\u0074\u0020\u006f\u0062\u006a\u0065c\u0074\u0020\u006e\u006f\u0074\u0020\u0066o\u0075\u006e\u0064\u0020\u002d\u002d\u0020\u0041\u0042\u004f\u0052T\u0020\u0073\u0075\u0062\u0073\u0065\u0074\u0074\u0069\u006e\u0067");
return _ebe .New ("\u0066\u006f\u006e\u0074fi\u006c\u0065\u0032\u0020\u006e\u006f\u0074\u0020\u0066\u006f\u0075\u006e\u0064");};_ecfc ,_dce :=_gc .DecodeStream (_dde );if _dce !=nil {_c .Log .Debug ("\u0044\u0065c\u006f\u0064\u0065 \u0065\u0072\u0072\u006f\u0072\u003a\u0020\u0025\u0076",_dce );
return _dce ;};_db ,_dce :=_dd .Parse (_gf .NewReader (_ecfc ));if _dce !=nil {_c .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0070\u0061\u0072\u0073\u0069n\u0067\u0020\u0025\u0064\u0020\u0062\u0079\u0074\u0065\u0020f\u006f\u006e\u0074",len (_dde .Stream ));
return _dce ;};_eba :=_bd ;if len (_bfe )> 0{_dafb :=_db .LookupRunes (_bfe );_eba =append (_eba ,_dafb ...);};_db ,_dce =_db .SubsetKeepIndices (_eba );if _dce !=nil {_c .Log .Debug ("\u0045R\u0052\u004f\u0052\u0020s\u0075\u0062\u0073\u0065\u0074t\u0069n\u0067 \u0066\u006f\u006e\u0074\u003a\u0020\u0025v",_dce );
return _dce ;};var _fdb _gf .Buffer ;_dce =_db .Write (&_fdb );if _dce !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_dce );return _dce ;};if _fdb .Len ()> len (_ecfc ){_c .Log .Debug ("\u0052\u0065-\u0077\u0072\u0069\u0074\u0074\u0065\u006e\u0020\u0066\u006f\u006e\u0074\u0020\u0069\u0073\u0020\u006c\u0061\u0072\u0067\u0065\u0072\u0020\u0074\u0068\u0061\u006e\u0020\u006f\u0072\u0069\u0067\u0069\u006e\u0061\u006c\u0020\u002d\u0020\u0073\u006b\u0069\u0070");
return nil ;};_cda ,_dce :=_gc .MakeStream (_fdb .Bytes (),_gc .NewFlateEncoder ());if _dce !=nil {_c .Log .Debug ("\u0045\u0052\u0052\u004fR \u0057\u0072\u0069\u0074\u0069\u006e\u0067\u0020\u0066\u006f\u006e\u0074\u003a\u0020%\u0076",_dce );return _dce ;
};*_dde =*_cda ;_dde .Set ("\u004ce\u006e\u0067\u0074\u0068\u0031",_gc .MakeInteger (int64 (_fdb .Len ())));return nil ;};func _eccd (_gdgf _gc .PdfObject )(_gfgc string ,_efdb []_gc .PdfObject ){var _cdfcc _gf .Buffer ;switch _gcab :=_gdgf .(type ){case *_gc .PdfIndirectObject :_efdb =append (_efdb ,_gcab );
_gdgf =_gcab .PdfObject ;};switch _fbab :=_gdgf .(type ){case *_gc .PdfObjectStream :if _cada ,_bbd :=_gc .DecodeStream (_fbab );_bbd ==nil {_cdfcc .Write (_cada );_efdb =append (_efdb ,_fbab );};case *_gc .PdfObjectArray :for _ ,_edee :=range _fbab .Elements (){switch _daeg :=_edee .(type ){case *_gc .PdfObjectStream :if _gdfcf ,_fbdf :=_gc .DecodeStream (_daeg );
_fbdf ==nil {_cdfcc .Write (_gdfcf );_efdb =append (_efdb ,_daeg );};};};};return _cdfcc .String (),_efdb ;};