//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sigutil ;import (_c "bytes";_b "crypto";_db "crypto/x509";_bf "encoding/asn1";_e "encoding/pem";_a "errors";_ge "fmt";_ff "github.com/unidoc/timestamp";_fa "github.com/unidoc/unipdf/v4/common";_ba "golang.org/x/crypto/ocsp";_f "io";_cg "net/http";
_g "time";);

// NewCertClient returns a new certificate client.
func NewCertClient ()*CertClient {return &CertClient {HTTPClient :_gfg ()}};

// NewOCSPClient returns a new OCSP client.
func NewOCSPClient ()*OCSPClient {return &OCSPClient {HTTPClient :_gfg (),Hash :_b .SHA1 }};

// GetIssuer retrieves the issuer of the provided certificate.
func (_geg *CertClient )GetIssuer (cert *_db .Certificate )(*_db .Certificate ,error ){for _ ,_cd :=range cert .IssuingCertificateURL {_gg ,_feb :=_geg .Get (_cd );if _feb !=nil {_fa .Log .Debug ("\u0057\u0041\u0052\u004e\u003a\u0020\u0063\u006f\u0075\u006c\u0064\u0020\u006e\u006f\u0074 \u0064\u006f\u0077\u006e\u006c\u006f\u0061\u0064\u0020\u0069\u0073\u0073\u0075e\u0072\u0020\u0066\u006f\u0072\u0020\u0063\u0065\u0072\u0074\u0069\u0066ic\u0061\u0074\u0065\u0020\u0025\u0076\u003a\u0020\u0025\u0076",cert .Subject .CommonName ,_feb );
continue ;};return _gg ,nil ;};return nil ,_ge .Errorf ("\u0069\u0073\u0073\u0075e\u0072\u0020\u0063\u0065\u0072\u0074\u0069\u0066\u0069\u0063a\u0074e\u0020\u006e\u006f\u0074\u0020\u0066\u006fu\u006e\u0064");};

// IsCA returns true if the provided certificate appears to be a CA certificate.
func (_da *CertClient )IsCA (cert *_db .Certificate )bool {return cert .IsCA &&_c .Equal (cert .RawIssuer ,cert .RawSubject );};

// Get retrieves the certificate at the specified URL.
func (_ef *CertClient )Get (url string )(*_db .Certificate ,error ){if _ef .HTTPClient ==nil {_ef .HTTPClient =_gfg ();};_ae ,_eg :=_ef .HTTPClient .Get (url );if _eg !=nil {return nil ,_eg ;};defer _ae .Body .Close ();_ce ,_eg :=_f .ReadAll (_ae .Body );
if _eg !=nil {return nil ,_eg ;};if _cb ,_ :=_e .Decode (_ce );_cb !=nil {_ce =_cb .Bytes ;};_ab ,_eg :=_db .ParseCertificate (_ce );if _eg !=nil {return nil ,_eg ;};return _ab ,nil ;};

// OCSPClient represents a OCSP (Online Certificate Status Protocol) client.
// It is used to request revocation data from OCSP servers.
type OCSPClient struct{

// HTTPClient is the HTTP client used to make OCSP requests.
// By default, an HTTP client with a 5 second timeout per request is used.
HTTPClient *_cg .Client ;

// Hash is the hash function  used when constructing the OCSP
// requests. If zero, SHA-1 will be used.
Hash _b .Hash ;};

// MakeRequest makes a OCSP request to the specified server and returns
// the parsed and raw responses. If a server URL is not provided, it is
// extracted from the certificate.
func (_gd *OCSPClient )MakeRequest (serverURL string ,cert ,issuer *_db .Certificate )(*_ba .Response ,[]byte ,error ){if _gd .HTTPClient ==nil {_gd .HTTPClient =_gfg ();};if serverURL ==""{if len (cert .OCSPServer )==0{return nil ,nil ,_a .New ("\u0063e\u0072\u0074i\u0066\u0069\u0063a\u0074\u0065\u0020\u0064\u006f\u0065\u0073 \u006e\u006f\u0074\u0020\u0073\u0070e\u0063\u0069\u0066\u0079\u0020\u0061\u006e\u0079\u0020\u004f\u0043S\u0050\u0020\u0073\u0065\u0072\u0076\u0065\u0072\u0073");
};serverURL =cert .OCSPServer [0];};_ec ,_ffd :=_ba .CreateRequest (cert ,issuer ,&_ba .RequestOptions {Hash :_gd .Hash });if _ffd !=nil {return nil ,nil ,_ffd ;};_bd ,_ffd :=_gd .HTTPClient .Post (serverURL ,"\u0061p\u0070\u006c\u0069\u0063\u0061\u0074\u0069\u006f\u006e\u002f\u006fc\u0073\u0070\u002d\u0072\u0065\u0071\u0075\u0065\u0073\u0074",_c .NewReader (_ec ));
if _ffd !=nil {return nil ,nil ,_ffd ;};defer _bd .Body .Close ();_df ,_ffd :=_f .ReadAll (_bd .Body );if _ffd !=nil {return nil ,nil ,_ffd ;};if _bfa ,_ :=_e .Decode (_df );_bfa !=nil {_df =_bfa .Bytes ;};_ffa ,_ffd :=_ba .ParseResponseForCert (_df ,cert ,issuer );
if _ffd !=nil {return nil ,nil ,_ffd ;};return _ffa ,_df ,nil ;};

// CRLClient represents a CRL (Certificate revocation list) client.
// It is used to request revocation data from CRL servers.
type CRLClient struct{

// HTTPClient is the HTTP client used to make CRL requests.
// By default, an HTTP client with a 5 second timeout per request is used.
HTTPClient *_cg .Client ;};

// GetEncodedToken executes the timestamp request and returns the DER encoded
// timestamp token bytes.
func (_dbe *TimestampClient )GetEncodedToken (serverURL string ,req *_ff .Request )([]byte ,error ){if serverURL ==""{return nil ,_ge .Errorf ("\u006d\u0075\u0073\u0074\u0020\u0070r\u006f\u0076\u0069\u0064\u0065\u0020\u0074\u0069\u006d\u0065\u0073\u0074\u0061m\u0070\u0020\u0073\u0065\u0072\u0076\u0065r\u0020\u0055\u0052\u004c");
};if req ==nil {return nil ,_ge .Errorf ("\u0074\u0069\u006de\u0073\u0074\u0061\u006dp\u0020\u0072\u0065\u0071\u0075\u0065\u0073t\u0020\u0063\u0061\u006e\u006e\u006f\u0074\u0020\u0062\u0065\u0020\u006e\u0069\u006c");};_fb ,_ecg :=req .Marshal ();if _ecg !=nil {return nil ,_ecg ;
};_bfaa ,_ecg :=_cg .NewRequest ("\u0050\u004f\u0053\u0054",serverURL ,_c .NewBuffer (_fb ));if _ecg !=nil {return nil ,_ecg ;};_bfaa .Header .Set ("\u0043\u006f\u006et\u0065\u006e\u0074\u002d\u0054\u0079\u0070\u0065","a\u0070\u0070\u006c\u0069\u0063\u0061t\u0069\u006f\u006e\u002f\u0074\u0069\u006d\u0065\u0073t\u0061\u006d\u0070-\u0071u\u0065\u0072\u0079");
if _dbe .BeforeHTTPRequest !=nil {if _aa :=_dbe .BeforeHTTPRequest (_bfaa );_aa !=nil {return nil ,_aa ;};};_fc :=_dbe .HTTPClient ;if _fc ==nil {_fc =_gfg ();};_ee ,_ecg :=_fc .Do (_bfaa );if _ecg !=nil {return nil ,_ecg ;};defer _ee .Body .Close ();_agc ,_ecg :=_f .ReadAll (_ee .Body );
if _ecg !=nil {return nil ,_ecg ;};if _ee .StatusCode !=_cg .StatusOK {return nil ,_ge .Errorf ("\u0075\u006e\u0065x\u0070\u0065\u0063\u0074e\u0064\u0020\u0048\u0054\u0054\u0050\u0020s\u0074\u0061\u0074\u0075\u0073\u0020\u0063\u006f\u0064\u0065\u003a\u0020\u0025\u0064",_ee .StatusCode );
};var _dag struct{Version _bf .RawValue ;Content _bf .RawValue ;};if _ ,_ecg =_bf .Unmarshal (_agc ,&_dag );_ecg !=nil {return nil ,_ecg ;};return _dag .Content .FullBytes ,nil ;};

// TimestampClient represents a RFC 3161 timestamp client.
// It is used to obtain signed tokens from timestamp authority servers.
type TimestampClient struct{

// HTTPClient is the HTTP client used to make timestamp requests.
// By default, an HTTP client with a 5 second timeout per request is used.
HTTPClient *_cg .Client ;

// Callbacks.
BeforeHTTPRequest func (_gdg *_cg .Request )error ;};

// NewCRLClient returns a new CRL client.
func NewCRLClient ()*CRLClient {return &CRLClient {HTTPClient :_gfg ()}};

// NewTimestampClient returns a new timestamp client.
func NewTimestampClient ()*TimestampClient {return &TimestampClient {HTTPClient :_gfg ()}};

// MakeRequest makes a CRL request to the specified server and returns the
// response. If a server URL is not provided, it is extracted from the certificate.
func (_ag *CRLClient )MakeRequest (serverURL string ,cert *_db .Certificate )([]byte ,error ){if _ag .HTTPClient ==nil {_ag .HTTPClient =_gfg ();};if serverURL ==""{if len (cert .CRLDistributionPoints )==0{return nil ,_a .New ("\u0063e\u0072\u0074i\u0066\u0069\u0063\u0061t\u0065\u0020\u0064o\u0065\u0073\u0020\u006e\u006f\u0074\u0020\u0073\u0070ec\u0069\u0066\u0079 \u0061\u006ey\u0020\u0043\u0052\u004c\u0020\u0073e\u0072\u0076e\u0072\u0073");
};serverURL =cert .CRLDistributionPoints [0];};_cab ,_cbd :=_ag .HTTPClient .Get (serverURL );if _cbd !=nil {return nil ,_cbd ;};defer _cab .Body .Close ();_ac ,_cbd :=_f .ReadAll (_cab .Body );if _cbd !=nil {return nil ,_cbd ;};if _cc ,_ :=_e .Decode (_ac );
_cc !=nil {_ac =_cc .Bytes ;};return _ac ,nil ;};

// CertClient represents a X.509 certificate client. Its primary purpose
// is to download certificates.
type CertClient struct{

// HTTPClient is the HTTP client used to make certificate requests.
// By default, an HTTP client with a 5 second timeout per request is used.
HTTPClient *_cg .Client ;};func _gfg ()*_cg .Client {return &_cg .Client {Timeout :5*_g .Second }};

// NewTimestampRequest returns a new timestamp request based
// on the specified options.
func NewTimestampRequest (body _f .Reader ,opts *_ff .RequestOptions )(*_ff .Request ,error ){if opts ==nil {opts =&_ff .RequestOptions {};};if opts .Hash ==0{opts .Hash =_b .SHA256 ;};if !opts .Hash .Available (){return nil ,_db .ErrUnsupportedAlgorithm ;
};_ga :=opts .Hash .New ();if _ ,_bff :=_f .Copy (_ga ,body );_bff !=nil {return nil ,_bff ;};return &_ff .Request {HashAlgorithm :opts .Hash ,HashedMessage :_ga .Sum (nil ),Certificates :opts .Certificates ,TSAPolicyOID :opts .TSAPolicyOID ,Nonce :opts .Nonce },nil ;
};