//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package sanitize ;import (_c "github.com/unidoc/unipdf/v4/common";_e "github.com/unidoc/unipdf/v4/core";);

// Optimize optimizes `objects` and returns updated list of objects.
func (_ea *Sanitizer )Optimize (objects []_e .PdfObject )([]_e .PdfObject ,error ){return _ea .processObjects (objects );};

// GetSuspiciousObjects returns a count of each detected suspicious object.
func (_bb *Sanitizer )GetSuspiciousObjects ()map[string ]int {return _bb ._f };

// New returns a new sanitizer object.
func New (opts SanitizationOpts )*Sanitizer {return &Sanitizer {_ec :opts }};

// Sanitizer represents a sanitizer object.
// It implements the Optimizer interface to access the objects field from the writer.
type Sanitizer struct{_ec SanitizationOpts ;_f map[string ]int ;};func (_cf *Sanitizer )processObjects (_fe []_e .PdfObject )([]_e .PdfObject ,error ){_ee :=[]_e .PdfObject {};_ca :=_cf ._ec ;for _ ,_eg :=range _fe {switch _bd :=_eg .(type ){case *_e .PdfIndirectObject :_d ,_a :=_e .GetDict (_bd );
if _a {if _gc ,_dd :=_e .GetName (_d .Get ("\u0054\u0079\u0070\u0065"));_dd &&*_gc =="\u0043a\u0074\u0061\u006c\u006f\u0067"{if _ ,_fd :=_e .GetIndirect (_d .Get ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"));_fd &&_ca .OpenAction {_d .Remove ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e");
};}else if _da ,_ed :=_e .GetName (_d .Get ("\u0053"));_ed {switch *_da {case "\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074":if _ca .JavaScript {if _ece ,_ga :=_e .GetStream (_d .Get ("\u004a\u0053"));_ga {_ba :=[]byte {};_fda ,_ge :=_e .MakeStream (_ba ,nil );
if _ge ==nil {*_ece =*_fda ;};};_c .Log .Debug ("\u004a\u0061\u0076\u0061\u0073\u0063\u0072\u0069\u0070\u0074\u0020a\u0063\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070p\u0065\u0064\u002e");continue ;};case "\u0055\u0052\u0049":if _ca .URI {_c .Log .Debug ("\u0055\u0052\u0049\u0020ac\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070\u0070\u0065\u0064\u002e");
continue ;};case "\u0047\u006f\u0054\u006f":if _ca .GoTo {_c .Log .Debug ("G\u004fT\u004f\u0020\u0061\u0063\u0074\u0069\u006f\u006e \u0073\u006b\u0069\u0070pe\u0064\u002e");continue ;};case "\u0047\u006f\u0054o\u0052":if _ca .GoToR {_c .Log .Debug ("R\u0065\u006d\u006f\u0074\u0065\u0020G\u006f\u0054\u004f\u0020\u0061\u0063\u0074\u0069\u006fn\u0020\u0073\u006bi\u0070p\u0065\u0064\u002e");
continue ;};case "\u004c\u0061\u0075\u006e\u0063\u0068":if _ca .Launch {_c .Log .Debug ("\u004a\u0061\u0076\u0061\u0073\u0063\u0072\u0069\u0070\u0074\u0020a\u0063\u0074\u0069\u006f\u006e\u0020\u0073\u006b\u0069\u0070p\u0065\u0064\u002e");continue ;};case "\u0052e\u006e\u0064\u0069\u0074\u0069\u006fn":if _eea ,_ead :=_e .GetStream (_d .Get ("\u004a\u0053"));
_ead {_eed :=[]byte {};_ae ,_ege :=_e .MakeStream (_eed ,nil );if _ege ==nil {*_eea =*_ae ;};};};}else if _ad :=_d .Get ("\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074");_ad !=nil &&_ca .JavaScript {continue ;}else if _cfg ,_edg :=_e .GetName (_d .Get ("\u0054\u0079\u0070\u0065"));
_edg &&*_cfg =="\u0041\u006e\u006eo\u0074"&&_ca .JavaScript {if _fdg ,_cfgf :=_e .GetIndirect (_d .Get ("\u0050\u0061\u0072\u0065\u006e\u0074"));_cfgf {if _baa ,_eb :=_e .GetDict (_fdg .PdfObject );_eb {if _gca ,_fdga :=_e .GetDict (_baa .Get ("\u0041\u0041"));
_fdga {_aeg ,_ce :=_e .GetIndirect (_gca .Get ("\u004b"));if _ce {if _dc ,_bc :=_e .GetDict (_aeg .PdfObject );_bc {if _add ,_ef :=_e .GetName (_dc .Get ("\u0053"));_ef &&*_add =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_dc .Clear ();
}else if _gaf :=_gca .Get ("\u0046");_gaf !=nil {if _dcc ,_eee :=_e .GetIndirect (_gaf );_eee {if _de ,_cfc :=_e .GetDict (_dcc .PdfObject );_cfc {if _aea ,_dea :=_e .GetName (_de .Get ("\u0053"));_dea &&*_aea =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_de .Clear ();
};};};};};};};};};};};case *_e .PdfObjectStream :_c .Log .Debug ("\u0070d\u0066\u0020\u006f\u0062j\u0065\u0063\u0074\u0020\u0073t\u0072e\u0061m\u0020\u0074\u0079\u0070\u0065\u0020\u0025T",_bd );case *_e .PdfObjectStreams :_c .Log .Debug ("\u0070\u0064\u0066\u0020\u006f\u0062\u006a\u0065\u0063\u0074\u0020s\u0074\u0072\u0065\u0061\u006d\u0073\u0020\u0074\u0079\u0070e\u0020\u0025\u0054",_bd );
default:_c .Log .Debug ("u\u006e\u006b\u006e\u006fwn\u0020p\u0064\u0066\u0020\u006f\u0062j\u0065\u0063\u0074\u0020\u0025\u0054",_bd );};_ee =append (_ee ,_eg );};_cf .analyze (_ee );return _ee ,nil ;};func (_ag *Sanitizer )analyze (_fg []_e .PdfObject ){_bdg :=map[string ]int {};
for _ ,_gec :=range _fg {switch _be :=_gec .(type ){case *_e .PdfIndirectObject :_dcce ,_fb :=_e .GetDict (_be .PdfObject );if _fb {if _bcc ,_db :=_e .GetName (_dcce .Get ("\u0054\u0079\u0070\u0065"));_db &&*_bcc =="\u0043a\u0074\u0061\u006c\u006f\u0067"{if _ ,_bdb :=_e .GetIndirect (_dcce .Get ("\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"));
_bdb {_bdg ["\u004f\u0070\u0065\u006e\u0041\u0063\u0074\u0069\u006f\u006e"]++;};}else if _egea ,_dcb :=_e .GetName (_dcce .Get ("\u0053"));_dcb {_agg :=_egea .String ();if _agg =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"||_agg =="\u0055\u0052\u0049"||_agg =="\u0047\u006f\u0054\u006f"||_agg =="\u0047\u006f\u0054o\u0052"||_agg =="\u004c\u0061\u0075\u006e\u0063\u0068"{_bdg [_agg ]++;
}else if _agg =="\u0052e\u006e\u0064\u0069\u0074\u0069\u006fn"{if _ ,_fdge :=_e .GetStream (_dcce .Get ("\u004a\u0053"));_fdge {_bdg [_agg ]++;};};}else if _bg :=_dcce .Get ("\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074");_bg !=nil {_bdg ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;
}else if _bccd ,_dg :=_e .GetIndirect (_dcce .Get ("\u0050\u0061\u0072\u0065\u006e\u0074"));_dg {if _ab ,_eab :=_e .GetDict (_bccd .PdfObject );_eab {if _abe ,_bad :=_e .GetDict (_ab .Get ("\u0041\u0041"));_bad {_eac :=_abe .Get ("\u004b");_gb ,_efd :=_e .GetIndirect (_eac );
if _efd {if _adb ,_cb :=_e .GetDict (_gb .PdfObject );_cb {if _bf ,_cd :=_e .GetName (_adb .Get ("\u0053"));_cd &&*_bf =="\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"{_bdg ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;
}else if _ ,_bce :=_e .GetString (_adb .Get ("\u004a\u0053"));_bce {_bdg ["\u004a\u0061\u0076\u0061\u0053\u0063\u0072\u0069\u0070\u0074"]++;}else {_ffa :=_abe .Get ("\u0046");if _ffa !=nil {_dde ,_ffac :=_e .GetIndirect (_ffa );if _ffac {if _efc ,_dga :=_e .GetDict (_dde .PdfObject );
_dga {if _ged ,_dgc :=_e .GetName (_efc .Get ("\u0053"));_dgc {_fa :=_ged .String ();_bdg [_fa ]++;};};};};};};};};};};};};};_ag ._f =_bdg ;};

// SanitizationOpts specifies the objects to be removed during sanitization.
type SanitizationOpts struct{

// JavaScript specifies wether JavaScript action should be removed. JavaScript Actions, section 12.6.4.16 of PDF32000_2008
JavaScript bool ;

// URI specifies if URI actions should be removed. 12.6.4.7 URI Actions, PDF32000_2008.
URI bool ;

// GoToR removes remote GoTo actions. 12.6.4.3 Remote Go-To Actions, PDF32000_2008.
GoToR bool ;

// GoTo specifies wether GoTo actions should be removed. 12.6.4.2 Go-To Actions, PDF32000_2008.
GoTo bool ;

// RenditionJS enables removing of `JS` entry from a Rendition Action.
// The `JS` entry has a value of text string or stream containing a JavaScript script that shall be executed when the action is triggered.
// 12.6.4.13 Rendition Actions Table 214, PDF32000_2008.
RenditionJS bool ;

// OpenAction removes OpenAction entry from the document catalog.
OpenAction bool ;

// Launch specifies wether Launch Action should be removed.
// A launch action launches an application or opens or prints a document.
// 12.6.4.5 Launch Actions, PDF32000_2008.
Launch bool ;};