//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package timeutils ;import (_b "errors";_e "fmt";_ff "regexp";_f "strconv";_ga "time";);var _eba =_ff .MustCompile ("\u005cs\u002a\u0044\u005cs\u002a\u003a\u005cs\u002a(\\\u0064\u007b\u0034\u007d\u0029\u0028\u005cd\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064\u007b\u0032\u007d\u0029\u0028\u005c\u0064{2\u007d)\u003f\u0028\u005b\u002b\u002d\u005a]\u0029\u003f\u0028\u005c\u0064{\u0032\u007d\u0029\u003f\u0027\u003f\u0028\u005c\u0064\u007b\u0032}\u0029\u003f");
func ParsePdfTime (pdfTime string )(_ga .Time ,error ){_gab :=_eba .FindAllStringSubmatch (pdfTime ,1);if len (_gab )< 1{if len (pdfTime )> 0&&pdfTime [0]!='D'{pdfTime =_e .Sprintf ("\u0044\u003a\u0025\u0073",pdfTime );return ParsePdfTime (pdfTime );};
return _ga .Time {},_e .Errorf ("\u0069n\u0076\u0061\u006c\u0069\u0064\u0020\u0064\u0061\u0074\u0065\u0020s\u0074\u0072\u0069\u006e\u0067\u0020\u0028\u0025\u0073\u0029",pdfTime );};if len (_gab [0])!=10{return _ga .Time {},_b .New ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0072\u0065\u0067\u0065\u0078p\u0020\u0067\u0072\u006f\u0075\u0070 \u006d\u0061\u0074\u0063\u0068\u0020\u006c\u0065\u006e\u0067\u0074\u0068\u0020!\u003d\u0020\u0031\u0030");
};_geb ,_ :=_f .ParseInt (_gab [0][1],10,32);_gf ,_ :=_f .ParseInt (_gab [0][2],10,32);_be ,_ :=_f .ParseInt (_gab [0][3],10,32);_c ,_ :=_f .ParseInt (_gab [0][4],10,32);_bbg ,_ :=_f .ParseInt (_gab [0][5],10,32);_de ,_ :=_f .ParseInt (_gab [0][6],10,32);
var (_fb byte ;_ba int64 ;_ged int64 ;);_fb ='+';if len (_gab [0][7])> 0{switch _gab [0][7]{case "\u002d":_fb ='-';case "\u005a":_fb ='Z';};};if len (_gab [0][8])> 0{_ba ,_ =_f .ParseInt (_gab [0][8],10,32);}else {_ba =0;};if len (_gab [0][9])> 0{_ged ,_ =_f .ParseInt (_gab [0][9],10,32);
}else {_ged =0;};_eg :=int (_ba *60*60+_ged *60);switch _fb {case '-':_eg =-_eg ;case 'Z':_eg =0;};_bg :=_e .Sprintf ("\u0055\u0054\u0043\u0025\u0063\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064",_fb ,_ba ,_ged );_ae :=_ga .FixedZone (_bg ,_eg );return _ga .Date (int (_geb ),_ga .Month (_gf ),int (_be ),int (_c ),int (_bbg ),int (_de ),0,_ae ),nil ;
};func FormatPdfTime (in _ga .Time )string {_ge :=in .Format ("\u002d\u0030\u0037\u003a\u0030\u0030");_a ,_ :=_f .ParseInt (_ge [1:3],10,32);_fa ,_ :=_f .ParseInt (_ge [4:6],10,32);_d :=int64 (in .Year ());_eb :=int64 (in .Month ());_ag :=int64 (in .Day ());
_fe :=int64 (in .Hour ());_gg :=int64 (in .Minute ());_bc :=int64 (in .Second ());_ad :=_ge [0];return _e .Sprintf ("\u0044\u003a\u0025\u002e\u0034\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e\u0032\u0064\u0025\u002e2\u0064\u0025\u0063\u0025\u002e2\u0064\u0027%\u002e\u0032\u0064\u0027",_d ,_eb ,_ag ,_fe ,_gg ,_bc ,_ad ,_a ,_fa );
};