//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

// Package ps implements various functionalities needed for handling Postscript for PDF uses, in particular
// for PDF function type 4.
//
// Package ps implements various functionalities needed for handling Postscript for PDF uses, in particular
// for PDF function type 4.
package ps ;import (_b "bufio";_c "bytes";_g "errors";_e "fmt";_af "github.com/unidoc/unipdf/v4/common";_bg "github.com/unidoc/unipdf/v4/core";_a "io";_df "math";);func (_gae *PSOperand )ifelse (_afc *PSStack )error {_cfba ,_cba :=_afc .Pop ();if _cba !=nil {return _cba ;
};_deg ,_cba :=_afc .Pop ();if _cba !=nil {return _cba ;};_ccd ,_cba :=_afc .Pop ();if _cba !=nil {return _cba ;};_gga ,_gff :=_cfba .(*PSProgram );if !_gff {return ErrTypeCheck ;};_feda ,_gff :=_deg .(*PSProgram );if !_gff {return ErrTypeCheck ;};_efe ,_gff :=_ccd .(*PSBoolean );
if !_gff {return ErrTypeCheck ;};if _efe .Val {_baf :=_feda .Exec (_afc );return _baf ;};_cba =_gga .Exec (_afc );return _cba ;};func (_ccg *PSOperand )bitshift (_ddg *PSStack )error {_egb ,_gge :=_ddg .PopInteger ();if _gge !=nil {return _gge ;};_aaec ,_gge :=_ddg .PopInteger ();
if _gge !=nil {return _gge ;};var _ad int ;if _egb >=0{_ad =_aaec <<uint (_egb );}else {_ad =_aaec >>uint (-_egb );};_gge =_ddg .Push (MakeInteger (_ad ));return _gge ;};func (_eeg *PSOperand )sqrt (_eegg *PSStack )error {_fda ,_fbbf :=_eegg .PopNumberAsFloat64 ();
if _fbbf !=nil {return _fbbf ;};if _fda < 0{return ErrRangeCheck ;};_afaa :=_df .Sqrt (_fda );_fbbf =_eegg .Push (MakeReal (_afaa ));return _fbbf ;};func (_ccf *PSOperand )log (_egcf *PSStack )error {_gbg ,_gafc :=_egcf .PopNumberAsFloat64 ();if _gafc !=nil {return _gafc ;
};_egbe :=_df .Log10 (_gbg );_gafc =_egcf .Push (MakeReal (_egbe ));return _gafc ;};

// String returns a string representation of the stack.
func (_bgbba *PSStack )String ()string {_gca :="\u005b\u0020";for _ ,_dedb :=range *_bgbba {_gca +=_dedb .String ();_gca +="\u0020";};_gca +="\u005d";return _gca ;};func (_cgfg *PSOperand )cos (_cag *PSStack )error {_gee ,_cfb :=_cag .PopNumberAsFloat64 ();
if _cfb !=nil {return _cfb ;};_fbf :=_df .Cos (_gee *_df .Pi /180.0);_cfb =_cag .Push (MakeReal (_fbf ));return _cfb ;};var ErrStackUnderflow =_g .New ("\u0073t\u0061c\u006b\u0020\u0075\u006e\u0064\u0065\u0072\u0066\u006c\u006f\u0077");func (_bafe *PSParser )parseNumber ()(PSObject ,error ){_aab ,_acf :=_bg .ParseNumber (_bafe ._fga );
if _acf !=nil {return nil ,_acf ;};switch _edgg :=_aab .(type ){case *_bg .PdfObjectFloat :return MakeReal (float64 (*_edgg )),nil ;case *_bg .PdfObjectInteger :return MakeInteger (int (*_edgg )),nil ;};return nil ,_e .Errorf ("\u0075n\u0068\u0061\u006e\u0064\u006c\u0065\u0064\u0020\u006e\u0075\u006db\u0065\u0072\u0020\u0074\u0079\u0070\u0065\u0020\u0025\u0054",_aab );
};

// PSParser is a basic Postscript parser.
type PSParser struct{_fga *_b .Reader };func (_gce *PSOperand )eq (_eag *PSStack )error {_adb ,_bdg :=_eag .Pop ();if _bdg !=nil {return _bdg ;};_caea ,_bdg :=_eag .Pop ();if _bdg !=nil {return _bdg ;};_bge ,_dgd :=_adb .(*PSBoolean );_bbdd ,_bed :=_caea .(*PSBoolean );
if _dgd ||_bed {var _faa error ;if _dgd &&_bed {_faa =_eag .Push (MakeBool (_bge .Val ==_bbdd .Val ));}else {_faa =_eag .Push (MakeBool (false ));};return _faa ;};var _adg float64 ;var _ecd float64 ;if _gaff ,_gddg :=_adb .(*PSInteger );_gddg {_adg =float64 (_gaff .Val );
}else if _bbc ,_dec :=_adb .(*PSReal );_dec {_adg =_bbc .Val ;}else {return ErrTypeCheck ;};if _adc ,_bgec :=_caea .(*PSInteger );_bgec {_ecd =float64 (_adc .Val );}else if _fce ,_bedf :=_caea .(*PSReal );_bedf {_ecd =_fce .Val ;}else {return ErrTypeCheck ;
};if _df .Abs (_ecd -_adg )< _ce {_bdg =_eag .Push (MakeBool (true ));}else {_bdg =_eag .Push (MakeBool (false ));};return _bdg ;};func (_cfd *PSOperand )atan (_dfd *PSStack )error {_bcb ,_aae :=_dfd .PopNumberAsFloat64 ();if _aae !=nil {return _aae ;};
_acb ,_aae :=_dfd .PopNumberAsFloat64 ();if _aae !=nil {return _aae ;};if _bcb ==0{var _ecb error ;if _acb < 0{_ecb =_dfd .Push (MakeReal (270));}else {_ecb =_dfd .Push (MakeReal (90));};return _ecb ;};_ffg :=_acb /_bcb ;_dbad :=_df .Atan (_ffg )*180/_df .Pi ;
_aae =_dfd .Push (MakeReal (_dbad ));return _aae ;};func (_agcb *PSOperand )xor (_fbga *PSStack )error {_ecbd ,_edfe :=_fbga .Pop ();if _edfe !=nil {return _edfe ;};_dfga ,_edfe :=_fbga .Pop ();if _edfe !=nil {return _edfe ;};if _agca ,_fgc :=_ecbd .(*PSBoolean );
_fgc {_cgcb ,_adfg :=_dfga .(*PSBoolean );if !_adfg {return ErrTypeCheck ;};_edfe =_fbga .Push (MakeBool (_agca .Val !=_cgcb .Val ));return _edfe ;};if _afd ,_acg :=_ecbd .(*PSInteger );_acg {_dgaa ,_daaf :=_dfga .(*PSInteger );if !_daaf {return ErrTypeCheck ;
};_edfe =_fbga .Push (MakeInteger (_afd .Val ^_dgaa .Val ));return _edfe ;};return ErrTypeCheck ;};func (_afe *PSReal )String ()string {return _e .Sprintf ("\u0025\u002e\u0035\u0066",_afe .Val )};func (_ecg *PSOperand )abs (_bbd *PSStack )error {_ba ,_beg :=_bbd .Pop ();
if _beg !=nil {return _beg ;};if _gbf ,_edg :=_ba .(*PSReal );_edg {_ee :=_gbf .Val ;if _ee < 0{_beg =_bbd .Push (MakeReal (-_ee ));}else {_beg =_bbd .Push (MakeReal (_ee ));};}else if _eed ,_db :=_ba .(*PSInteger );_db {_fed :=_eed .Val ;if _fed < 0{_beg =_bbd .Push (MakeInteger (-_fed ));
}else {_beg =_bbd .Push (MakeInteger (_fed ));};}else {return ErrTypeCheck ;};return _beg ;};

// NewPSProgram returns an empty, initialized PSProgram.
func NewPSProgram ()*PSProgram {return &PSProgram {}};

// MakeBool returns a new PSBoolean object initialized with `val`.
func MakeBool (val bool )*PSBoolean {_gbfc :=PSBoolean {};_gbfc .Val =val ;return &_gbfc };func (_fe *PSProgram )DebugString ()string {_afg :="\u007b\u0020";for _ ,_ceb :=range *_fe {_afg +=_ceb .DebugString ();_afg +="\u0020";};_afg +="\u007d";return _afg ;
};func (_dc *PSOperand )String ()string {return string (*_dc )};var ErrUndefinedResult =_g .New ("\u0075\u006e\u0064\u0065fi\u006e\u0065\u0064\u0020\u0072\u0065\u0073\u0075\u006c\u0074\u0020\u0065\u0072\u0072o\u0072");func (_bgc *PSBoolean )DebugString ()string {return _e .Sprintf ("\u0062o\u006f\u006c\u003a\u0025\u0076",_bgc .Val );
};func (_fg *PSReal )Duplicate ()PSObject {_ga :=PSReal {};_ga .Val =_fg .Val ;return &_ga };var ErrRangeCheck =_g .New ("\u0072\u0061\u006e\u0067\u0065\u0020\u0063\u0068\u0065\u0063\u006b\u0020e\u0072\u0072\u006f\u0072");

// PopInteger specificially pops an integer from the top of the stack, returning the value as an int.
func (_afb *PSStack )PopInteger ()(int ,error ){_cfe ,_ecbf :=_afb .Pop ();if _ecbf !=nil {return 0,_ecbf ;};if _fddfd ,_agb :=_cfe .(*PSInteger );_agb {return _fddfd .Val ,nil ;};return 0,ErrTypeCheck ;};func (_ffbc *PSOperand )or (_cbb *PSStack )error {_dbdge ,_ecdf :=_cbb .Pop ();
if _ecdf !=nil {return _ecdf ;};_cad ,_ecdf :=_cbb .Pop ();if _ecdf !=nil {return _ecdf ;};if _eeea ,_gffg :=_dbdge .(*PSBoolean );_gffg {_aed ,_caba :=_cad .(*PSBoolean );if !_caba {return ErrTypeCheck ;};_ecdf =_cbb .Push (MakeBool (_eeea .Val ||_aed .Val ));
return _ecdf ;};if _bae ,_dgga :=_dbdge .(*PSInteger );_dgga {_fcb ,_dgf :=_cad .(*PSInteger );if !_dgf {return ErrTypeCheck ;};_ecdf =_cbb .Push (MakeInteger (_bae .Val |_fcb .Val ));return _ecdf ;};return ErrTypeCheck ;};

// PSObjectArrayToFloat64Array converts []PSObject into a []float64 array. Each PSObject must represent a number,
// otherwise a ErrTypeCheck error occurs.
func PSObjectArrayToFloat64Array (objects []PSObject )([]float64 ,error ){var _cd []float64 ;for _ ,_ae :=range objects {if _ab ,_ac :=_ae .(*PSInteger );_ac {_cd =append (_cd ,float64 (_ab .Val ));}else if _gd ,_f :=_ae .(*PSReal );_f {_cd =append (_cd ,_gd .Val );
}else {return nil ,ErrTypeCheck ;};};return _cd ,nil ;};func (_gab *PSOperand )cvr (_edc *PSStack )error {_eca ,_ecbc :=_edc .Pop ();if _ecbc !=nil {return _ecbc ;};if _dbga ,_ega :=_eca .(*PSReal );_ega {_ecbc =_edc .Push (MakeReal (_dbga .Val ));}else if _ebg ,_dee :=_eca .(*PSInteger );
_dee {_ecbc =_edc .Push (MakeReal (float64 (_ebg .Val )));}else {return ErrTypeCheck ;};return _ecbc ;};

// PSBoolean represents a boolean value.
type PSBoolean struct{Val bool ;};

// MakeOperand returns a new PSOperand object based on string `val`.
func MakeOperand (val string )*PSOperand {_dffe :=PSOperand (val );return &_dffe };func (_dgde *PSOperand )sub (_abaa *PSStack )error {_ccc ,_egec :=_abaa .Pop ();if _egec !=nil {return _egec ;};_gggdf ,_egec :=_abaa .Pop ();if _egec !=nil {return _egec ;
};_fffg ,_dfec :=_ccc .(*PSReal );_ged ,_afcb :=_ccc .(*PSInteger );if !_dfec &&!_afcb {return ErrTypeCheck ;};_gea ,_ffe :=_gggdf .(*PSReal );_cdf ,_adge :=_gggdf .(*PSInteger );if !_ffe &&!_adge {return ErrTypeCheck ;};if _afcb &&_adge {_acbc :=_cdf .Val -_ged .Val ;
_geeda :=_abaa .Push (MakeInteger (_acbc ));return _geeda ;};var _cgdg float64 =0;if _ffe {_cgdg =_gea .Val ;}else {_cgdg =float64 (_cdf .Val );};if _dfec {_cgdg -=_fffg .Val ;}else {_cgdg -=float64 (_ged .Val );};_egec =_abaa .Push (MakeReal (_cgdg ));
return _egec ;};func (_adf *PSOperand )ne (_dgg *PSStack )error {_dfde :=_adf .eq (_dgg );if _dfde !=nil {return _dfde ;};_dfde =_adf .not (_dgg );return _dfde ;};func (_gfed *PSOperand )sin (_egbd *PSStack )error {_gddf ,_acc :=_egbd .PopNumberAsFloat64 ();
if _acc !=nil {return _acc ;};_accf :=_df .Sin (_gddf *_df .Pi /180.0);_acc =_egbd .Push (MakeReal (_accf ));return _acc ;};func (_cdg *PSOperand )DebugString ()string {return _e .Sprintf ("\u006fp\u003a\u0027\u0025\u0073\u0027",*_cdg );};func (_gggb *PSOperand )ln (_cbc *PSStack )error {_ffa ,_cdb :=_cbc .PopNumberAsFloat64 ();
if _cdb !=nil {return _cdb ;};_ffge :=_df .Log (_ffa );_cdb =_cbc .Push (MakeReal (_ffge ));return _cdb ;};func (_effd *PSParser )parseFunction ()(*PSProgram ,error ){_dcg ,_ :=_effd ._fga .ReadByte ();if _dcg !='{'{return nil ,_g .New ("\u0069\u006ev\u0061\u006c\u0069d\u0020\u0066\u0075\u006e\u0063\u0074\u0069\u006f\u006e");
};_cega :=NewPSProgram ();for {_effd .skipSpaces ();_effd .skipComments ();_fagg ,_eba :=_effd ._fga .Peek (2);if _eba !=nil {if _eba ==_a .EOF {break ;};return nil ,_eba ;};if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u0050e\u0065k\u0020\u0073\u0074\u0072\u0069\u006e\u0067\u003a\u0020\u0025\u0073",string (_fagg ));
};if _fagg [0]=='}'{if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u0045\u004f\u0046 \u0066\u0075\u006e\u0063\u0074\u0069\u006f\u006e");};_effd ._fga .ReadByte ();break ;}else if _fagg [0]=='{'{if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u0046u\u006e\u0063\u0074\u0069\u006f\u006e!");
};_bbdb ,_ada :=_effd .parseFunction ();if _ada !=nil {return nil ,_ada ;};_cega .Append (_bbdb );}else if _bg .IsDecimalDigit (_fagg [0])||(_fagg [0]=='-'&&_bg .IsDecimalDigit (_fagg [1])){if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u002d>\u004e\u0075\u006d\u0062\u0065\u0072!");
};_fcbb ,_cdca :=_effd .parseNumber ();if _cdca !=nil {return nil ,_cdca ;};_cega .Append (_fcbb );}else {if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u002d>\u004fp\u0065\u0072\u0061\u006e\u0064 \u006f\u0072 \u0062\u006f\u006f\u006c\u003f");
};_fagg ,_ =_effd ._fga .Peek (5);_age :=string (_fagg );if _af .Log .IsLogLevel (_af .LogLevelTrace ){_af .Log .Trace ("\u0050\u0065\u0065k\u0020\u0073\u0074\u0072\u003a\u0020\u0025\u0073",_age );};if (len (_age )> 4)&&(_age [:5]=="\u0066\u0061\u006cs\u0065"){_ffba ,_cbce :=_effd .parseBool ();
if _cbce !=nil {return nil ,_cbce ;};_cega .Append (_ffba );}else if (len (_age )> 3)&&(_age [:4]=="\u0074\u0072\u0075\u0065"){_dfbe ,_bce :=_effd .parseBool ();if _bce !=nil {return nil ,_bce ;};_cega .Append (_dfbe );}else {_dcb ,_bgd :=_effd .parseOperand ();
if _bgd !=nil {return nil ,_bgd ;};_cega .Append (_dcb );};};};return _cega ,nil ;};

// Append appends an object to the PSProgram.
func (_cgf *PSProgram )Append (obj PSObject ){*_cgf =append (*_cgf ,obj )};func (_ag *PSReal )DebugString ()string {return _e .Sprintf ("\u0072e\u0061\u006c\u003a\u0025\u002e\u0035f",_ag .Val );};func (_fb *PSProgram )Duplicate ()PSObject {_gb :=&PSProgram {};
for _ ,_bd :=range *_fb {_gb .Append (_bd .Duplicate ());};return _gb ;};

// PSStack defines a stack of PSObjects. PSObjects can be pushed on or pull from the stack.
type PSStack []PSObject ;

// PSInteger represents an integer.
type PSInteger struct{Val int ;};func (_fec *PSOperand )Duplicate ()PSObject {_ed :=*_fec ;return &_ed };func _afgd (_baefd int )int {if _baefd < 0{return -_baefd ;};return _baefd ;};func (_eddd *PSOperand )lt (_edf *PSStack )error {_cgb ,_bfec :=_edf .PopNumberAsFloat64 ();
if _bfec !=nil {return _bfec ;};_def ,_bfec :=_edf .PopNumberAsFloat64 ();if _bfec !=nil {return _bfec ;};if _df .Abs (_def -_cgb )< _ce {_dffc :=_edf .Push (MakeBool (false ));return _dffc ;}else if _def < _cgb {_cbe :=_edf .Push (MakeBool (true ));return _cbe ;
}else {_agcd :=_edf .Push (MakeBool (false ));return _agcd ;};};func (_gad *PSBoolean )Duplicate ()PSObject {_dg :=PSBoolean {};_dg .Val =_gad .Val ;return &_dg };func (_cef *PSOperand )mul (_bdfd *PSStack )error {_fdb ,_ffad :=_bdfd .Pop ();if _ffad !=nil {return _ffad ;
};_agfc ,_ffad :=_bdfd .Pop ();if _ffad !=nil {return _ffad ;};_cafc ,_aefgg :=_fdb .(*PSReal );_agg ,_eec :=_fdb .(*PSInteger );if !_aefgg &&!_eec {return ErrTypeCheck ;};_cea ,_gfe :=_agfc .(*PSReal );_cgab ,_baa :=_agfc .(*PSInteger );if !_gfe &&!_baa {return ErrTypeCheck ;
};if _eec &&_baa {_bgcfe :=_agg .Val *_cgab .Val ;_gcff :=_bdfd .Push (MakeInteger (_bgcfe ));return _gcff ;};var _eggdg float64 ;if _aefgg {_eggdg =_cafc .Val ;}else {_eggdg =float64 (_agg .Val );};if _gfe {_eggdg *=_cea .Val ;}else {_eggdg *=float64 (_cgab .Val );
};_ffad =_bdfd .Push (MakeReal (_eggdg ));return _ffad ;};func (_daf *PSOperand )ifCondition (_cfg *PSStack )error {_adgd ,_aeb :=_cfg .Pop ();if _aeb !=nil {return _aeb ;};_dea ,_aeb :=_cfg .Pop ();if _aeb !=nil {return _aeb ;};_cab ,_bab :=_adgd .(*PSProgram );
if !_bab {return ErrTypeCheck ;};_cgc ,_bab :=_dea .(*PSBoolean );if !_bab {return ErrTypeCheck ;};if _cgc .Val {_cgd :=_cab .Exec (_cfg );return _cgd ;};return nil ;};

// MakeInteger returns a new PSInteger object initialized with `val`.
func MakeInteger (val int )*PSInteger {_efdg :=PSInteger {};_efdg .Val =val ;return &_efdg };func (_dfb *PSOperand )floor (_befd *PSStack )error {_eee ,_cee :=_befd .Pop ();if _cee !=nil {return _cee ;};if _ecgc ,_caf :=_eee .(*PSReal );_caf {_cee =_befd .Push (MakeReal (_df .Floor (_ecgc .Val )));
}else if _fdcf ,_eaf :=_eee .(*PSInteger );_eaf {_cee =_befd .Push (MakeInteger (_fdcf .Val ));}else {return ErrTypeCheck ;};return _cee ;};func (_fddf *PSOperand )round (_bgf *PSStack )error {_aedb ,_afa :=_bgf .Pop ();if _afa !=nil {return _afa ;};if _dedc ,_ccdc :=_aedb .(*PSReal );
_ccdc {_afa =_bgf .Push (MakeReal (_df .Floor (_dedc .Val +0.5)));}else if _cec ,_bea :=_aedb .(*PSInteger );_bea {_afa =_bgf .Push (MakeInteger (_cec .Val ));}else {return ErrTypeCheck ;};return _afa ;};func (_dbd *PSOperand )ge (_feca *PSStack )error {_eagf ,_daa :=_feca .PopNumberAsFloat64 ();
if _daa !=nil {return _daa ;};_beb ,_daa :=_feca .PopNumberAsFloat64 ();if _daa !=nil {return _daa ;};if _df .Abs (_beb -_eagf )< _ce {_ceg :=_feca .Push (MakeBool (true ));return _ceg ;}else if _beb > _eagf {_agff :=_feca .Push (MakeBool (true ));return _agff ;
}else {_dga :=_feca .Push (MakeBool (false ));return _dga ;};};

// NewPSExecutor returns an initialized PSExecutor for an input `program`.
func NewPSExecutor (program *PSProgram )*PSExecutor {_bf :=&PSExecutor {};_bf .Stack =NewPSStack ();_bf ._de =program ;return _bf ;};

// NewPSParser returns a new instance of the PDF Postscript parser from input data.
func NewPSParser (content []byte )*PSParser {_cbag :=PSParser {};_eagge :=_c .NewBuffer (content );_cbag ._fga =_b .NewReader (_eagge );return &_cbag ;};func (_ebgc *PSOperand )truncate (_dbdd *PSStack )error {_fgeg ,_fbcd :=_dbdd .Pop ();if _fbcd !=nil {return _fbcd ;
};if _gfeb ,_edceg :=_fgeg .(*PSReal );_edceg {_dbb :=int (_gfeb .Val );_fbcd =_dbdd .Push (MakeReal (float64 (_dbb )));}else if _fgg ,_gbe :=_fgeg .(*PSInteger );_gbe {_fbcd =_dbdd .Push (MakeInteger (_fgg .Val ));}else {return ErrTypeCheck ;};return _fbcd ;
};func (_abe *PSOperand )idiv (_fffe *PSStack )error {_agc ,_edce :=_fffe .Pop ();if _edce !=nil {return _edce ;};_cdc ,_edce :=_fffe .Pop ();if _edce !=nil {return _edce ;};_cgff ,_fbg :=_agc .(*PSInteger );if !_fbg {return ErrTypeCheck ;};if _cgff .Val ==0{return ErrUndefinedResult ;
};_fcee ,_fbg :=_cdc .(*PSInteger );if !_fbg {return ErrTypeCheck ;};_dfa :=_fcee .Val /_cgff .Val ;_edce =_fffe .Push (MakeInteger (_dfa ));return _edce ;};func (_ggaa *PSParser )parseOperand ()(*PSOperand ,error ){var _decd []byte ;for {_efda ,_eabd :=_ggaa ._fga .Peek (1);
if _eabd !=nil {if _eabd ==_a .EOF {break ;};return nil ,_eabd ;};if _bg .IsDelimiter (_efda [0]){break ;};if _bg .IsWhiteSpace (_efda [0]){break ;};_dedd ,_ :=_ggaa ._fga .ReadByte ();_decd =append (_decd ,_dedd );};if len (_decd )==0{return nil ,_g .New ("\u0069\u006e\u0076al\u0069\u0064\u0020\u006f\u0070\u0065\u0072\u0061\u006e\u0064\u0020\u0028\u0065\u006d\u0070\u0074\u0079\u0029");
};return MakeOperand (string (_decd )),nil ;};func (_bbb *PSOperand )index (_cbd *PSStack )error {_cegd ,_gcc :=_cbd .Pop ();if _gcc !=nil {return _gcc ;};_egc ,_gag :=_cegd .(*PSInteger );if !_gag {return ErrTypeCheck ;};if _egc .Val < 0{return ErrRangeCheck ;
};if _egc .Val > len (*_cbd )-1{return ErrStackUnderflow ;};_fbfa :=(*_cbd )[len (*_cbd )-1-_egc .Val ];_gcc =_cbd .Push (_fbfa .Duplicate ());return _gcc ;};func (_aeg *PSOperand )pop (_ddgc *PSStack )error {_ ,_geed :=_ddgc .Pop ();if _geed !=nil {return _geed ;
};return nil ;};

// MakeReal returns a new PSReal object initialized with `val`.
func MakeReal (val float64 )*PSReal {_deb :=PSReal {};_deb .Val =val ;return &_deb };

// Execute executes the program for an input parameters `objects` and returns a slice of output objects.
func (_gf *PSExecutor )Execute (objects []PSObject )([]PSObject ,error ){for _ ,_gg :=range objects {_da :=_gf .Stack .Push (_gg );if _da !=nil {return nil ,_da ;};};_fd :=_gf ._de .Exec (_gf .Stack );if _fd !=nil {_af .Log .Debug ("\u0045x\u0065c\u0020\u0066\u0061\u0069\u006c\u0065\u0064\u003a\u0020\u0025\u0076",_fd );
return nil ,_fd ;};_bb :=[]PSObject (*_gf .Stack );_gf .Stack .Empty ();return _bb ,nil ;};

// PSOperand represents a Postscript operand (text string).
type PSOperand string ;func (_efb *PSParser )skipSpaces ()(int ,error ){_cgef :=0;for {_aggd ,_aga :=_efb ._fga .Peek (1);if _aga !=nil {return 0,_aga ;};if _bg .IsWhiteSpace (_aggd [0]){_efb ._fga .ReadByte ();_cgef ++;}else {break ;};};return _cgef ,nil ;
};

// Pop pops an object from the top of the stack.
func (_dca *PSStack )Pop ()(PSObject ,error ){if len (*_dca )< 1{return nil ,ErrStackUnderflow ;};_ebb :=(*_dca )[len (*_dca )-1];*_dca =(*_dca )[0:len (*_dca )-1];return _ebb ,nil ;};func (_efg *PSOperand )mod (_gcg *PSStack )error {_fcd ,_fcfd :=_gcg .Pop ();
if _fcfd !=nil {return _fcfd ;};_bag ,_fcfd :=_gcg .Pop ();if _fcfd !=nil {return _fcfd ;};_gggd ,_eagg :=_fcd .(*PSInteger );if !_eagg {return ErrTypeCheck ;};if _gggd .Val ==0{return ErrUndefinedResult ;};_ccbf ,_eagg :=_bag .(*PSInteger );if !_eagg {return ErrTypeCheck ;
};_ecad :=_ccbf .Val %_gggd .Val ;_fcfd =_gcg .Push (MakeInteger (_ecad ));return _fcfd ;};func (_eaa *PSOperand )not (_gdda *PSStack )error {_gaec ,_cbaa :=_gdda .Pop ();if _cbaa !=nil {return _cbaa ;};if _ggaf ,_fbbb :=_gaec .(*PSBoolean );_fbbb {_cbaa =_gdda .Push (MakeBool (!_ggaf .Val ));
return _cbaa ;}else if _cbda ,_bac :=_gaec .(*PSInteger );_bac {_cbaa =_gdda .Push (MakeInteger (^_cbda .Val ));return _cbaa ;}else {return ErrTypeCheck ;};};func (_gaab *PSParser )skipComments ()error {if _ ,_abd :=_gaab .skipSpaces ();_abd !=nil {return _abd ;
};_fedf :=true ;for {_bfg ,_cged :=_gaab ._fga .Peek (1);if _cged !=nil {_af .Log .Debug ("\u0045\u0072\u0072\u006f\u0072\u0020\u0025\u0073",_cged .Error ());return _cged ;};if _fedf &&_bfg [0]!='%'{return nil ;};_fedf =false ;if (_bfg [0]!='\r')&&(_bfg [0]!='\n'){_gaab ._fga .ReadByte ();
}else {break ;};};return _gaab .skipComments ();};func (_egge *PSOperand )copy (_caef *PSStack )error {_eff ,_dac :=_caef .PopInteger ();if _dac !=nil {return _dac ;};if _eff < 0{return ErrRangeCheck ;};if _eff > len (*_caef ){return ErrRangeCheck ;};*_caef =append (*_caef ,(*_caef )[len (*_caef )-_eff :]...);
return nil ;};func (_fac *PSOperand )exp (_dda *PSStack )error {_ggg ,_fcf :=_dda .PopNumberAsFloat64 ();if _fcf !=nil {return _fcf ;};_dbgd ,_fcf :=_dda .PopNumberAsFloat64 ();if _fcf !=nil {return _fcf ;};if _df .Abs (_ggg )< 1&&_dbgd < 0{return ErrUndefinedResult ;
};_cdde :=_df .Pow (_dbgd ,_ggg );_fcf =_dda .Push (MakeReal (_cdde ));return _fcf ;};func (_abag *PSOperand )neg (_feg *PSStack )error {_gec ,_degf :=_feg .Pop ();if _degf !=nil {return _degf ;};if _beda ,_ddd :=_gec .(*PSReal );_ddd {_degf =_feg .Push (MakeReal (-_beda .Val ));
return _degf ;}else if _degg ,_fcfde :=_gec .(*PSInteger );_fcfde {_degf =_feg .Push (MakeInteger (-_degg .Val ));return _degf ;}else {return ErrTypeCheck ;};};func (_baef *PSOperand )roll (_fad *PSStack )error {_adgdb ,_dcdc :=_fad .Pop ();if _dcdc !=nil {return _dcdc ;
};_gadf ,_dcdc :=_fad .Pop ();if _dcdc !=nil {return _dcdc ;};_fabc ,_ffbe :=_adgdb .(*PSInteger );if !_ffbe {return ErrTypeCheck ;};_ebc ,_ffbe :=_gadf .(*PSInteger );if !_ffbe {return ErrTypeCheck ;};if _ebc .Val < 0{return ErrRangeCheck ;};if _ebc .Val ==0||_ebc .Val ==1{return nil ;
};if _ebc .Val > len (*_fad ){return ErrStackUnderflow ;};for _ccge :=0;_ccge < _afgd (_fabc .Val );_ccge ++{var _aee []PSObject ;_aee =(*_fad )[len (*_fad )-(_ebc .Val ):len (*_fad )];if _fabc .Val > 0{_eac :=_aee [len (_aee )-1];_aee =append ([]PSObject {_eac },_aee [0:len (_aee )-1]...);
}else {_bbf :=_aee [len (_aee )-_ebc .Val ];_aee =append (_aee [1:],_bbf );};_cage :=append ((*_fad )[0:len (*_fad )-_ebc .Val ],_aee ...);_fad =&_cage ;};return nil ;};

// NewPSStack returns an initialized PSStack.
func NewPSStack ()*PSStack {return &PSStack {}};const _ce =0.000001;func (_ccb *PSOperand )div (_cge *PSStack )error {_bgcf ,_dce :=_cge .Pop ();if _dce !=nil {return _dce ;};_bgb ,_dce :=_cge .Pop ();if _dce !=nil {return _dce ;};_ece ,_gdc :=_bgcf .(*PSReal );
_dfe ,_ege :=_bgcf .(*PSInteger );if !_gdc &&!_ege {return ErrTypeCheck ;};if _gdc &&_ece .Val ==0{return ErrUndefinedResult ;};if _ege &&_dfe .Val ==0{return ErrUndefinedResult ;};_abgb ,_ea :=_bgb .(*PSReal );_fc ,_bgaf :=_bgb .(*PSInteger );if !_ea &&!_bgaf {return ErrTypeCheck ;
};var _fdc float64 ;if _ea {_fdc =_abgb .Val ;}else {_fdc =float64 (_fc .Val );};if _gdc {_fdc /=_ece .Val ;}else {_fdc /=float64 (_dfe .Val );};_dce =_cge .Push (MakeReal (_fdc ));return _dce ;};func (_edfc *PSParser )parseBool ()(*PSBoolean ,error ){_bgbb ,_bcd :=_edfc ._fga .Peek (4);
if _bcd !=nil {return MakeBool (false ),_bcd ;};if (len (_bgbb )>=4)&&(string (_bgbb [:4])=="\u0074\u0072\u0075\u0065"){_edfc ._fga .Discard (4);return MakeBool (true ),nil ;};_bgbb ,_bcd =_edfc ._fga .Peek (5);if _bcd !=nil {return MakeBool (false ),_bcd ;
};if (len (_bgbb )>=5)&&(string (_bgbb [:5])=="\u0066\u0061\u006cs\u0065"){_edfc ._fga .Discard (5);return MakeBool (false ),nil ;};return MakeBool (false ),_g .New ("\u0075n\u0065\u0078\u0070\u0065c\u0074\u0065\u0064\u0020\u0062o\u006fl\u0065a\u006e\u0020\u0073\u0074\u0072\u0069\u006eg");
};

// PopNumberAsFloat64 pops and return the numeric value of the top of the stack as a float64.
// Real or integer only.
func (_bcc *PSStack )PopNumberAsFloat64 ()(float64 ,error ){_cabac ,_acfa :=_bcc .Pop ();if _acfa !=nil {return 0,_acfa ;};if _dggd ,_cbbe :=_cabac .(*PSReal );_cbbe {return _dggd .Val ,nil ;}else if _eedf ,_gcfe :=_cabac .(*PSInteger );_gcfe {return float64 (_eedf .Val ),nil ;
}else {return 0,ErrTypeCheck ;};};

// PSExecutor has its own execution stack and is used to executre a PS routine (program).
type PSExecutor struct{Stack *PSStack ;_de *PSProgram ;};var ErrTypeCheck =_g .New ("\u0074\u0079p\u0065\u0020\u0063h\u0065\u0063\u006b\u0020\u0065\u0072\u0072\u006f\u0072");

// DebugString returns a descriptive string representation of the stack - intended for debugging.
func (_bdfc *PSStack )DebugString ()string {_dad :="\u005b\u0020";for _ ,_agbd :=range *_bdfc {_dad +=_agbd .DebugString ();_dad +="\u0020";};_dad +="\u005d";return _dad ;};

// PSProgram defines a Postscript program which is a series of PS objects (arguments, commands, programs etc).
type PSProgram []PSObject ;func (_cg *PSInteger )Duplicate ()PSObject {_bba :=PSInteger {};_bba .Val =_cg .Val ;return &_bba };

// Empty empties the stack.
func (_bcf *PSStack )Empty (){*_bcf =[]PSObject {}};func (_cgfgg *PSOperand )exch (_ddb *PSStack )error {_agfd ,_fdd :=_ddb .Pop ();if _fdd !=nil {return _fdd ;};_afgg ,_fdd :=_ddb .Pop ();if _fdd !=nil {return _fdd ;};_fdd =_ddb .Push (_agfd );if _fdd !=nil {return _fdd ;
};_fdd =_ddb .Push (_afgg );return _fdd ;};func (_bec *PSOperand )ceiling (_fbab *PSStack )error {_aag ,_aaed :=_fbab .Pop ();if _aaed !=nil {return _aaed ;};if _efc ,_efd :=_aag .(*PSReal );_efd {_aaed =_fbab .Push (MakeReal (_df .Ceil (_efc .Val )));
}else if _dfg ,_feb :=_aag .(*PSInteger );_feb {_aaed =_fbab .Push (MakeInteger (_dfg .Val ));}else {_aaed =ErrTypeCheck ;};return _aaed ;};func (_fa *PSBoolean )String ()string {return _e .Sprintf ("\u0025\u0076",_fa .Val )};

// Parse parses the postscript and store as a program that can be executed.
func (_dfedb *PSParser )Parse ()(*PSProgram ,error ){_dfedb .skipSpaces ();_fef ,_gecf :=_dfedb ._fga .Peek (2);if _gecf !=nil {return nil ,_gecf ;};if _fef [0]!='{'{return nil ,_g .New ("\u0069\u006e\u0076\u0061\u006c\u0069\u0064\u0020\u0050\u0053\u0020\u0050\u0072\u006f\u0067\u0072\u0061\u006d\u0020\u006e\u006f\u0074\u0020\u0073t\u0061\u0072\u0074\u0069\u006eg\u0020\u0077i\u0074\u0068\u0020\u007b");
};_gdg ,_gecf :=_dfedb .parseFunction ();if _gecf !=nil &&_gecf !=_a .EOF {return nil ,_gecf ;};return _gdg ,_gecf ;};func (_fbd *PSOperand )cvi (_abad *PSStack )error {_gbfd ,_fdf :=_abad .Pop ();if _fdf !=nil {return _fdf ;};if _dbg ,_eggd :=_gbfd .(*PSReal );
_eggd {_eda :=int (_dbg .Val );_fdf =_abad .Push (MakeInteger (_eda ));}else if _cdd ,_cfdb :=_gbfd .(*PSInteger );_cfdb {_bdc :=_cdd .Val ;_fdf =_abad .Push (MakeInteger (_bdc ));}else {return ErrTypeCheck ;};return _fdf ;};

// PSObject represents a postscript object.
type PSObject interface{

// Duplicate makes a fresh copy of the PSObject.
Duplicate ()PSObject ;

// DebugString returns a descriptive representation of the PSObject with more information than String()
// for debugging purposes.
DebugString ()string ;

// String returns a string representation of the PSObject.
String ()string ;};

// Exec executes the program, typically leaving output values on the stack.
func (_ggd *PSProgram )Exec (stack *PSStack )error {for _ ,_cff :=range *_ggd {var _bfb error ;switch _abf :=_cff .(type ){case *PSInteger :_fab :=_abf ;_bfb =stack .Push (_fab );case *PSReal :_dfc :=_abf ;_bfb =stack .Push (_dfc );case *PSBoolean :_ge :=_abf ;
_bfb =stack .Push (_ge );case *PSProgram :_fbc :=_abf ;_bfb =stack .Push (_fbc );case *PSOperand :_ffc :=_abf ;_bfb =_ffc .Exec (stack );default:return ErrTypeCheck ;};if _bfb !=nil {return _bfb ;};};return nil ;};func (_fba *PSOperand )and (_abg *PSStack )error {_cae ,_cffa :=_abg .Pop ();
if _cffa !=nil {return _cffa ;};_eedg ,_cffa :=_abg .Pop ();if _cffa !=nil {return _cffa ;};if _bdf ,_fff :=_cae .(*PSBoolean );_fff {_cb ,_fee :=_eedg .(*PSBoolean );if !_fee {return ErrTypeCheck ;};_cffa =_abg .Push (MakeBool (_bdf .Val &&_cb .Val ));
return _cffa ;};if _fbb ,_egg :=_cae .(*PSInteger );_egg {_gdd ,_ef :=_eedg .(*PSInteger );if !_ef {return ErrTypeCheck ;};_cffa =_abg .Push (MakeInteger (_fbb .Val &_gdd .Val ));return _cffa ;};return ErrTypeCheck ;};func (_ec *PSInteger )String ()string {return _e .Sprintf ("\u0025\u0064",_ec .Val )};


// Exec executes the operand `op` in the state specified by `stack`.
func (_ca *PSOperand )Exec (stack *PSStack )error {_aa :=ErrUnsupportedOperand ;switch *_ca {case "\u0061\u0062\u0073":_aa =_ca .abs (stack );case "\u0061\u0064\u0064":_aa =_ca .add (stack );case "\u0061\u006e\u0064":_aa =_ca .and (stack );case "\u0061\u0074\u0061\u006e":_aa =_ca .atan (stack );
case "\u0062\u0069\u0074\u0073\u0068\u0069\u0066\u0074":_aa =_ca .bitshift (stack );case "\u0063e\u0069\u006c\u0069\u006e\u0067":_aa =_ca .ceiling (stack );case "\u0063\u006f\u0070\u0079":_aa =_ca .copy (stack );case "\u0063\u006f\u0073":_aa =_ca .cos (stack );
case "\u0063\u0076\u0069":_aa =_ca .cvi (stack );case "\u0063\u0076\u0072":_aa =_ca .cvr (stack );case "\u0064\u0069\u0076":_aa =_ca .div (stack );case "\u0064\u0075\u0070":_aa =_ca .dup (stack );case "\u0065\u0071":_aa =_ca .eq (stack );case "\u0065\u0078\u0063\u0068":_aa =_ca .exch (stack );
case "\u0065\u0078\u0070":_aa =_ca .exp (stack );case "\u0066\u006c\u006fo\u0072":_aa =_ca .floor (stack );case "\u0067\u0065":_aa =_ca .ge (stack );case "\u0067\u0074":_aa =_ca .gt (stack );case "\u0069\u0064\u0069\u0076":_aa =_ca .idiv (stack );case "\u0069\u0066":_aa =_ca .ifCondition (stack );
case "\u0069\u0066\u0065\u006c\u0073\u0065":_aa =_ca .ifelse (stack );case "\u0069\u006e\u0064e\u0078":_aa =_ca .index (stack );case "\u006c\u0065":_aa =_ca .le (stack );case "\u006c\u006f\u0067":_aa =_ca .log (stack );case "\u006c\u006e":_aa =_ca .ln (stack );
case "\u006c\u0074":_aa =_ca .lt (stack );case "\u006d\u006f\u0064":_aa =_ca .mod (stack );case "\u006d\u0075\u006c":_aa =_ca .mul (stack );case "\u006e\u0065":_aa =_ca .ne (stack );case "\u006e\u0065\u0067":_aa =_ca .neg (stack );case "\u006e\u006f\u0074":_aa =_ca .not (stack );
case "\u006f\u0072":_aa =_ca .or (stack );case "\u0070\u006f\u0070":_aa =_ca .pop (stack );case "\u0072\u006f\u0075n\u0064":_aa =_ca .round (stack );case "\u0072\u006f\u006c\u006c":_aa =_ca .roll (stack );case "\u0073\u0069\u006e":_aa =_ca .sin (stack );
case "\u0073\u0071\u0072\u0074":_aa =_ca .sqrt (stack );case "\u0073\u0075\u0062":_aa =_ca .sub (stack );case "\u0074\u0072\u0075\u006e\u0063\u0061\u0074\u0065":_aa =_ca .truncate (stack );case "\u0078\u006f\u0072":_aa =_ca .xor (stack );};return _aa ;
};

// PSReal represents a real number.
type PSReal struct{Val float64 ;};func (_dfed *PSOperand )gt (_dff *PSStack )error {_aaf ,_dbdg :=_dff .PopNumberAsFloat64 ();if _dbdg !=nil {return _dbdg ;};_cfa ,_dbdg :=_dff .PopNumberAsFloat64 ();if _dbdg !=nil {return _dbdg ;};if _df .Abs (_cfa -_aaf )< _ce {_ade :=_dff .Push (MakeBool (false ));
return _ade ;}else if _cfa > _aaf {_fbdc :=_dff .Push (MakeBool (true ));return _fbdc ;}else {_bfe :=_dff .Push (MakeBool (false ));return _bfe ;};};

// Push pushes an object on top of the stack.
func (_aac *PSStack )Push (obj PSObject )error {if len (*_aac )> 100{return ErrStackOverflow ;};*_aac =append (*_aac ,obj );return nil ;};func (_cf *PSInteger )DebugString ()string {return _e .Sprintf ("\u0069\u006e\u0074\u003a\u0025\u0064",_cf .Val );
};var ErrStackOverflow =_g .New ("\u0073\u0074\u0061\u0063\u006b\u0020\u006f\u0076\u0065r\u0066\u006c\u006f\u0077");func (_adef *PSOperand )le (_eab *PSStack )error {_gcf ,_gaa :=_eab .PopNumberAsFloat64 ();if _gaa !=nil {return _gaa ;};_aef ,_gaa :=_eab .PopNumberAsFloat64 ();
if _gaa !=nil {return _gaa ;};if _df .Abs (_aef -_gcf )< _ce {_aefg :=_eab .Push (MakeBool (true ));return _aefg ;}else if _aef < _gcf {_fea :=_eab .Push (MakeBool (true ));return _fea ;}else {_bbbb :=_eab .Push (MakeBool (false ));return _bbbb ;};};func (_gc *PSOperand )add (_bef *PSStack )error {_edd ,_bga :=_bef .Pop ();
if _bga !=nil {return _bga ;};_bbde ,_bga :=_bef .Pop ();if _bga !=nil {return _bga ;};_dd ,_eb :=_edd .(*PSReal );_aba ,_cga :=_edd .(*PSInteger );if !_eb &&!_cga {return ErrTypeCheck ;};_bc ,_dba :=_bbde .(*PSReal );_dcd ,_bege :=_bbde .(*PSInteger );
if !_dba &&!_bege {return ErrTypeCheck ;};if _cga &&_bege {_cc :=_aba .Val +_dcd .Val ;_bgg :=_bef .Push (MakeInteger (_cc ));return _bgg ;};var _dfcf float64 ;if _eb {_dfcf =_dd .Val ;}else {_dfcf =float64 (_aba .Val );};if _dba {_dfcf +=_bc .Val ;}else {_dfcf +=float64 (_dcd .Val );
};_bga =_bef .Push (MakeReal (_dfcf ));return _bga ;};func (_dab *PSOperand )dup (_ead *PSStack )error {_ffb ,_bdfb :=_ead .Pop ();if _bdfb !=nil {return _bdfb ;};_bdfb =_ead .Push (_ffb );if _bdfb !=nil {return _bdfb ;};_bdfb =_ead .Push (_ffb .Duplicate ());
return _bdfb ;};var ErrUnsupportedOperand =_g .New ("\u0075\u006e\u0073\u0075pp\u006f\u0072\u0074\u0065\u0064\u0020\u006f\u0070\u0065\u0072\u0061\u006e\u0064");func (_eg *PSProgram )String ()string {_gfd :="\u007b\u0020";for _ ,_fge :=range *_eg {_gfd +=_fge .String ();
_gfd +="\u0020";};_gfd +="\u007d";return _gfd ;};