//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package basic ;import _db "github.com/unidoc/unipdf/v4/internal/jbig2/errors";func (_e IntsMap )Get (key uint64 )(int ,bool ){_a ,_ac :=_e [key ];if !_ac {return 0,false ;};if len (_a )==0{return 0,false ;};return _a [0],true ;};func (_c IntSlice )Size ()int {return len (_c )};
func (_dbb IntSlice )Get (index int )(int ,error ){if index > len (_dbb )-1{return 0,_db .Errorf ("\u0049\u006e\u0074S\u006c\u0069\u0063\u0065\u002e\u0047\u0065\u0074","\u0069\u006e\u0064\u0065x:\u0020\u0025\u0064\u0020\u006f\u0075\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006eg\u0065",index );
};return _dbb [index ],nil ;};func (_ae *Stack )peek ()(interface{},bool ){_fb :=_ae .top ();if _fb ==-1{return nil ,false ;};return _ae .Data [_fb ],true ;};func (_eg *IntSlice )Copy ()*IntSlice {_abg :=IntSlice (make ([]int ,len (*_eg )));copy (_abg ,*_eg );
return &_abg ;};func (_bd *NumSlice )AddInt (v int ){*_bd =append (*_bd ,float32 (v ))};func (_cc *Stack )top ()int {return len (_cc .Data )-1};func Sign (v float32 )float32 {if v >=0.0{return 1.0;};return -1.0;};func Abs (v int )int {if v > 0{return v ;
};return -v ;};type IntsMap map[uint64 ][]int ;func (_ea *IntSlice )Add (v int )error {if _ea ==nil {return _db .Error ("\u0049\u006e\u0074S\u006c\u0069\u0063\u0065\u002e\u0041\u0064\u0064","\u0073\u006c\u0069\u0063\u0065\u0020\u006e\u006f\u0074\u0020\u0064\u0065f\u0069\u006e\u0065\u0064");
};*_ea =append (*_ea ,v );return nil ;};type Stack struct{Data []interface{};Aux *Stack ;};func (_bbf *Stack )Push (v interface{}){_bbf .Data =append (_bbf .Data ,v )};func (_gc NumSlice )Get (i int )(float32 ,error ){if i < 0||i > len (_gc )-1{return 0,_db .Errorf ("\u004e\u0075\u006dS\u006c\u0069\u0063\u0065\u002e\u0047\u0065\u0074","\u0069n\u0064\u0065\u0078\u003a\u0020\u0027\u0025\u0064\u0027\u0020\u006fu\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006e\u0067\u0065",i );
};return _gc [i ],nil ;};type IntSlice []int ;func (_f IntsMap )Add (key uint64 ,value int ){_f [key ]=append (_f [key ],value )};func Max (x ,y int )int {if x > y {return x ;};return y ;};func (_bc *Stack )Pop ()(_ff interface{},_ffg bool ){_ff ,_ffg =_bc .peek ();
if !_ffg {return nil ,_ffg ;};_bc .Data =_bc .Data [:_bc .top ()];return _ff ,true ;};func (_aa *Stack )Peek ()(_eaf interface{},_fe bool ){return _aa .peek ()};func (_dc *Stack )Len ()int {return len (_dc .Data )};func Ceil (numerator ,denominator int )int {if numerator %denominator ==0{return numerator /denominator ;
};return (numerator /denominator )+1;};func (_ab IntsMap )Delete (key uint64 ){delete (_ab ,key )};func (_ad *NumSlice )Add (v float32 ){*_ad =append (*_ad ,v )};func (_ag IntsMap )GetSlice (key uint64 )([]int ,bool ){_da ,_g :=_ag [key ];if !_g {return nil ,false ;
};return _da ,true ;};func Min (x ,y int )int {if x < y {return x ;};return y ;};func NewIntSlice (i int )*IntSlice {_b :=IntSlice (make ([]int ,i ));return &_b };func (_acd NumSlice )GetIntSlice ()[]int {_dag :=make ([]int ,len (_acd ));for _fd ,_bb :=range _acd {_dag [_fd ]=int (_bb );
};return _dag ;};func (_cd NumSlice )GetInt (i int )(int ,error ){const _gf ="\u0047\u0065\u0074\u0049\u006e\u0074";if i < 0||i > len (_cd )-1{return 0,_db .Errorf (_gf ,"\u0069n\u0064\u0065\u0078\u003a\u0020\u0027\u0025\u0064\u0027\u0020\u006fu\u0074\u0020\u006f\u0066\u0020\u0072\u0061\u006e\u0067\u0065",i );
};_bf :=_cd [i ];return int (_bf +Sign (_bf )*0.5),nil ;};type NumSlice []float32 ;func NewNumSlice (i int )*NumSlice {_daf :=NumSlice (make ([]float32 ,i ));return &_daf };